- src/components/App/App.test.tsx
- src/components/Temp/tests/TempActions.test.tsx
- src/components/Temp/tests/TempReducer.test.tsx
- src/components/Temp/tests/__mocks__/axios.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/2)
> Repair front end unit tests

- src/goals/MergeDupGoal/MergeDupStep/WordCard/component.tsx
- src/types/word.tsx
I should have included this in my last PR but I forgot.
The backend gives us a semantic domain object that has lowercase initial characters for it's members.
This changes the frontend's representation to match this
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/41)
> Change semantic domain members to be lowercase initial

- src/components/Login/LoginActions.tsx
- src/components/Login/LoginPage/LoginComponent.tsx
- src/components/Login/LoginPage/index.tsx
- src/components/Login/LoginPage/tests/LoginComponent.test.tsx
- src/components/Login/LoginReducer.tsx
- src/components/Login/RegisterPage/RegisterComponent.tsx
- Keep the spinner from showing on the login page when you navigate back to it
- Fix issue: pressing enter on the register page would go back to login without submitting the form
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/124)
> Fix register page submission and login page spinner

- package-lock.json
- src/components/CreateProject/CreateProjectReducer.tsx
- src/components/CreateProject/tests/CreateProjectReducer.test.tsx
- src/components/DraggableWord/reducer.tsx
- src/components/DraggableWord/tests/reducer.test.tsx
- src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorReducer.tsx
- src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorReducer.test.tsx
- src/components/Login/LoginReducer.tsx
- src/components/Login/tests/LoginReducer.test.tsx
- src/components/Project/ProjectReducer.tsx
- src/components/Project/tests/ProjectReducer.test.tsx
- src/components/Temp/TempReducer.tsx
- src/components/Temp/tests/TempReducer.test.tsx
- src/components/TreeView/TreeViewReducer.ts
- src/components/TreeView/tests/TreeViewReducer.test.tsx
- src/goals/CharInventoryCreation/CharacterInventoryReducer.tsx
- src/goals/CharInventoryCreation/tests/CharacterInventoryReducer.test.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
- src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx
Reset the following state on logout:
- loginState
- createProjectState
- treeViewState
- goalSelectorState
- mergeDuplicateGoal
- characterInventoryState
- currentProject
- tempState
GoalsState was already reset in "Reset redux store".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/171)
> Reset redux store 2

- src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/AlignedList.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DomainCell.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/SenseCell.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx
* Fix some React key issues
* Index is still used for some items, but since re-arranging senses aren't allowed, this isn't much of an issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/232)
> Fix loading no items in ReviewEntries

- src/goals/MergeDupGoal/MergeDupStep/MergeRow/MergeRowComponent.tsx
If a a column has more than one word and two of those
words have different verns and the last word that contains
the vern that is currently selected is removed from the column
it will reset the selected vern to a different one that is in the
list
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/242)
> Make vern reset if vern is missing from list

- deploy/roles/nodejs/defaults/main.yml
The previous requirement that node.js 10.16.0 was too specific and is no 
longer available on the repo.  Now will install the current 10.x 
version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/274)
> Remove requirement for specific version of nodejs

- .gitignore
- deploy/hosts
- deploy/vagrant-installer/Vagrantfile
- docs/deploy/README.md
Create a vagrant vm that can be used to install TheCombine on other targets, such as an Intel NUC for field use.  The vm allows users to install TheCombine when not running on a Linux platform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/280)
> Install vm

- deploy/group_vars/nuc/main.yml
- deploy/group_vars/server/main.yml
- deploy/roles/the_combine_app/defaults/main.yml
- deploy/roles/the_combine_app/handlers/main.yml
- deploy/roles/the_combine_app/tasks/backend_service.yml
- deploy/roles/the_combine_app/tasks/install.yml
- deploy/roles/the_combine_app/templates/combine_backend.service.j2
- deploy/roles/the_combine_app/templates/config.js.j2
- deploy/roles/the_combine_app/templates/rsyslog.conf.j2
- deploy/vars/config_common.yml
- docs/deploy/README.md
This pull request includes residual fixes that were missed from the previous pull request, notably:
* corrected the listen address for Apache on the demo server
* corrected quoting in the template for the config.js configuration file
* set the logging levels to "Debug" for Default, Microsoft, and System
* added information about the Ansible vault password to `docs/deploy/README.md`
* added restart of the combine backend service if the software is updated
In addition, the backend service has been setup to log messages to `/var/log/combine.log` (as well as `/var/log/syslog`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/286)
> Pr285 residuals

- .gitignore
- README.md
Clarify setup instructions to help make development setup more reproducible on Windows.
- State that `ASPNETCORE_JWT_SECRET_KEY` must be 16 characters long
- Provide optional install commands for the [Chocolately ](https://chocolatey.org/)package manager for Windows to ease dependency installation.
- Clarify that .NET Core 2.1 LTS should be used (currently)
- Mention you may need to trust the local self-signed cert in the browser
- Ignore [JetBrains Rider](https://www.jetbrains.com/rider/) IDE files. (Rider is [free for open source projects](https://www.jetbrains.com/opensource/)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/289)
> Clarify Windows development setup instructions

- src/backend/index.tsx
- src/backend/localStorage.tsx
- src/components/AppBar/UserMenu.tsx
- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
- src/components/GoalTimeline/GoalsActions.tsx
- src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
- src/components/Login/AuthHeaders.tsx
- src/components/PrivateRoute/index.tsx
- src/components/Project/ProjectReducer.tsx
- src/components/ProjectScreen/ChooseProject/ChooseProjectComponent.tsx
- src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx
- src/components/UserSettings/AvatarUpload.tsx
- src/components/UserSettings/UserSettings.tsx
- src/goals/CharInventoryCreation/CharacterInventoryActions.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
- src/localStorage/index.tsx
Closes #314
This is a somewhat conservative first step to collapse 7-8 duplicated redefinitions of the `getCurrentUser()` function. There are more accesses to `localStorage` that could be grouped here, but this is a helpful step towards allowing #310 to continue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/317)
> Create a single module from which to interact with local storage

- Backend/Properties/launchSettings.json
Currently during development relaunching the backend keeps opening new browser tabs. This is an annoyance, especially since the developer generally doesn't need to browse to the backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/348)
> Don't open a browser tab every time the backend relaunches

- Backend/Controllers/FrontierController.cs
- Backend/Controllers/UserEditController.cs
Closes #369
Also:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/370)
> Suppress backend warnings triggered in release mode

- deploy/build.sh
- deploy/playbook_publish.yml
- deploy/roles/dotnet_core/defaults/main.yml
- deploy/roles/the_combine_app/defaults/main.yml
- deploy/roles/the_combine_app/tasks/backend_cert.yml
- deploy/roles/the_combine_app/tasks/install.yml
- deploy/roles/the_combine_app/tasks/main.yml
- deploy/roles/the_combine_app/tasks/test.yml
- deploy/vars/config_common.yml
Closes #371.
Issue #371 states that the role for the_combine_app installs the Backend software from a hardcoded directory.  This PR makes the following changes to address this issue:
- Use .NET version specified in BackendFramework.csproj to select directory for Backend software to install
- Add a test to verify that the backend service is running at the end of the installation process
- Update build script to remove old builds before building the backend
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/372)
> Correct directory used for Backend software

- deploy/playbook_publish.yml
The trailing '/' is required so that .../netcore3.1/* is copied to {{ 
dest_dir}} instead of {{ dest_dir }}/netcore3.1.
*Assertion:* The problem is limited to how TheCombine backend software is installed on the target.  Verification can be performed on a NUC or the demo server.
*Verification Method*
1. Verify installation on clean target
1. Reinstall OS on NUC from restore image (OS, users & ssh keys setup) & upgrade packages
1. Install app using .NET 3.1 on NUC
1. `playbook_nuc.yml` to install .NET 3.1
1. Run `./build.sh`
1. Run `playbook_publish.yml` to install TheCombine on the NUC
1. *Verify* operation of TheCombine
1. *Verify* combine_backend service is running on NUC
1. Connect to *TheCombine* via WiFi access point
1. *Verify* frontend can connect to backend, e.g. register a new …
> Add trailing '/' to combine_build_dir variable.

- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/tests/ReviewEntriesActions.test.tsx
closes #312 
The review entries page purposefully prevented you from removing all senses from a word. This has been removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/387)
> Allow deleting all senses from a word

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/405)
> Fix README getting started link to point to .NET Core 3.1

- src/backend/index.tsx
projectRoles is the field used to specify a users relation to a project while workedProjects is used to store a list of the things a user has done on a project. If a user makes no changes to a project, invited but hasn't done anything, then it would be entirely acceptable for that project not to show up in the users workedProjects, however projectRoles will have to mention the relationship.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/403)
> Revert getProjectsByUser to use projectRoles

- .gitignore
- README.md
- mongo_database/.gitignore
- setupMongo.ts
Closes #400 
- Add development instructions for Ubuntu 18.04
- Fix `npm run predatabase` script
These instructions were tested on a clean, up-to-date Ubuntu 18.04 VM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/401)
> Add Ubuntu 18.04 development instructions

- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
Resolves #328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/435)
> Patch refreshWord to return 'en' for analysisLang if none is stored.

- src/backend/index.tsx
- src/types/runtimeConfig.tsx
#446 Introduced an error causing all backend wrappers to drop the `/v1` prefix from their routes. I have changed appending the `/v1` prefix to be handled by the backend wrapper rather than the runtimeConfig.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/447)
> Fix baseURL

- deploy/group_vars/nuc/main.yml
- deploy/group_vars/server/main.yml
Update server configurations to match changes made in PR #447.
PR#447 updates RuntimeConfig.baseUrl() so that it returns the URL of the server, not the URL of the Backend service.  This requires that the config.js files that are generated to deploy the application must not have the '/v1' in any configuration items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/462)
> Remove '/v1' from baseUrl configuration files

- README.md
Explain that `STMP` environment values must be kept secret, which is why they are not provided in the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/513)
> Add clarification about the SMTP variable values

- Backend/Interfaces/IEmailContext.cs
- Backend/Startup.cs
This fixes the immediate problems related to #509.
The backend can now startup, but as logged in error messages, email services will not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/522)
> Allow backend to start up even if SMTP environment variables are not set

- Backend/Dockerfile
- docker-compose.yml
- nginx/nginx.conf
When running inside of Docker, the backend now runs on port 5000 rather than port 80. This is an important first step towards #514, as now running the backend itself inside the container no longer requires root priveledges.
This change is completed isolated within the Docker Compose project and does not affect any external deployment configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/523)
> Run backend on a non-privileged port within Docker container

- src/components/GoalTimeline/GoalTimelineVertical/GoalTimelineVertical.tsx
- src/components/GoalTimeline/GoalTimelineVertical/tests/GoalTimelineVertical.test.tsx
My pull request for removing duplicate goal suggestions in Data Cleanup > Other Options contains a bug for when the goalSuggestions redux state is empty. To reproduce the issue, select Data Cleanup > Our Recommendation 3 times.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/567)
> Fix goal suggestions

- src/components/DataEntry/DataEntryHeader/DataEntryHeader.tsx
- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
- src/components/DataEntry/DataEntryTable/ExistingEntry/DeleteEntry/DeleteEntry.tsx
- src/components/Pronunciations/AudioPlayer.tsx
- src/components/Pronunciations/RecorderIcon.tsx
- src/components/Pronunciations/tests/__snapshots__/Pronunciations.test.tsx.snap
For the sake of vision-impaired users, we will eventually want a more thorough refactor of how everything behaves with keyboard-and-voice-only operation.
For now, this resolves #479
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/579)
> Make TAB skip things that don't play well with ENTER.

- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
parseWord was comparing the Analysis Language name instead of the bcp47
This caused recording to make the glosses empty until the page refreshed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/622)
> Fix bug in parseWord

- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/tests/NewEntry.test.tsx
- src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx
- src/components/DataEntry/DataEntryTable/RecentEntry/tests/RecentEntry.test.tsx
- src/components/DataEntry/DataEntryTable/VernWithSuggestions/SenseDialog/SenseDialog.tsx
- src/components/DataEntry/DataEntryTable/VernWithSuggestions/VernDialog/VernDialog.tsx
- src/components/DataEntry/DataEntryTable/VernWithSuggestions/VernDialog/tests/VernDialog.test.tsx
- src/components/DataEntry/DataEntryTable/VernWithSuggestions/VernWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/VernWithSuggestions/tests/VernWithSuggestions.test.tsx
- src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes.ts
**Priority:** Without this change, senses without "en" never show up in the NewEntry dialogs.
* Use project's first analysis language in new entries instead of 'en'
* Allow non-'en' senses to show up in the dialogs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/615)
> [DataEntryTable] Remove "en" assumption

- src/components/ProjectSettings/ProjectExport/ExportProjectButton.tsx
Projects more than ~5MB made the export fail. By creating a temp url instead of using the file directly on the link, larger projects can now be exported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/638)
> Create local url for file export

- Backend/Services/LiftApiServices.cs
* Also improve the definition of "Active Words"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/639)
> Fix crash involving multiple glosses for one language

- src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx
The bpc47 code had mistakenly been given to LanguagePicker for `name` and `font` properties. See "en" showing up twice below:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/644)
> [ProjectScreen] Fix property assignment in analysis language picker

- Backend/Services/WordApiServices.cs
The wrong index was being used, but @jmgrady identified a simplification to avoid any use of `oldSenseIndex` and `newSenseIndex`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/676)
> [WordApiServices > WordIsUnique] Remove index usage

- package-lock.json
- package.json
- src/components/Pronunciations/Recorder.ts
`mimeType: "audio/webm;codecs=pcm"` is presently unavailable in typescript, so reverting part of #649 in order to export the full audio stream
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/682)
> Uninstall @types/recordrtc; Use codecs=pcm

- README.md
I remember being confused because the instructions say to install 'MongoDB server' but the link is to "Install MongoDB Community Edition" (which includes the server, but doesn't say so explicitly on the page).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/700)
> README Install list: remove 'server' from 'MongoDB'

- Backend/Program.cs
- nginx/nginx.conf
Without this fix, NGINX will block large POSTs from clients when they try to import large projects or upload audio clips longer than ~5 seconds:
```
frontend_1  | 2020/09/04 16:24:49 [error] 6#6: *12 client intended to send too large body: 59610499 bytes, client: 172.19.0.1, server: , request: "POST /v1/projects/5f526a5172d7140006be5616/words/upload HTTP/1.1", host: "localhost", referrer: "https://localhost/"
```
Without this fix, Kestrel will also throw an error:
```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
Route matched with {action = "UploadLiftFile", controller = "Lift"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] UploadLiftFile(System.String, BackendFramework.Models.FileUpload) on …
```
> Increase max request body size to allow clients to import large projects

- package-lock.json
- package.json
The tsc in package.json (introduced in #724) causes a failure for me (Ubuntu 18.04) when running `npm start`:
```
> thecombine@0.2.0-alpha.1 predatabase /home/dror/sil/TheCombine
> tsc setupMongo.ts && node setupMongo.js
setupMongo.ts(5,37): error TS1005: ';' expected.
setupMongo.ts(6,9): error TS1005: ';' expected.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! thecombine@0.2.0-alpha.1 predatabase: `tsc setupMongo.ts && node setupMongo.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the thecombine@0.2.0-alpha.1 predatabase script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
--- …
> Remove tsc from package.json

- src/backend/tests/localStorage.test.tsx
- src/components/Login/tests/LoginActions.test.tsx
- src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx
- src/goals/DefaultGoal/BaseGoalWidget/tests/BaseGoalWidget.test.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/730)
> Try to get lgtm to stop complaining about sensitive info in localStorage

- README.md
- package.json
Closes #704
- Split `npm run test` into two, one for backend and one for frontend
- Also document CLI instructions for running a subset of either set of tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/732)
> Split frontend and backend unit testing into two scripts

- README.md
The rest of the setup/installation instructions work for Mac.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/752)
> Add environment variable instruction for Mac

- README.md
- package.json
Everywhere else, the backend is referred to as `backend`. Use the same term for the `npm` script used to start the backend.
Relates to #757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/760)
> Normalize backend starting npm script name

- dev-requirements.txt
Weekly update of Python dev-dependencies.
```bash
(venv) $ pip-compile --upgrade dev-requirements.in
```
Developers who are running Python linting locally will want to `rm -r .tox/` to ensure their tox environments are recreated with the latest dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/767)
> Upgrade Python dev-dependencies

- README.md
Our repo shows the latest version of `master`, but it didn't show the latest release. Users of Combine would likely be interested in knowing what our latest release is, since they will not be (generally) using pre-release versions.
- Also separate build status badges from project info with new line to make it easier to read
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/769)
> Add GitHub release badge and 

- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
- src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepActions.test.tsx
- src/resources/translations.json
Resolves #765
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/766)
> Merge continue

- src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx
- src/resources/translations.json
Since The Combine is out of sync with crowdin, some translations needed to be manual transferred before re-syncing.
In this pr:
- Removed unnecessary phrases; 
- Cleanup capitalization/punctuation/spacing;
- Add crowdin translations not previously transferred (but probably missed a few); 
- Repeat English phrase where translation is missing.
Once in crowdin, all existing translations can be reviewed and (re)approved, and missing translations added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/770)
> Translation cleanup before crowdin sync

- nginx/templates/thecombine.conf.template
TLS 1.0 and 1.1 have known security concerns. All major browser support at least TLS 1.2.
This disables the default NGINX configuration portion that enables support for TLS 1.0 and 1.1, and also adds support for TLS 1.3, the new standard that is more secure and can also be more performant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/779)
> Disable TLS 1.0 and 1.1 and enable TLS 1.3 in NGINX configuration

- certmgr/Dockerfile
- certmgr/scripts/func.py
- certmgr/scripts/letsencrypt_cert.py
PR #777 introduced 2 defects:
- in `certmgr/Dockerfile`, the destination directory for the entrypoint scripts needs a trailing '/'
- from the review, the python scripts were updated to use pathlib instead of strings for file paths.  One function, `Path.readlink()` is not available until Python 3.9; the certmgr container is at Python 3.7.  The 2 uses of `Path.readlink()` are changed to use `os.readlink()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/781)
> Fix defects from PR#777

- src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx
- src/components/Pronunciations/PronunciationsComponent.tsx
Resolves #668
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/782)
> Limit audio re-rendering; Remove unnecessary key

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend/Controllers/LiftController.cs
- Backend/Services/LiftApiServices.cs
Closes #786
Should help some with #656
- The fix for LIFT export fixes a true disk space leak.
- Since Lift import can only be performed once, there is no recurring leak fixed on the import side, but the temporary file is still removed
The following files will no longer persist after an import in `.CombineFiles/<ProjectID>/Import`:
- `<temp-name-with-date>.zip`
Or after an export in `.CombineFiles/<ProjectID>/Export`:
- `<temp-name>.zip`
- `LiftExport`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/791)
> Remove temporary .zip files generated during Lift import and export

- src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
- src/types/word.tsx
Resolves #607
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/796)
> [NewEntry] Allow submission with no gloss

- src/components/TreeView/TreeViewHeader.tsx
- src/components/TreeView/tests/__snapshots__/TreeDepiction.test.tsx.snap
- src/components/TreeView/tests/__snapshots__/TreeViewComponent.test.tsx.snap
- src/components/TreeView/tests/__snapshots__/TreeViewHeader.test.tsx.snap
Resolves #794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/804)
> Modify TreeView search's event handler to preempt material-table's

- nginx/templates/thecombine.conf.template
Set cache expiration to 12 hours on the frontend routes so that if the server's frontend implementation is updated, clients will automatically pull in a fresh version at the beginning of the next day.
This fixes the issue where users have to manually refresh to update their cached frontend implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/809)
> Set cache expiration for frontend route

- Backend/Controllers/LiftController.cs
Revert #801
This did not have any noticeable improvement on memory usage.
#811 is tracking trying to fix this issue more holistically.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/813)
> Remove GC.Collect() call from Lift Export

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend/Controllers/LiftController.cs
- Backend/Interfaces/ILiftService.cs
- Backend/Services/LiftApiServices.cs
Follow on to #819 
Relate to #814 
- Fix memory leak in Lift export where Lift exported files are never removed from an internal dictionary
- Reduce medium-term memory usage of lift export by 33% by only storing binary contents of export rather than base64 encoded contents before download
Note: There is still a possibility of a memory leak if a user exports a project but never downloads it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/820)
> Fix memory leak in Lift Export

- docker_deploy/group_vars/qa/main.yml
Set the profile used to access the AWS Elastic Container Registry to ecr_read_only for QA servers.  Servers (QA & Live server) only need to download docker images; they do not create images to upload to the registry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/831)
> Set AWS profile for ECR to ecr_read_only

- src/components/Pronunciations/AudioRecorder.tsx
- src/components/Pronunciations/RecorderIcon.tsx
- src/components/Pronunciations/tests/__snapshots__/Pronunciations.test.tsx.snap
- src/resources/translations.json
Replaces #838.
The `ref` property is not implicit with a functional component as it is for a traditional component.
Thus, `Tooltip` cannot be used around a functional component, because it tries to pass its `ref` to its children.
Previously in `AudioRecorder`, we had `Tooltip` wrapped around the functional component `RecorderIcon`.
To fix the associated warnings, this pr moves `Tooltip` to within `RecorderIcon`.
Should we ever need tooltip around a functional component: https://material-ui.com/guides/composition/#caveat-with-refs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/839)
> Move Tooltip inside RecorderIcon.

- src/components/UserSettings/tests/AvatarUpload.test.tsx
This resolves three warnings thrown by `npm run test-frontend -- AvatarUpload`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/840)
> Convert AvatarUpload testing from react-dom to react-test-renderer.

- src/components/App/DefaultState.tsx
- src/components/DataEntry/tests/DataEntryComponent.test.tsx
- src/components/Pronunciations/AudioPlayer.tsx
- src/components/Pronunciations/PronunciationsActions.tsx
- src/components/Pronunciations/PronunciationsReducer.tsx
- src/components/Pronunciations/RecorderIcon.tsx
- src/components/Pronunciations/tests/Pronunciations.test.tsx
- src/components/Pronunciations/tests/__snapshots__/Pronunciations.test.tsx.snap
- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesReducer.tsx
- src/rootReducer.tsx
- src/types/index.tsx
Extract recording from ReviewEntries state and expand with playing for stand-alone Pronunciations state.
With this pr, clicking any play or record icon will halt an active recording.
Resolves #330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/847)
> Implement Pronunciations state/actions/reducer.

- src/goals/CreateCharInv/CreateCharInv.tsx
- src/goals/CreateStrWordInv/CreateStrWordInv.tsx
- src/goals/HandleFlags/HandleFlags.tsx
- src/goals/MergeDupGoal/MergeDups.tsx
- src/goals/ReviewEntries/ReviewEntries.tsx
- src/goals/SpellCheckGloss/SpellCheckGloss.tsx
- src/goals/ValidateChars/ValidateChars.tsx
- src/goals/ValidateStrWords/ValidateStrWords.tsx
- src/types/baseGoal.tsx
- src/types/goals.tsx
Was never implemented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/857)
> Remove vestigial Goal property Tool.

- src/components/Login/LoginPage/LoginComponent.tsx
Incorrectly added in #862, triggers a Console warning on the Login Page.
Only works on `<Grid container>`; does nothing in `<Grid item>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/869)
> Remove bad justify prop.

- src/components/Login/LoginPage/LoginComponent.tsx
- src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx
Eliminate `npm run test-frontend -- tests/BaseGoalScreen` console errors:
```
console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
at module.exports (/Users/dror/sil/TheCombine/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
at HTMLCanvasElementImpl.getContext (/Users/dror/sil/TheCombine/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
at HTMLCanvasElement.getContext (/Users/dror/sil/TheCombine/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
at hasBrowserCanvas (/Users/dror/sil/TheCombine/node_modules/jspdf/src/libs/png.js:480:36)
at /Users/dror/sil/TheCombine/node_modules/jspdf/src/libs/png.js:489:3
at …
```
> Update BaseGoalScreen testing.

- .gitattributes
- docs/api/projects/get_semantic_domains.md
- docs/api/projects/project.md
- docs/api/projects/project_with_user.md
- docs/api/projects/words/gloss.md
- docs/api/projects/words/semanticDomain.md
- docs/api/projects/words/sense.md
- docs/data_model.md
- docs/deploy/README.md
- docs/docker_deploy/README.md
- docs/frontend/README.md
- docs/frontend/addingComponents.md
- docs/frontend/fileStructure/backend.md
- docs/frontend/fileStructure/components.md
- docs/frontend/fileStructure/goals.md
- docs/frontend/fileStructure/index.tsx.md
- docs/frontend/fileStructure/rootReducer.tsx.md
- docs/frontend/fileStructure/serviceWorker.ts.md
- docs/frontend/fileStructure/store.tsx.md
- docs/frontend/fileStructure/types.md
- docs/meeting_notes/5-30_Cleaner_Workflow/cleaner_workflow_5-30.md
- docs/meeting_notes/cleaner_workflow_5-30.md
- docs/ts_style_guide.md
- package.json
- user_guide/docs/dataEntry.md
- user_guide/docs/project.md
- Wrap Markdown lines at 120 characters for consistency. This also makes it possible for developers to view two Markdown pages side by side on the same monitor
- Set Git to require Unix Line Feeds for Markdown and YAML on all platforms to avoid Windows developers having Git conflict with Prettier
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/874)
> Enable formatting prose in Markdown

- Backend/Controllers/LiftController.cs
- Backend/Program.cs
- user_guide/docs/project.md
- user_guide/mkdocs.yml
- Restrict large file uploads to only the Lift Upload endpoint 
- Rather than open up the entire backend to large file uploads (for example avatars and audio), only selectively extend the max request size for Lift Import
- Also document this limitation in the user guide.
- Add admonition MkDocs extension
- Related to #694 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/875)
> Restrict large file uploads to only the Lift Upload endpoint

- Backend.Tests/Mocks/ProjectServiceMock.cs
- Backend/Controllers/LiftController.cs
- Backend/Controllers/ProjectController.cs
- Backend/Interfaces/IProjectService.cs
- Backend/Services/ProjectApiServices.cs
- Remove compiler warning suppression and instead properly use async/await in `CanUploadLift` methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/876)
> Make ProjectService.CanImportLift async

- Backend/Dockerfile
Per this announcement, point to the new names for canonical `dotnet` Docker images: https://github.com/dotnet/dotnet-docker/issues/2375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/884)
> Use new canonical dotnet Docker image name

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend.Tests/Mocks/PermissionServiceMock.cs
- Backend/Controllers/AudioController.cs
- Backend/Controllers/AvatarController.cs
- Backend/Controllers/FrontierController.cs
- Backend/Controllers/LiftController.cs
- Backend/Controllers/ProjectController.cs
- Backend/Controllers/UserController.cs
- Backend/Controllers/UserEditController.cs
- Backend/Controllers/UserRoleController.cs
- Backend/Controllers/WordController.cs
- Backend/Interfaces/IPermissionService.cs
- Backend/Services/EmailService.cs
- Backend/Services/PermissionService.cs
- This reduces peak/persistent memory usage of downloading a 116MB Lift export by ~116MB.
Closes #811
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/878)
> Stream all file downloads

- dev-requirements.txt
Note that `pip-tools>=5.5.0` should be used to upgrade Python dependencies going forward as they changed the formatting of the output `*-requirements.txt` file. The diff noise lower if `pip-tools>=5.5.0` is used going forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/891)
> Update Python dependencies

- Backend.Tests/Mocks/PermissionServiceMock.cs
- Backend/Controllers/UserController.cs
- Backend/Controllers/UserEditController.cs
- Backend/Interfaces/IPermissionService.cs
- Backend/Services/LiftApiServices.cs
- Backend/Services/PermissionService.cs
- Backend/Services/UserApiServices.cs
- Backend/Services/UserEditApiServices.cs
- Backend/Services/WordApiServices.cs
Fixes part of #882.
Use `async` / `await` rather than `.Result` in all API methods to increase performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/893)
> Properly use async/await in all areas it can be used in backend

- src/components/GoalTimeline/GoalsActions.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
`loadGoalData()` blocks any use of words that are already in a suggested duplicate set, as it should. It also blocks words that were seen in a singleton set or a blacklist set, preventing them from being compared to other words. This pr removes those two restrictions.
The latter restriction was because `getNextDups()` has some sets that are strict subsets of previous sets. If you blacklisted a set, you shouldn't have to consider its subsets. To target that problem specifically, this pr updates the blacklisting function to blacklist not just a specified set but also its subsets.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/902)
> Cleanup loadGoalData and blacklist building.

- src/components/GoalTimeline/GoalsActions.tsx
- src/goals/CharInventoryCreation/CharacterInventoryActions.tsx
Twin pr to #922.
A follow-up pr is needed to work the bugs out of these goal-general functions and make sure they are generally useful.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/923)
> Move goal-general function from CharacterInventory to GoalActions.

- .prettierignore
Closes #932 
This shaves almost a minute off the time to run `npm run fmt-frontend`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/944)
> Ignore formatting large dictionary TS files to speed up formatting

- src/backend/localStorage.tsx
- src/backend/tests/localStorage.test.tsx
- src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
- src/components/Login/AuthHeaders.tsx
- src/components/Login/LoginActions.tsx
- src/components/Login/tests/AuthHeaders.test.tsx
- src/components/UserSettings/UserSettings.tsx
- src/goals/CharInventoryCreation/tests/CharacterInventoryActions.test.tsx
Closes #951 
Also:
- Update signature of `getCurrentUser()` to return `undefined` to match style guide
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/959)
> Fix allowing user to change email

- user_guide/docs/project.md
Users have reported thinking that exports have stalled when in fact they just take a long time to export. Specifically highlight long export times in the user guide.
Related #937
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/952)
> Highlight that export of large projects will take a long time

- Backend/Helper/Time.cs
- Backend/Models/Word.cs
- Backend/Services/LiftApiServices.cs
- Backend/Services/WordApiServices.cs
- Backend/Services/WordRepository.cs
Subtask of #960
- Use ISO 8601 date time format to allow for reliable round tripping of date times through database
- Set `Word.Modified` to creation time when `Word` is created
- Properly import `Creation` and `Modified` date times during Lift import
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/962)
> Fix Storage/Import of Word Creation and Modified Fields

- nginx/templates/default.conf.template
Update the nginx configuration templates to add the location for `/.well-known/acme-challenge` to the ssl server configuration.  This is required when an external service provides the redirection of http traffic to an https site.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/969)
> Add .well-known folder to ssl configuration

- Backend/Services/WordApiServices.cs
- Backend/Services/WordRepository.cs
Closes #960
- Update `Word.Modified` when
- Words are merged
- Words are deleted (e.g. removed from frontier)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/994)
> Update Word.Modified timestamp on merge or delete

- Backend/Startup.cs
Closes #992 
- No longer read `COMBINE_CORS_ORIGIN` env variable
- Increase security slightly by no longer setting any CORS headers if running within Docker/production
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/996)
> Remove CORS headers from production

- nginx/templates/default.conf.template
Enable Gzip compression on all common compressible response formats in NGINX.
This should increase page loading speeds, especially for users with slower network connection speeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/997)
> Enable Gzip compression in NGINX

- package.json
Currently if `npm run lint` is run and warnings are detected, the process does not fail. This means that when `npm run lint` is run on CI, it will not fail if ESLint warnings are pushed.
Fix this by failing if any warnings are detected by ESLint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/999)
> Cause npm run lint to fail if warnings are detected

- Backend.Tests/Controllers/UserEditControllerTests.cs
- Backend/Controllers/UserEditController.cs
- Backend/Interfaces/IUserEditService.cs
- Backend/Models/UserEdit.cs
- Backend/Services/UserEditApiServices.cs
- src/backend/index.tsx
- src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx
- src/components/GoalTimeline/GoalDisplay/HorizontalDisplay.tsx
- src/components/GoalTimeline/GoalDisplay/VerticalDisplay.tsx
- src/components/GoalTimeline/GoalTimelineComponent.tsx
- src/components/GoalTimeline/GoalsActions.tsx
- src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
- src/components/GoalTimeline/tests/GoalTimelineComponent.test.tsx
- src/goals/CreateCharInv/CreateCharInv.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
- src/goals/MergeDupGoal/MergeDupStep/index.tsx
- src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepActions.test.tsx
- src/types/goals.tsx
Backend:
* update functions that handle UserEdit goals and goal steps.
Frontend:
* update `backend.tsx` function correspondingly;
* make `GoalTimeline/GoalDisplay/` create new goals to avoid mutating suggestion list, disable buttons to completed goals;
* cleanup `GoalTimeline/GoalsActions.tsx`, especially goal loading and step advancing functions;
* in `MergeDupStepComponent.tsx`, don't refresh words (leave that to general goal actions), load filler text if nothing to merge (will need a proper page);
* in `types/goals.tsx`,  give empty first step by default, replace v1 (time-based) with v4 (random) to prevent duplicate hashes when goal history loaded
Closes #186 *
Closes #588 
Closes #990 
First 1.5 boxes of #931
Related to #393, #458 , #725 (*more needed to handle in-progress multi-step …
> Major goal- and step-loading refactor.

- src/types/project.tsx
- src/types/word.tsx
Several type definitions in the frontend are not up to date with the backend. This is causing some data to flow through the frontend and back to the backend without it being apparent in the frontend that this is happening (JSON fields are being passed around that are persisted, but not reflected in the types).
- Also reorder the definitions to match the backend to make it easier to verify in the future
This syncing problem is something that OpenAPI solves.
- https://www.openapis.org/
- https://github.com/OpenAPITools/openapi-generator
- #309 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1019)
> Fix frontend Word and Project data types to match the backend

- dev-requirements.in
- dev-requirements.txt
- Bump Python dependencies
- Remove unused `pytest` and `pytest-cov`. They were included accidently when using another Python project as an example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1038)
> Bump Python dependencies

- Backend.Tests/Mocks/WordRepositoryMock.cs
- Backend/Controllers/WordController.cs
- Backend/Interfaces/IWordRepository.cs
- Backend/Services/WordRepository.cs
- src/backend/index.tsx
- src/components/SiteSettings/SiteSettingsComponent.tsx
Closes #1014 
Backend function for filling empty guids, using the same guid for all words in the history of a frontier/deleted word.
Hacky frontend button in SiteSettings to trigger the backend.
This is an alternative to #1014
I think this requires `Word.Guid` to be nullable, or at least not automatically filled with a random `new Guid()`, so it must be used without #1013.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1037)
> Functions, button to fill all empty guids.

- Backend.Tests/Models/WordTests.cs
- Backend/Models/Word.cs
Previously, `Sense.Clone()` would not clone the `Accessibility`, instead it would also put `State.Active` on any clone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1045)
> Fix Sense.Clone() to clone Accessibility

- deploy/roles/combine_maintenance/files/add_user_to_proj.py
- deploy/roles/combine_maintenance/files/maint_utils.py
- deploy/roles/combine_maintenance/files/make_user_admin.py
- deploy/roles/combine_maintenance/files/rm_project.py
Improve the code quality of the maintenance scripts added with PR #1031.
- Use single exit code for failure
- Specify user permissions using an enumerated type
- Consistent quoting of string literals
- Improve help wording
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1041)
> Improve code quality for combine maintenance scripts

- Backend/Services/LiftApiServices.cs
Closes #1015 
`LiftSense` has a `.Guid` field. Document why The Combine imports the GUID for a `Sense` from from the `.Id` field rather than the `.Guid` field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1047)
> Document use of LiftSense.Id for GUID

- README.md
Use `python -m piptools ...` rather than `pip-compile` / `pip-sync` commands to ensure the correct Python virtual environment is in use.
`python -m ...` will always use `python` from the currently activated virtual environment.
This fixes an issue observed on macOS where `pip-tools` was installed globally and being used rather than the version in the current `venv`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1056)
> Fully qualify pip-tools command 

- Backend/Services/LiftApiServices.cs
Closes #1061 
Fix for issue exposed in #1054
`FinishEntry` is not expected to be `async` by parent class, so do not define as `async`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1064)
> Make FinishEntry sync to fix Lift import

- deploy/roles/docker_install/handlers/main.yml
- deploy/roles/docker_install/tasks/main.yml
The handlers for the `docker_install` role included a task to restart the `logrotate` service when the configuration to rotate the docker log files is created or modified.  This causes an error in Ubuntu 18.04 because `logrotate` is scheduled as a `cron` job instead of a `systemd` service.  In Ubuntu 20.04, it is ineffective since the `logrotate` service is a `oneshot` that is triggered by a `systemd` timer; restarting it is not necessary.
Note to reviewers: In addition to the issue above, the service name in the handler file is incorrectly named `rotatelog`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1070)
> Fix docker install handler

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend/Controllers/LiftController.cs
- Backend/Services/LiftApiServices.cs
Removing an unused part of our import process. If we decide to automatically extract `VernacularWritingSystem` for the project from the lift file in the future, we'll probably want something that is run once, not with every imported entry.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1065)
> Don't worry about project language when importing entries.

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend/Controllers/LiftController.cs
* Clear out the lift storage path directory before
trying to unzip files so that we don't have any
issues overwriting previous failed import attempts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1074)
> Recover from failed Lift import attempts

- Backend.Tests/Controllers/WordControllerTests.cs
- Backend.Tests/Mocks/WordRepositoryMock.cs
- Backend.Tests/Models/UserEditTests.cs
- Backend/Controllers/WordController.cs
- Backend/Interfaces/IWordRepository.cs
- Backend/Interfaces/IWordService.cs
- Backend/Models/Word.cs
- Backend/Services/LiftApiServices.cs
- Backend/Services/WordApiServices.cs
- Backend/Services/WordRepository.cs
- src/backend/index.tsx
- src/components/Login/LoginPage/LoginComponent.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
- src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepActions.test.tsx
- src/types/word.tsx
Rather than updating all remaining mergeWords after each is merged, prepare them all at once, then merge all, then delete all children from the frontier.
Resolves #1072
Resolves #1078
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1081)
> MergeDups refactor (all at once, rather than one-by-one)

- deploy/group_vars/nuc/main.yml
- deploy/host_vars/qa-thecombine.psonet.yml
- deploy/host_vars/thecombine.app.yml
- deploy/host_vars/thecombine.yml
- deploy/hosts.yml
Move host specific configuration items to the hosts.yml inventory file.  This is a step to enable easier configuration for other sites to run their own instance of _TheCombine_.
Also update NUC configuration items.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1082)
> Remove host_vars files

- deploy/roles/docker_install/tasks/main.yml
- deploy/roles/docker_install/templates/daemon.json.j2
Configure the docker engine to log using the syslog driver instead of the json driver.
This is residual work from #1055.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1088)
> Configure logging for docker engine

- src/components/AppBar/UserMenu.tsx
Resolves #957
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1096)
> Use forwardRef around UserMenuList to prevent console warning.

- README.md
Since moving to Docker/NGINX, we no longer run SSL outside of a reverse proxy directly from the backend. Remove an outdated reference to this from from the README.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1137)
> Remove reference to backend running on port 5001

- src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DragSense.tsx
When combining senses (dropping a sense on another, triggering the sidebar to open), we show all the glosses, but during the actual merge, only the first sense and its glosses are preserved. This pr implements visual indication that only the first of merged senses is kept in the merge process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1151)
> When merging senses, only show glosses from the keeper.

- deploy/bin/clean_repo.py
- deploy/roles/combine_maintenance/files/aws_backup.py
- deploy/roles/combine_maintenance/files/combine_app.py
- deploy/roles/combine_maintenance/tasks/main.yml
Addresses the following problems with the maintenance scripts for The Combine:
- PR #1114, Drop Python 3.6 Support, introduces type problems with calls to subprocess.run.
- Ansible role `combine_maintenance` does not install all the required Python modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1152)
> Fix maintenance scripts

- deploy/roles/docker_install/tasks/main.yml
Add a task to the `docker_install` role to explicitly enable the docker service (that is, start automatically) after docker has been installed.  This is required for _The Combine_ to start when the NUC is powered on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1156)
> Explicitly enable the docker service when docker is installed

- deploy/group_vars/nuc/main.yml
- deploy/playbook_target_setup.yml
- deploy/roles/ethernet_config/defaults/main.yaml
- deploy/roles/ethernet_config/handlers/main.yaml
- deploy/roles/ethernet_config/tasks/main.yml
Update the default network configuration to specify that the Ethernet connection on the NUC is optional.  In the normal use of the NUC, the Ethernet cable is not connected and the NUC waits for the connection during startup.  With this change, the time from power on until The Combine is ready goes from 3 minutes to 30 seconds.
Note that this implementation iterates over all network connection configuration files and updates all ethernet connections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1162)
> Set ethernet as optional on NUCs

- docs/user_guide/mkdocs.yml
By default, [Material for MkDocs pulls fonts dynamically from the internet](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#disabling-font-loading). To make the user experience better on offline networks, disable this feature and use built in system fonts instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1170)
> Disable pulling fonts from the Internet in the user guide

- docs/style_guide/ts_style_guide.md
- package-lock.json
- package.json
- src/components/Buttons/EditTextDialog.tsx
- src/components/DataEntry/DataEntryHeader/DataEntryHeader.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
- src/components/TreeView/TreeViewHeader.tsx
- src/components/TreeView/tests/TreeViewHeader.test.tsx
Use `ts-key-enum` to improve the compile-time checking of comparisons of `KeyboardEvent`s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1179)
> Use ts-key-enum to improve type safety of comparisons of KeyboardEvents

- Dockerfile
- nginx/templates/default.conf.template
Enable HTTP/2 support in NGINX. This should increase page loading performance, especially for mobile users and users running with high latency (e.g. a user in France running against the Combine within the U.S.).
Also update NGINX to the latest version (1.21).
HTTP/2 works by using a binary format that is more efficient to transmit as well as using a single TCP/TLS connection for multiple requests. This reduces round trip times to set up TCP + TLS connections. We already enabled TLS 1.3 in #779, which eliminated reduced 1 round trip time. Using HTTP/2 will further increase network performance of remote users.
HTTP/2 was released in 2015 and all major browsers support it: https://caniuse.com/http2. Somewhere around 60% of websites use HTTP/2 currently.
Because NGINX proxies connections to …
> Enable HTTP/2 support in production NGINX configuration

- src/components/Login/Redux/LoginActions.ts
- src/components/ProjectInvite/index.ts
Fixes #1218 
Applying what #1187 did to `asyncRegister` to `asyncRegisterForEmailInvite` nullifies the subtle distinction between the two functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1219)
> Retire asyncRegisterForEmailInvite

- Backend/BackendFramework.csproj
- Backend/Controllers/UserController.cs
Closes #1214 
This is a follow on of the work that has proceeded to eliminate remaining usages of deprecated ASP.NET 2.2 features from the code base.
- #1198 
- #1215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1220)
> Remove dependency on deprecated WebApiCompatShim

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
Closes #1160
This PR adds two new Gitlab Actions CI jobs. One builds the backend docker image and one builds the frontend docker image. Note these are purely done for testing purposes: to ensure that a PR did not make changes that broke the production Docker image builds. These CI jobs are not intended for any kind of automatic Docker push/deployment, though that could be done in the future if desired.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1216)
> Add Docker build GitHub Actions Jobs

- README.md
Correct README.md to specify the correct directory for the maintenance scripts, `/opt/combine/bin`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1229)
> Fix readme path

- dev-requirements.in
- dev-requirements.txt
- tox.ini
Unpin `isort` now that upstream https://github.com/PyCQA/isort/issues/1762 has been resolved.
Also use `--check` alias in `tox` config so that `isort` CLI matches similar `black` CLI arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1243)
> Unpin isort

- deploy/roles/combine_maintenance/tasks/main.yml
The maintenance script, `set_proj_owner.py` was approved with PR #1259.  This PR updates the Ansible playbooks to install the script on target machines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1262)
> Install set_proj_owner.py script on target

- deploy/roles/docker_install/defaults/main.yml
- deploy/roles/docker_install/handlers/main.yml
- deploy/roles/docker_install/tasks/main.yml
Pin Ubuntu Docker packages to version 5.20.10.*;  Kubernetes has now been validated with Docker 20.10. (see [Container Runtimes | Kubernetes](https://kubernetes.io/docs/setup/production-environment/container-runtimes/)
Closes #1256.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1263)
> Docker 20.10

- .vscode/settings.json
In a new .cs file, this sets the default to tab = 4 spaces.
When editing an existing .cs file, the existing indentation will override this, unless we also set `"editor.detectIndentation": false`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1264)
> Fix vscode default tab setting to 4 spaces for cs.

- dev-requirements.txt
- docs/user_guide/mkdocs.yml
Material for MkDocs 7.2 released with the following new useful search features. Enable them for the user guide:
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1283)
> Enable Material for MkDocs 7.2 search features

- package-lock.json
- package.json
- src/components/GoalTimeline/Redux/GoalActions.ts
- src/components/ProjectExport/DownloadButton.tsx
- src/goals/CharInventoryCreation/components/CharacterList/CharacterStatusText.tsx
- Enable exhaustiveness checks for `switch` statements in the frontend. (https://stackoverflow.com/a/60166264/)
- Downgrade to TypeScript `4.2.4` to support `@typescript-eslint/parser` which doesn't support TypeScript 4.3.x in the version we have pinned
- https://github.com/typescript-eslint/typescript-eslint/issues/3272
- `npm` is pinning `@typescript-eslint/parser` at `4.21` (4 months old) rather than `4.29`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1298)
> Enable ESLint exhaustive switch linting

- Backend.Tests/Helper/SanitizationTests.cs
- Backend.Tests/Helper/TimeTests.cs
- Backend.Tests/Models/EmailInviteTests.cs
- Backend.Tests/Models/ProjectTests.cs
- Backend.Tests/Models/UserEditTests.cs
- Backend.Tests/Models/UserTests.cs
- Backend.Tests/Models/WordTests.cs
- Backend/Models/EmailInvite.cs
- Backend/Models/Project.cs
Add unit test coverage for:
-  `User` `Model`
- `Project` `CustomField`
- `Project` `InviteTokens`
- Remove unused `UserCreatedProject.Clone()`
- Unicode punctuation for `Sanitization.MakeFriendlyForPath()`
- `Helper.Time`
- `Helper.Sanitization`
Follow on to #1271
After this PR, all `Model`s have 100% test coverage as are `Helper.Time` and `Helper.Sanitization`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1307)
> Increase backend unit test coverage

- .github/workflows/frontend.yml
https://medium.com/the-node-js-collection/node-js-16-available-now-7f5099a97e70
> As per the release schedule, Node.js 16 will be the ‘Current’ release for the next 6 months and then promoted to Long-term Support (LTS) in October 2021
https://endoflife.date/nodejs
- Node 12 has already ended active support, and it's security support ends in 8 months
Some of our `npm` scripts already fail under Node 12 (for example license report generation).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1320)
> Drop Node 12 support, add Node 16

- Backend/Controllers/AudioController.cs
Previously, we were testing `if file is null`, but the compiler enforces that it cannot be `null`. In fact, the way `OpenRead` signals that the file does not exist is to throw an `Exception`.
This change will properly return a `BadRequest` in the event the file has been deleted or moved rather than allowing an uncaught exception to bubble into a 500 server error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1357)
> Fix handling case if audio file is missing

- Backend/Controllers/AudioController.cs
- Backend/Controllers/AvatarController.cs
- Backend/Controllers/InviteController.cs
- Backend/Controllers/LiftController.cs
- Backend/Controllers/MergeController.cs
- Backend/Controllers/ProjectController.cs
- Backend/Controllers/UserController.cs
- Backend/Controllers/UserEditController.cs
- Backend/Controllers/UserRoleController.cs
- Backend/Controllers/WordController.cs
- Backend/Startup.cs
The call in `Startup.Configure` to `app.UseCors(LocalhostCorsPolicy);` should apply CORS headers to all requests.
Remove duplicated `EnableCors[]` attributes to `Controller`s, which should not be needed.
CORS is only needed for local development outside of Docker, so that is the context that should be tested for this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1356)
> Remove duplicated CORS attributes from Controllers

- .github/workflows/frontend.yml
Using the downgrading suggested in https://github.com/nodejs/node/issues/40030
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1369)
> Pin Node to 16.8 to avoid 16.9 bug.

- docs/deploy/README.md
Add instructions for installing Helm to docs/deploy/README.md.
Helm should be installed on the client machine rather than the target since the Ansible installation and configuration playbooks for The Combine will not have `ssh` access to the Production and QA Kubernetes clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1375)
> Add instructions for installing Helm

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend.Tests/Helper/TimeTests.cs
- Backend/Controllers/LiftController.cs
- Backend/Helper/CombineHub.cs
- Backend/Helper/FileStorage.cs
- Backend/Helper/Time.cs
- Backend/Services/LiftService.cs
- src/components/App/SignalRHub.tsx
- src/components/ProjectExport/DownloadButton.tsx
- src/components/ProjectExport/ExportButton.tsx
- src/components/ProjectExport/Redux/ExportProjectActions.ts
- src/components/ProjectExport/Redux/ExportProjectReducer.ts
- src/components/ProjectExport/Redux/ExportProjectReduxTypes.ts
- src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx
- src/components/ProjectSettings/ProjectUsers/UserList.tsx
- src/resources/translations.json
Fixes #1379 
Bypasses #937 by not requiring the user to press a button when the export is ready to download.
Also, uses random temp export folders to prevent concurrency issues when there are multiple simultaneous attempts to export the same project.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1376)
> Spawn new Thread for the export [backend], auto-download when export done [frontend]

- Backend/Controllers/LiftController.cs
Improve error messages when malformed Lift files are imported.
When #1388 is merged, these will be displayed to the users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1394)
> Improve lift import error messages

- README.md
This usage also matches the macOS instructions
For reference, see: https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1470)
> Document the canonical way to activate a Python virtual environment

- deploy/roles/k8s_config/templates/deployment-maintenance.yaml.j2
- maintenance/scripts/combine_restore.py
When asking the user to choose the backup to restore, the `combine_restore.py` script did not display all available backups.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1482)
> Fix kubernetes restore

- deploy/group_vars/qa/main.yml
- deploy/group_vars/server/main.yml
- deploy/hosts.yml
- docs/deploy/README.md
Update deployment scripts and documentation for running _The Combine_ in a Kubernetes cluster.  Dropping documentation of `docker-compose` deployment.
Closes #1457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1483)
> Switch to kubernetes deployment

- Backend/Controllers/ProjectController.cs
- Backend/Models/UserRole.cs
- Backend/Services/InviteService.cs
- README.md
- deploy/roles/combine_maintenance/files/add_user_to_proj.py
- deploy/roles/combine_maintenance/files/combine_app.py
- maintenance/scripts/combine_app.py
- src/api/models/permission.ts
- src/components/ProjectSettings/ProjectUsers/AddProjectUsers.tsx
- src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx
Closes #1485 
@jmgrady When this is released, we will need to run a one-time database migration script on the live server to remove all `2` Permission objects from all Users. This will allow this value can be reused safely in the future if needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1491)
> Remove Unused Permission enumeration member

- deploy/roles/combine_config/templates/env.backend.j2
- deploy/roles/combine_config/templates/env.certmgr.j2
- deploy/roles/combine_config/templates/env.frontend.j2
Update the templates for `.env.frontend`, `,env.backend`, and `.env.certmgr` to enclose most string environment variables in double-quotes - when running under `zsh` on a Mac, the missing quotes were a problem.  This solution has been tested on Windows, Ubuntu (`bash`), and Mac (`zsh`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1512)
> Quote string environment variables in docker-compose .env files

- .github/workflows/backend.yml
- Backend.Tests/Backend.Tests.csproj
- Backend.Tests/Controllers/AudioControllerTests.cs
- Backend.Tests/Controllers/AvatarControllerTests.cs
- Backend.Tests/Controllers/BannerControllerTests.cs
- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend.Tests/Controllers/ProjectControllerTests.cs
- Backend.Tests/Controllers/UserControllerTests.cs
- Backend.Tests/Controllers/UserEditControllerTests.cs
- Backend.Tests/Controllers/UserRoleControllerTests.cs
- Backend.Tests/Controllers/WordControllerTests.cs
- Backend/BackendFramework.csproj
- Backend/Dockerfile
- Backend/Helper/PasswordHash.cs
- Backend/Models/EmailInvite.cs
- Backend/Models/PasswordReset.cs
- Backend/Properties/launchSettings.json
- Backend/Services/LiftService.cs
- README.md
- package.json
Closes #1172
- Upgrade to .NET 6
- Upgrade to C# 10
- Enable Backend hot reload
- Remove obsolete `RNGCryptoServiceProvider`
- In unit test code, use `!` to suppress more aggressive null checks when casting to `ObjectResult` from API endpoints under test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1509)
> Upgrade to .NET 6

- Backend/Startup.cs
- README.md
- docs/style_guide/c_sharp_style_guide.md
- Correct C# style guide to follow the standard C# brace and indentation style.
- Remove all .NET version-specific query args from hyperlinks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1513)
> Correct brace style in C# style guide

- package-lock.json
- package.json
- src/components/App/App.test.tsx
- src/components/Login/LoginPage/tests/LoginComponent.test.tsx
- src/components/Login/RegisterPage/tests/RegisterComponent.test.tsx
- src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/CharacterReplaceDialog.tsx
Modernize ESLint settings for what a new React project using ESlint would like like today.
As a reference, see: https://khalilstemmler.com/blogs/typescript/eslint-for-typescript/
This PR does several things:
- Decouples our React-ESlint settings from create-react-app allowing us to control and bump the versions independently
- Enables additional React linting that wasn't on before (such as JSX linting)
- Fix some unquoted literals that the new lints warn about
- https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md
- Defers #1519 to a future PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1518)
> Modernize ESLint React/TypeScript configuration

- Dockerfile
- tox.ini
Set Python 3.9 as the default version to build the user guide, type check, etc.
This follows the policy of selecting the second from newest Python version for production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1522)
> Use Python 3.9 to build the user guide

- src/types/goals.ts
Reverting one small bit of #1523 that was causing null entries in the UserEdits database, making all future goals impossible for the given project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1527)
> Revert to using {} instead of undefined for empty goal edit steps

- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
Closes #608
In the case that the user ESCapes out of the dialogs, the focus returns to the vernacular field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1536)
> Focus on gloss after closing dialogs

- .editorconfig
Since we use a different indent size for C# vs TS, set this explicitly within `.editorconfig` so that developers opening the project for the first time will have their editors/IDEs auto-configured properly.
These values match the defaults for `dotnet-format` and Prettier, respectively.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1551)
> Set indent_size within editorconfig

- .editorconfig
- pyproject.toml
Follow on to #1551
Set this to the value used by `black` in `pyprojec.toml`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1558)
> Set Python max line length in .editorconfig

- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/tests/GlossWithSuggestions.test.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/tests/VernWithSuggestions.test.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/tests/NewEntry.test.tsx
- src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx
Specifically:
* While a recent entry is updating, temporarily disable it instead of making it disappear (Resolves: #1466)
* After an entry is updated, remove its old id from the `defunctWordIds` array (used to determine if an entry is updating)
Also:
* Move handling of `allVerns` inside `NewEntry`, since it isn't used in any other part of `DataEntryTable`.
The first item above improves the ux.
The second and third items above appear to improve performance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1560)
> [DataEntryTable] Improve updating of recent entries

- deploy/scripts/setup_combine.py
- maintenance/scripts/combine_app.py
- maintenance/scripts/combine_backup.py
- maintenance/scripts/maint_utils.py
_TheCombine_ backup process broke with the delivery of PR #1561.
The cause of the problem was that literal strings for the different combine components, frontend, backend, etc., were replaced by an enumerated type in the Python scripts in the `maintenance` container.  One case was missed where the name of the enum was used instead of the `value`.
In addition, this PR makes the following improvements:
- Fix case of variable in `setup_combine.py` being read before it was initialized;
- Replaced additional instances of literal strings with the component enums; and
- Improved exception handling for `subprocess.CalledProcessError` - adds the command that failed to the error report.
--- …
> Fix backup scripts

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- Backend.Tests/Backend.Tests.csproj
Closes #1600
Closes #1603 
-  #1576 removed `coverlet.msbuild` extension which is needed for coverage file generation. This PR adds it back in.
- The CI will now fail if coverage fails to upload, which will catch errors like this in the future
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1601)
> Migrate to version 2 of CodeCov GitHub Action

- .github/actions/combine-deploy-update/action.yml
The container name for the `deployment/cert-proxy-server` should be `cert-proxy-server`, not `maintenance`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1607)
> Fix deployment name for cert proxy server

- Backend.Tests/Models/WordTests.cs
- Backend.Tests/Services/WordServiceTests.cs
- Backend/Models/Word.cs
- Backend/Services/WordService.cs
- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
The "Note" part of #1584
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1615)
> [NewEntry] If duplicate, add note to existing

- docs/deploy/README.md
- docs/deploy/kubernetes_design/README.md
- docs/user_guide/docs/account.md
- src/components/LandingPage/BottomBar.tsx
- src/components/LandingPage/LandingButtons.tsx
- src/components/LandingPage/TopBar.tsx
- src/components/LandingPage/index.tsx
- src/components/Login/LoginPage/LoginComponent.tsx
- src/resources/translations.json
Resolves #1604, step 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1616)
> [LangingPage] Add  paragraph with call-to-action, sign-up button

- deploy/helm/thecombine/charts/maintenance/templates/cronjob-daily-backup.yaml
- deploy/helm/thecombine/values.yaml
- deploy/scripts/setup_files/combine_config.yaml
Currently the helm chart for the combine is set to configure a cron job to run a backup at 03:15 UTC every day.  Change the default to not create regular backups and override this for the production environment only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1621)
> Disable backups by default for all but production installations

- README.md
We no longer support having the backend host HTTPS directly (NGINX or Kubernetes does this), so simplify initial setup instructions for developers by removing references to this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1623)
> Remove unused HTTPS certificate instructions from README

- deploy/helm/cert-proxy-server/templates/env-nginx-configmap.yaml
- deploy/helm/cert-proxy-server/templates/ingress-nuc.yaml
- deploy/helm/cert-proxy-server/templates/init-nginx-pages.yaml
- deploy/helm/cert-proxy-server/values.yaml
- deploy/scripts/setup_combine.py
- deploy/scripts/setup_files/combine_config.yaml
- deploy/scripts/setup_files/profiles/dev.yaml
- deploy/scripts/setup_files/profiles/nuc.yaml
- deploy/scripts/setup_files/profiles/prod.yaml
Address a set of small problems which prevent the cert proxy server from deploying properly:
- the global definition of `serverName` was used for both the application frontend and the combine-cert-proxy server.  This was addressed 2 ways:
- changed the structure of the `overrides` in the configuration file to have separate override YAML for each chart, i.e.
```
overrides:
chart_name:
override_variable_1: some_value
...
```
- created a separate variable, `certProxyServerName`, for the combine-cert-proxy.  This variable is not in the `global` section because it does not need to be shared with subcharts
- The ingress template created an ingress resources for each of the nucs.  The template was missing the `---` document separator so a single resource was created with many duplicate fields.
- …
> Fix Helm deployment of the certificate proxy server

- deploy/helm/cert-proxy-server/templates/ingress-nuc.yaml
- deploy/scripts/setup_files/profiles/prod.yaml
An error was introduced when porting the Kubernetes installation from Ansible to Helm. The variable .Values.combineCertProxyList is used in two ways:
- iterate over the servers in the list to create an ingress for each server, and
- create an environment variable for the combine-cert-proxy deployment. The deployment monitors watches for changes to secrets, if the secret is for a server in the environment variable, then the secret is pushed to AWS S3.
For the first use, the variable must be a list. In the second use, when the environment variable is set from a list, it has brackets ( [ ] ) around the list which prevents the deployment from detecting any changes.
--- …
> Fix setting of server list for the cert proxy server

- deploy/helm/thecombine/charts/frontend/templates/deployment-frontend.yaml
- deploy/helm/thecombine/templates/ingress-combine.yaml
- deploy/helm/thecombine/values.yaml
- deploy/scripts/setup_files/profiles/nuc.yaml
- deploy/scripts/setup_files/profiles/prod.yaml
- deploy/scripts/setup_files/profiles/staging.yaml
- nginx/init/25-combine-runtime-config.sh
This PR addresses the following issues with the Helm charts for _The Combine_:
- Update the default S3 bucket for the NUCs to be `prod.thecombine.app`
- Fix the generation of `config.js` on the frontend; the script to build `config.js` from environment variables did not work correctly if there were spaces in the value of the environment variable
- The analytics write key was missing from the environment variables for the frontend.  The value was being put into the configuration map, `env-frontend` but the definition of the frontend deployment never created the environment variable in the pod container.  In addition, the analytics write key for the QA server is now specified.
- Added option to specify the name of the secret for _The Combine's_ TLS certificate since the QA server's resource …
> Update helm charts

- scripts/clean_aws_repo.py
When `clean_aws_repo.py` is run manually, it is helpful to know what tags are available when creating the patterns for removing old images.  This adds a `--list` option to just list the tags and untagged images without removing any images from the specified repo(s).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1654)
> Add ability to list images in the repo(s)

- maintenance/scripts/combine-clean-aws.sh
When the installation of The Combine in the Kubernetes cluster moved from Ansible playbooks to a Helm chart, the way the AWS bucket is specified was changed but the script to clean up old backups was not updated.  In the Helm chart, the `aws_bucket` environment variable starts with `s3://`.
This PR updates the `combine-clean-aws.sh` scripts to work whether or not the `aws_bucket` environment variable begins with the AWS S3 URL prefix.
Closes #1657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1658)
> Allow $aws_backup with and without 's3://' at beginning

- .github/actions/combine-deploy-update/action.yml
- .github/workflows/backend.yml
- .github/workflows/python.yml
- Backend/Dockerfile
Update the GitHub Actions as follows:
- Pin `dotnet/sdk` to `6.0.202` where referenced.  This applies to the GitHub Actions as well as the file `./Backend/Dockerfile`
- Remove lint/type checking of python code against Python 3.8.  All containers are using 3.10.  The user guide continues to be built using 3.9.
- Change to the home directory as the first step for the self-hosted runner when deploying to the production or QA server so that we are working from a known spot.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1661)
> Update gh actions

- .github/workflows/deploy_release.yml
- deploy/scripts/setup_combine.py
This PR includes two updates to the release scripts:
1. the GitHub action to deploy a release was updated to update the production server as well as the QA server;
2. the `setup_combine.py` script was updated to use the `--tag` value for the version of the helm charts unless the value is `latest`; if the value is `latest` it will use the results from `get_release()` in `app_release.py`.  There are two reasons for this change:
1. to have the chart version match the version of the software that is installed rather than the version of the git repository where the script was run; and
2. to be able to install the helm charts without having the full git repository present, for example, from a Docker image that includes the scripts.
---
This change is [<img …
> Update release scripts

- deploy/Dockerfile
- deploy/docker_home/.bashrc
- deploy/docker_home/restore_config.sh
- deploy/docker_home/save_config.sh
- deploy/scripts/check_certs.py
- deploy/scripts/setup_target.py
- deploy/scripts/utils.py
This PR includes the following enhancements to the `combine_deploy` image that can be used to setup _The Combine_ on a NUC:
- Adds scripts to store/restore setup information to a volume when mounted as `/config`; the information saved is:
- /etc/hosts
- $HOME/.ssh
- $HOME/.kube
This obviates the need to re-run the `setup_target.py` script and the Ansible playbook each time the image is run.
- Adds a `check_cert.py` to print the expiration time of any TLS certificates installed on the target.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1694)
> Combine deploy enhancements

- dev-requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1697)
> Upgrade Python deps

- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
Resolves #1711 by preventing Safari's default of triggering the Exit button when the "return" key is pressed within a TextField. This solution does not identify the root of that wonky behavior, but does avoid it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1712)
> [DataEntryTable] Use preventDefault in TextField

- .github/actions/combine-deploy-update/action.yml
Missing `${{ inputs.image_registry_alias }}` when updating the `combine-cert-proxy` deployment results in an invalid image name being specified for the deployment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1716)
> Add missing public registry alias to update of combine-cert-proxy

- deploy/scripts/sem_dom_import.py
- deploy/scripts/semantic_domains.py
Add an option to the `sem_dom_import.py` script to specify whether the questions section of each semantic domain should be full or flat (default).  As an example:
- Full:
```
"questions": [
{
"question": "(1) What words are used to refer to the sky?",
"example_words": "sky, firmament, canopy, vault",
"example_sentences": ""
},
{
"question": "(2) What words refer to the air around the earth?",
"example_words": "air, atmosphere, airspace, stratosphere, ozone layer",
"example_sentences": ""
},
...
```
- Flat:
```
"questions": [
"(1) What words are used to refer to the sky?",
"(2) What words refer to the air around the earth?",
...
```
- - - …
> Add option for full question structure or flattened questions

- deploy/scripts/semantic_domains.py
Change the script that generates the import data for the SemanticDomainTree collection in the database so that missing parent, next, or previous nodes are set to `null` instead of `{}`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1731)
> Set empty nodes to null instead of empty object, {}

- deploy/ansible/group_vars/nuc/main.yml
- deploy/ansible/group_vars/server/main.yml
- deploy/ansible/playbook_kube_install.yaml
- deploy/ansible/roles/monitor_hardware/defaults/main.yml
- deploy/ansible/roles/monitor_hardware/handlers/main.yml
- deploy/ansible/roles/monitor_hardware/tasks/main.yml
- deploy/requirements.txt
- deploy/scripts/build.py
- maintenance/requirements.txt
Add a role the Ansible scripts that add hardware monitoring, specifically, Temperature, to the setup of the NUC devices.
The monitoring values are not displayed in _The Combine_ User Interface.  They are added to aid diagnosis of problems in the field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1745)
> Add Hardware Monitoring to NUC installations

- database/init/update-semantic-domains.sh
- maintenance/scripts/db_update_sem_dom_in_senses.py
Update database migration script for updating `SemanticDomains` field of the `senses` in the `FrontierCollection` and the `WordsCollection`.
- Adds `_id` field for the MongoDB ObjectId for the document in the `SemanticDomains` collection.  If the semantic domain id and name do not match any of the domains in the collection, `null` is used;
- Changes the `guid` field from a `UUID` type to `str` type to match the `SemanticDomains` collection and the data model.
- Reverts the change to the script to update the `SemanticDomains` collection to use the `merge` mode instead of `upsert` so that only changed documents are updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombi …
> Update migration script

- deploy/ansible/roles/docker_install/tasks/main.yml
The Ansible module, `apt_key` and the `apt-key` keyring management system are deprecated.  These changes update the installation of `docker` to use the method recommended in the DEPRECATION section of the `apt-key(8)` man page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1754)
> update installation of apt key for docker

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1757)
> Add documentation of CI/CD processes to README.md

- README.md
Fix the badge for the CodeQL code scanning results and add badge for the OSSF Scorecard results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1773)
> Update readme badges for CodeQL and OSSF Scorecard

- Backend/Repositories/SemanticDomainRepository.cs
- src/components/TreeView/TreeSearch.tsx
“Find a domain” search field at top of the domain tree should not be case-sensitive.
Add method to convert input string, then passing correct format string into the searching method
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1814)
> Fix case-sensitive of Find a domain

- .github/workflows/backend.yml
- .github/workflows/codeql.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
- .github/workflows/frontend.yml
- .github/workflows/maintenance.yml
- .github/workflows/python.yml
- .github/workflows/scorecards.yml
Update the GitHub actions for _The Combine_ update the `step-security/harden-runner` actions as follows:
- change the `egress-policy` from `audit` to `block`;
- set `disable-sudo` to `true`;
- add the `allowed-endpoints` recommended by the StepSecurity audit runs;
- remove the `step-security/harden-runner` step for actions run on a self-hosted runner (self-hosted runners are not supported by `harden-runner`)
Note:
- The `harden-runner` action logs the following error during the _Post Harden Runner_ phase:
```
Error: StepSecurity Harden Runner: Overwrite detected for /etc/systemd/resolved.conf
```
This is a known issue.  It does not cause the step to fail and can be ignored.  See the discussion in [step-security/harden-runner](https://github.com/step-security/harden-runner/discussions/230) …
> Change Harden Runner actions from audit to block

- Backend.Tests/Services/MergeServiceTests.cs
- Backend.Tests/Util.cs
- Backend/Services/MergeService.cs
Resolves #1818 
Without these changes to `Backend/Services/MergeServices.cs`, the backend test consistently fails when `wordCount=10000`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1819)
> Refactor asyncronous handling of merge list

- Backend/Dockerfile
When pinning the `aspnet-core` image to a specific commit, the sha256 sum that was used to build the Backend was incorrect.  It was the sha256 sum for `aspnet-core:7` instead of `aspnet-core:6`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1828)
> Fix sha256 sum for aspnet-core image

- package-lock.json
- package.json
Updating the `axios` npm package to 1.x.x breaks the audio recording functionality.  When attempting to upload an audio recording, a _400-Bad Request_ error is returned.  It says it is a null file.
This PR rolls back the version of the `axios` package to the latest working version.
Issue #1930 created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1931)
> Rollback axios package to 0.27.2

- src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
While clicking the delete icon when entering words 
Frontend’s word ID did not match the FrontierCollection 
Fix by removing the Incorrect update
The problem is When updateWord API called both word's in the  FrontierCollection and WordsCollection are updated, However, the frontend copy is NOT updated. So that when the delete icon is clicked deleteWord API is not able to find the word by the wrong _id. 
The updateWord API is Not necessary at this point
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1943)
> Fix the delete icon causing the backend not found

- .github/dependabot.yml
- .github/workflows/backend.yml
- .github/workflows/codeql.yml
- .github/workflows/combine_deploy_image.yml
- .github/workflows/database.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
- .github/workflows/frontend.yml
- .github/workflows/maintenance.yml
- .github/workflows/pages.yml
- .github/workflows/python.yml
- .github/workflows/scorecards.yml
- Backend.Tests/Backend.Tests.csproj
- Dockerfile
- docs/user_guide/docs/licenses/backend_licenses.txt
- docs/user_guide/docs/licenses/frontend_licenses.txt
- package-lock.json
- package.json
Update the schedule for `dependabot` dependency checks to run weekly on Sundays.
In addition, 
- update the outstanding dependency changes highlighted by `dependabot`, and
- update the `Dockerfile` that is used to build the frontend image to install required libraries using `npm ci` instead of `npm install`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1959)
> Dependabot schedule config; use `npm ci` for docker builds; dependency updates

- .github/workflows/backend.yml
- .github/workflows/codeql.yml
- .github/workflows/combine_deploy_image.yml
- .github/workflows/database.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
- .github/workflows/frontend.yml
- .github/workflows/maintenance.yml
- .github/workflows/pages.yml
- .github/workflows/python.yml
- .github/workflows/scorecards.yml
- Backend/BackendFramework.csproj
- docs/user_guide/docs/licenses/backend_licenses.txt
- docs/user_guide/docs/licenses/frontend_licenses.txt
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2011)
> Dependabot updates for week of 10 Apr 2023

- .gitignore
- docs/user_guide/docs/licenses/frontend_licenses.txt
- package-lock.json
- package.json
PR #2001 updated axios to 1.3.4 as part of the `dependabot` updates without verifying that the change addresses issue #1930.
This PR rolls axios back to a working version.
An additional unrelated change is include to add `public/scripts/config.js` to `.gitignore` so that custom runtime configurations can be tested with development builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2022)
> Revert axios to 0.27.2

- src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DropWord.tsx
- src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx
- src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
Resolves #2097
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2104)
> [MergeDups] Fix column overflow & flag bug

- .editorconfig
- Backend.Tests/Backend.Tests.csproj
- Backend.Tests/Controllers/AudioControllerTests.cs
- Backend.Tests/Controllers/BannerControllerTests.cs
- Backend.Tests/Helper/TimeTests.cs
- Backend.Tests/Mocks/PermissionServiceMock.cs
- Backend.Tests/Services/MergeServiceTests.cs
- Backend/BackendFramework.csproj
- Backend/Controllers/LiftController.cs
- Backend/Interfaces/IEmailService.cs
- Backend/Interfaces/IMergeBlacklistRepository.cs
- Backend/Interfaces/IWordRepository.cs
- Backend/Services/InviteService.cs
- Backend/Services/LiftService.cs
- Backend/Services/MergeService.cs
- Backend/Services/PermissionService.cs
- Backend/Services/StatisticsService.cs
- Backend/Startup.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2106)
> Tighten backend linting

- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
Update the GitHub action to build the QA images to allow pulling of images from microsoft.com.
In addition, initial `allowed-endpoints` are specified for building releases for the production server.  `egress-policy` is left at `audit` until the results of this change can be reviewed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2195)
> Fix build for QA deployment

- .github/workflows/backend.yml
- .github/workflows/codeql.yml
- .github/workflows/combine_deploy_image.yml
- .github/workflows/database.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
- .github/workflows/frontend.yml
- .github/workflows/maintenance.yml
- .github/workflows/pages.yml
- .github/workflows/python.yml
- .github/workflows/scorecards.yml
- Backend.Tests/Backend.Tests.csproj
- Backend/BackendFramework.csproj
- Dockerfile
- docs/user_guide/docs/licenses/backend_licenses.txt
- docs/user_guide/docs/licenses/frontend_licenses.txt
- package-lock.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2270)
> Dependabot updates for week of 12 June 2023

- README.md
Update the instructions for setting up _The Combine_ on a local Kubernetes cluster in `README.md`.  Specifically:
1. Changed the URL for _The Combine_ from `https://thecombine.local` to `https://thecombine.localhost`.  This URL change was made sometime ago since Google Chrome, Chromium Derivatives, and Firefox automatically map `*.localhost` to 127.0.0.1.
2. Removed instructions for updating the host machine's host configuration file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2271)
> Update URL and host config for local kubernetes cluster

- src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx
Fixes the following (introduced in #2306):
In `CreateProject`, after loading a LIFT file, when selecting a vernacular language from the drop-down menu, the console gives this:
```
react_devtools_backend_compact.js:2367
Warning: A component is changing an uncontrolled input to be controlled.
This is likely caused by the value changing from undefined to a defined value, which should not happen.
Decide between using a controlled or uncontrolled input element for the lifetime of the component.
More info: https://reactjs.org/link/controlled-components
at input
at http://localhost:3000/static/js/bundle.js:20558:66
at SelectInput (http://localhost:3000/static/js/bundle.js:37716:27)
at http://localhost:3000/static/js/bundle.js:20558:66
at div
at http://localhost:3000/static/js/bundle.js:20558:66 …
```
> Fix console warning re undefined option

- .vscode/settings.json
- Backend.Tests/Helper/LanguageTests.cs
- Backend.Tests/Models/ProjectTests.cs
- Backend.Tests/Util.cs
- Backend/Controllers/LiftController.cs
- Backend/Helper/GrammaticalCategory.cs
- Backend/Helper/Language.cs
- Backend/Helper/LiftHelper.cs
- Backend/Models/Project.cs
- Backend/Services/LiftService.cs
Resolves #2340
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2349)
> Sort writing systems retrieved from import LDMLs

- Backend/Models/Project.cs
Its absence prevented Serialization in some scenarios.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2353)
> [Backend/Models] WritingSystem: restore parameterless constructor

- .vscode/settings.json
This adds a warning when committing through VSCode's "Source Control" panel (not when committing via a cli opened in VSCode).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2450)
> Configure VSCode to warn on commits to master, main

- .github/actions/combine-deploy-update/action.yml
The CD script to deploy to the QA and Production servers was failing because the `kubectl` command used to log the Kubernetes versions was using a deprecated option that has now been removed.  The PR makes the following changes to address this issue:
- instead of downloading the latest version of `kubectl`, it now downloads a specific version.  This also helps to avoid warnings that "version difference between client and server exceeds the supported minor version skew of +/-1".  The `kubectl` version is specified as a repository variable in the GitHub project settings.
- changes the output format from `--short` to `yaml`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombi …
> Specify kubectl version as GHA variable

- .github/actions/combine-deploy-update/action.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
In order to fix the last attempt to specify the `kubectl` version through a GitHub Actions variable, the following changes are proposed:
- add an input value to `.github/actions/combine-deploy-update/action.yml`.  Since the action is run as a `composite` on our self-hosted runner, it GitHub Action variables are not accessible and need to be passed in as inputs.
- update `.github/workflows/deploy_qa.yml` and `.github/workflows/deploy_release.yml` to pass the GitHub Action variable for the `kubectl` version into the action abobe.
- fix the path for the `kubectl` download
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2489)
> Fix download of kubectl by specific version version

- src/components/ProjectScreen/index.tsx
The `ProjectScreen` component clears the current project on every render, but should only do so on initial render.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2547)
> Fix empty project bug on project creation

- deploy/scripts/setup_combine.py
- deploy/scripts/setup_files/combine_config.yaml
`setup_combine.py` accepts a `--langs`|`-l` option to specify languages to install on the target system.  The script then tried to apply these languages to all charts instead of just the `combine` chart.
This adds a configuration field for each chart to specify whether the language overrides should be added to the chart configuration files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2548)
> Configure whether languages should be installed on a per chart basis

- src/utilities/fontContext.ts
The `.reverse()` was being applied directly to something in the Redux state, causing the order of the project analysis languages to flip (just in the frontend, not in the database) on every refresh.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2550)
> Don't mutate the input in the Font Context constructor

- src/components/DataEntry/DataEntryTable/NewEntry/index.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/tests/index.test.tsx
- src/components/DataEntry/DataEntryTable/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2566)
> Clear the audio when a new entry is submitted

- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
- src/utilities/fontComponents.tsx
Fixes #2605
Figured it out using:
https://mui.com/material-ui/react-autocomplete/#githubs-picker
https://mui.com/material-ui/api/autocomplete/#Autocomplete-prop-renderOption
https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Autocomplete/Autocomplete.js#L555-L571
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2620)
> Make a WithFont extension of <li> for Autocomplete renderOptions

- Backend.Tests/Controllers/StatisticsControllerTests.cs
- Backend.Tests/Mocks/StatisticsServiceMock.cs
Progress on #2647
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2669)
> [StatisticsController] Add tests

- src/backend/index.ts
Removed:
- SemanticDomainController > getAllSemanticDomainTreeNodes
- StatisticsController > getWordsPerDayPerUserCounts
- UserEditController > getAllUserEdits
- WordController > getAllWords
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2660)
> Remove 4 unused functions from backend/index.ts

- src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTable.tsx
Resolves #598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2713)
> [ReviewEntries] Scroll-to-top after changing rows-per-page

- .github/workflows/frontend.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2734)
> [GitHub Actions] Split the longest-to-run workflow job into two

- Backend/Repositories/WordRepository.cs
Resolves #1700
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2789)
> Don't retrieve 0-sense words from the database

- deploy/scripts/setup_files/profiles/prod.yaml
Configure the production Kubernetes cluster to create a certificate for `local.thecombine.app`.  This is intended to be available for users who manage an installation of _The Combine_ on their own hardware.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2825)
> Add local.thecombine.app to list of certificates for offline use

- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/DropWord.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/SidebarDragSense.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/SidebarDrop.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/index.tsx
Have components pull only what they need from the state to avoid sidebar dispatches from causing rerenders.
Fixes #2833
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2834)
> Use targeted useAppSelector to avoid sidebar rerender loop

- src/components/TreeView/TreeNavigator.tsx
- src/components/TreeView/tests/SemanticDomainMock.ts
- src/components/TreeView/tests/TreeNavigator.test.tsx
Up arrow goes to parent, side arrows go to siblings, down arrow only works when there's only one child.
While writing a script for the domain tree tutorial, I felt it was more natural to use (and explain) if the down arrow goes to the first child if there are multiple children (sub)domains.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2840)
> [TreeView] Have down arrow go to first child

- Backend.Tests/Models/SenseTests.cs
- Backend.Tests/Models/WordTests.cs
- Backend/Models/Sense.cs
- Backend/Models/Word.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2867)
> Clean up backend Word/Sense models

- Backend/Controllers/SpeakerController.cs
- src/api/api/speaker-api.ts
Follow-up to #2795 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2872)
> [SpeakerController] Fix CreateSpeaker api path

- src/components/ProjectUsers/SpeakerConsentListItemIcon.tsx
But don't allow speakers to be associated with consent audio (accomplished by the `AudioPlayer` component with the `updateAudioSpeaker` prop undefined).
Follow-up to #2795 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2873)
> [Speaker] Allow consent audio to be deleted

- docs/user_guide/assets/licenses/frontend_licenses.txt
- package-lock.json
- package.json
- src/components/App/AppLoggedIn.tsx
- src/components/App/DatePickersLocalizationProvider.tsx
- src/components/ProjectSettings/ProjectSchedule/CalendarView.tsx
- src/components/ProjectSettings/ProjectSchedule/DateScheduleEdit.tsx
- src/components/ProjectSettings/ProjectSchedule/DateSelector.tsx
- src/components/ProjectSettings/ProjectSchedule/ProjectPickersDay.tsx
- src/components/ProjectSettings/ProjectSchedule/index.tsx
- src/components/ProjectSettings/tests/index.test.tsx
This is prerequisite for installing `material-react-table` for #2875
Changes:
- install `@mui/x-date-pickers` (v6)
- update frontend license report
- replace English-stuck component-specific `LocalizationProvider` wrappers with one `DatePickersLocalizationProvider` in `AppLoggedIn`
- use current `i18next` language in `DatePickersLocalizationProvider`
- add `LocalizationProvider` to the `ProjectSettings` tests (now necessary for the schedule settings with `mui/x-date-pickers` components without their own providers)
- replace deprecated `CalendarPicker` with `DateCalendar`
- remove unnecessary `date` and `onChange` props
- update prop `defaultCalendarMonth` to `referenceDate`
- replace deprecated `renderDay` with corresponding usage of `slots` and `slotProps`
- extract two instances of …
> Update @mui/x-date-pickers and Project Schedule settings

- Backend/Services/MergeService.cs
Redundant audio removal was mistakenly taken out in #2795---I thought it wasn't necessary and was wrong.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2890)
> [MergeDups] Restore removal of redundant audio

- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/DragSense.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/DropWord.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/SidebarDragSense.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/SidebarDrop.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/index.tsx
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/tests/index.test.tsx
- src/goals/MergeDuplicates/MergeDupsTreeTypes.ts
- src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts
- src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx
- src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts
- src/goals/MergeDuplicates/Redux/tests/MergeDupsReducer.test.tsx
Rather than having `MergeTreeSense extends Sense`, have it include `sense: Sense` as a field.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2901)
> [MergeDups] Refactor `MergeTreeSense`

- src/components/App/DefaultState.ts
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/tests/index.test.tsx
- src/goals/MergeDuplicates/MergeDupsTreeTypes.ts
- src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts
- src/goals/MergeDuplicates/Redux/MergeDupsReduxTypes.ts
- src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx
- src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts
- src/goals/MergeDuplicates/Redux/tests/MergeDupsReducer.test.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2896)
> [MergeDups] Clean up state

- src/goals/MergeDuplicates/Redux/MergeDupsActions.ts
- src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx
Follow-up to #2869 
When determining updated ids for the merge blacklist, the identification of words that were merge missed words that had all their senses moved to other words. This pr fixes that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2902)
> Fix determination of which words have been merged

- codecov.yml
https://docs.codecov.com/docs/commit-status#disabling-a-status
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2935)
> Disable CodeCov status checks on PRs

- src/components/DataEntry/DataEntryTable/NewEntry/StyledMenuItem.ts
Sara M. reported that in Data Entry (when adding a new entry with a duplicate vernacular form to multiple existing entries), in the "Select an entry" `VernDialog`, clicking just outside the second button, even on the bottom of the first button, triggers the second button.
It turns out that our `StyledMenuItem` for the `VernDialog` and `SenseDialog` implicitly had `overflow: "hidden",`, so setting `overflow: "clip",` fixes the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2942)
> Prevent Vern/Sense Dialog button invisible overflow

- src/components/Pronunciations/AudioPlayer.tsx
User can change speaker of an audio recording by right-clicking on the AudioPlayer green triangle icon. However, a multi-finger click/tap on a mousepad was overlooked.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2943)
> [AudioPlayer] Catch 2-finger mousepad tap as right click

- src/components/GoalTimeline/tests/GoalRedux.test.tsx
- src/components/ProjectScreen/tests/ChooseProject.test.tsx
- src/goals/CharacterInventory/CharInv/CharacterDetail/tests/index.test.tsx
- src/utilities/testRendererUtilities.tsx
- src/utilities/testUtilities.tsx
- src/utilities/testingLibraryUtilities.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2947)
> Extract test function as general-use utility

- src/components/DataEntry/DataEntryTable/NewEntry/index.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/tests/index.test.tsx
Resolves #2903
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2946)
> [DataEntry > NewEntry] Prevent double submission

- src/components/Buttons/IconButtonWithTooltip.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/DeleteEntry.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/EntryNote.tsx
- src/components/DataEntry/DataEntryTable/RecentEntry.tsx
- src/components/DataEntry/DataEntryTable/tests/RecentEntry.test.tsx
- src/components/Pronunciations/AudioPlayer.tsx
- src/components/Pronunciations/AudioRecorder.tsx
- src/components/Pronunciations/PronunciationsBackend.tsx
- src/components/Pronunciations/RecorderIcon.tsx
- src/components/Pronunciations/tests/AudioRecorder.test.tsx
Following feedback from Sara M, this pr smooths out behavior when editing recent entries in the `DataEntryTable`.
Currently:
- While the vernacular and gloss are being edited, the buttons in the row (note, recording, delete) can still be clicked, but this creates odd behavior when the row is updated (as soon as the focus moves away from the text field being edited)
- When changes are made to a recent entry, while the row is updating, the buttons disappear completely, which is visually jarring.
This pr simply disables the buttons in both cases, making the icons gray and unclickable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2944)
> [RecentEntry] Disable row buttons when editing vern/gloss

- src/components/AppBar/tests/NavigationButtons.test.tsx
- src/components/AppBar/tests/SpeakerMenu.test.tsx
- src/components/DataEntry/DataEntryTable/tests/index.test.tsx
- src/components/DataEntry/tests/index.test.tsx
- src/components/PasswordReset/tests/ResetPage.test.tsx
- src/components/ProjectScreen/tests/ChooseProject.test.tsx
- src/components/ProjectSettings/tests/ProjectImport.test.tsx
- src/components/ProjectUsers/tests/ProjectSpeakersList.test.tsx
- src/components/ProjectUsers/tests/SortOptions.test.tsx
- src/components/ProjectUsers/tests/SpeakerConsentListItemIcon.test.tsx
- src/goals/ReviewEntries/Redux/tests/ReviewEntriesActions.test.tsx
- src/utilities/tests/dictionaryLoader.test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2945)
> Fix uncalled/impotent test functions

- deploy/helm/cert-proxy-server/templates/deployment-cert-proxy-server.yaml
- deploy/helm/cert-proxy-server/templates/deployment-nuc-proxy.yaml
- deploy/helm/thecombine/charts/backend/templates/deployment-backend.yaml
- deploy/helm/thecombine/charts/backend/values.yaml
- deploy/helm/thecombine/charts/database/templates/database.yaml
- deploy/helm/thecombine/charts/database/values.yaml
- deploy/helm/thecombine/charts/frontend/templates/deployment-frontend.yaml
- deploy/helm/thecombine/charts/frontend/values.yaml
- deploy/helm/thecombine/charts/maintenance/templates/cronjob-daily-backup.yaml
- deploy/helm/thecombine/charts/maintenance/templates/deployment-maintenance.yaml
- deploy/helm/thecombine/charts/maintenance/values.yaml
- deploy/helm/thecombine/values.yaml
- deploy/scripts/setup_files/profiles/dev.yaml
- deploy/scripts/setup_files/profiles/prod.yaml
- deploy/scripts/setup_files/profiles/staging.yaml
Adds CPU and memory resource requests for the Kubernetes deployments.  In the cases of the QA and Production servers, resource limits are specified as well.
The initial resource requests are set at approximately 120% of the quiescent levels.  The limits are rather broad and should be adjusted as RWC data become available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3002)
> Specify requested k8s resources for CPU & Memory

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
As of 7 April 2024, Codecov uploads started failing when using `codecov/codecov-action@v3`.
According to codecov/codecov-action issue [#1359](https://github.com/codecov/codecov-action/issues/1359), `v3` is now requiring an upload token.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3047)
> Add codecov token to upload actions

- deploy/scripts/install-combine.sh
- deploy/scripts/setup_files/cluster_config.yaml
- deploy/scripts/uninstall-combine
Update install/uninstall scripts as follows:
- add 'set -eo pipefail' to stop script at first failure
In addition, these changes are made to the install script:
- remove message about creating the initial user; that functionality was removed
- create Python virtual environment at the beginning of the state machine
regardless of initial state
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3044)
> Update install/uninstall scripts

- Backend/Dockerfile
For the .NET 8 Linux images, Microsoft added an app user and an app user group.  Therefore, when the build tries to create the group, it fails.  This PR replaces the `groupadd` and `useradd` commands with `groupmod` and `usermod` commands.  This allows us to set the UID & GID to 999 which is assumed by the maintenance scripts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3048)
> Update user setup for MS .NET 8.0 images

- installer/README.md
This PR fixes some errors to the README.md file for the installer script:
1. Provided missing example to show how to view the current expiration date for _The Combine_'s web certificate; and
2. changed release numbers in examples to actual release numbers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3055)
> Edits to README for standalone installer

- src/components/LandingPage/LandingButtons.tsx
Fixes bug from (https://github.com/sillsdev/TheCombine/pull/2969) where the User Guide button on the landing page links to `https://qa-kube.thecombine.app/docs/[object%20Object]`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3066)
> [Landing Page] Fix broken User Guide button

- src/components/DataEntry/DataEntryTable/NewEntry/VernDialog.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/tests/VernDialog.test.tsx
Fixes #3071
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3072)
> [NewEntry] Prevent crash when duplicate vernacular is cleared

- src/components/Pronunciations/AudioRecorder.tsx
- src/components/Pronunciations/Recorder.ts
- src/components/Pronunciations/RecorderIcon.tsx
Mostly fixes #3073 
Pro: If the record button is clicked/pressed while a previous recording is still active, that previous recording is finished before a new one is started.
Con: If the record button is clicked/tapped just to end a recording that is still going, a second recording blip will also be created (but at least that is easily deleted).
Pro: If focus shifts away from the button, that will also activate the end of the recording. This works if a user clicks elsewhere.
Con: This doesn't always work if the user taps/presses elsewhere, because the initial recording touch doesn't consistently shift focus to the button in the first place.
- - - …
> [Recorder] Add backstops for if cursor departs button

- src/goals/ReviewEntries/ReviewEntriesTable/index.tsx
Fixes #3147 
Disable `autoResetPageIndex` (https://www.material-react-table.com/docs/guides/pagination#customize-pagination-behavior), which resets the table to the first page when editing/filtering/sorting. (It would be nice to have the latter two, but not at the expense of the first one.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3158)
> [ReviewEntries] Turn off return-to-first-page-when-row-is-edited

- src/components/AnnouncementBanner/AnnouncementBanner.tsx
- src/components/Buttons/LoadingButton.tsx
- src/components/Buttons/LoadingDoneButton.tsx
- src/components/ProjectExport/DownloadButton.tsx
- src/components/ProjectSettings/ProjectArchive.tsx
- src/components/Statistics/ProgressBar/LinearProgressBar.tsx
- src/goals/CharacterInventory/CharInv/CharacterList/CharacterStatusText.tsx
- src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditDialog.tsx
#3161 used `sx` color functions with no regard for different size/margin/placement handling between `style` and `sx`. As a consequence, the announcement banner and the loading button spinning wheel (and possibly other things) were way out of place:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3188)
> Retract #3161 due to broken placement styles

- src/goals/MergeDuplicates/Redux/reducerUtilities.ts
- src/goals/MergeDuplicates/Redux/tests/MergeDupsActions.test.tsx
- src/goals/MergeDuplicates/Redux/tests/reducerUtilities.test.ts
Resolves #3166
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3181)
> Preserve more content when merging senses

- src/components/Buttons/PartOfSpeechButton.tsx
Fixes #3177, which appeared in #3156.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3217)
> [ReviewEntries] Prevent table flickering with parts of speech

- .github/workflows/scorecards.yml
The `master` branch fails the `Scorecards supply-chain security / Scorecards analysis (push)` check since #3222, because of `Bump ossf/scorecard-action from 2.3.1 to 2.3.3`. The URL was updated in 2.3.3 (https://github.com/ossf/scorecard-action/pull/1376).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3224)
> [GHA] Update OSSF URL in Harden Runner

- README.md
Resolves #3159 
To review this pr, check out the [README in this branch](https://github.com/sillsdev/TheCombine/tree/readme-get-started?tab=readme-ov-file#the-combine):
* Does the placement of the new step make sense in the README?
* Is the instruction clear, concise, correct, and without spelling/grammar errors?
* Do the links work?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3230)
> [README] Add 'Getting Started' step to load sem doms

- tsconfig.json
We're already using ES6 features (e.g., arrow functions and `let`/`const`), so this change just helps the IDE know what Typescript syntax is allowable.
Before this change, my IDE was complaining about the use of the `/u` RegEx ending in `src/utilities/spellChecker.ts`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3232)
> Update TS target to ES6 (which we already use)

- README.md
[Before](https://github.com/sillsdev/TheCombine/tree/master?tab=readme-ov-file#the-combine), the links were all to the same general actions page and the scorecard badge always said passing even when it failed:
[After](https://github.com/sillsdev/TheCombine/tree/badges?tab=readme-ov-file#the-combine), the links go to specific relevant actions and the unhelpful action badges are removed:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3225)
> [README] Remove unhelpful action badges

- src/components/TreeView/TreeDepiction/DomainTileButton.tsx
- src/components/TreeView/TreeDepiction/tests/__snapshots__/DomainTileButton.test.tsx.snap
- src/components/TreeView/TreeDepiction/tests/__snapshots__/index.test.tsx.snap
- src/components/TreeView/TreeNavigator.tsx
Fixes #3215
- Adds functionality for Enter key to select the current domain when navigating the tree with arrows
- Removes ability to tab-select any of the domain tiles other than the current domain
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3221)
> [TreeView] Improve ENTER key behavior

- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/utilities/spellChecker.ts
- src/utilities/tests/spellChecker.test.ts
Resolves #3189
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3226)
> [GlossWithSuggestions] Use ... for all but last word

- src/components/DataEntry/DataEntryTable/NewEntry/SenseDialog.tsx
- src/components/DataEntry/DataEntryTable/RecentEntry.tsx
- src/components/DataEntry/DataEntryTable/index.tsx
- src/components/DataEntry/DataEntryTable/tests/index.test.tsx
- src/utilities/tests/wordUtilities.test.ts
- src/utilities/wordUtilities.ts
Resolves #3167
Acceptance test:
- Data Entry:
- In semantic domain 1, create entry with vernacular form "vern" and gloss "glossA"
- Project settings:
- In "Basic Settings" tab, make sure Autocomplete is on
- In "Languages" tab, add a new analysis language and move it to the top of the list
- Data Entry:
- In semantic domain 2, begin adding a new word by typing "vern" in the Vernacular text field
- Select "vern" from the dropdown options (either by clicking it or pressing enter when it's highlighted)
- Verify that the "Select and Entry" dialog pops up and that there is a "vern  glossA" option
- Select it (either by clicking it or pressing enter when it's highlighted)
- Verify that the "Select a Sense" dialog appears and that there is a "glossA" option
- Select it (either by clicking it or …
> [DataEntryTable] Use current analysis lang with sense glosses

- src/components/DataEntry/DataEntryTable/EntryCellComponents/DeleteEntry.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/VernDialog.tsx
- src/components/DataEntry/DataEntryTable/NewEntry/index.tsx
- src/components/DataEntry/DataEntryTable/RecentEntry.tsx
Fixes #3258 
Makes a simplification to decrease fragility and increase managability: When enter is pressed from the vernacular field, always shift focus to the gloss field.
Fixes bug introduced in #3290 by using the `Dialog` prop `disableRestoreFocus`
Fixes prop-with-key-spread console warning by explicitly specifying the `LiWithFont`'s key
Remove unnecessary `Autocomplete` props in `GlossWithSuggestions` and `VernWithSuggestions`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3297)
> [DataEntryTable] Fix NewEntry vernacular focus issues

- src/components/Pronunciations/Recorder.ts
- src/components/Pronunciations/RecorderIcon.tsx
- src/components/Pronunciations/utilities.ts
https://github.com/sillsdev/TheCombine/pull/3247 broke recording on Firefox:
```
Uncaught (in promise) TypeError: 'microphone' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
```
(See https://stackoverflow.com/questions/53147944/firefox-permission-name-member-of-permissiondescriptor-camera-is-not-a-vali)
This fix checks for permission on all non-Firefox browsers and assumes permission for Firefox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3298)
> Don't check mic permission on Firefox

- src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
- src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
Fixes #3320
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3321)
> [DataEntry] Let arrows to move out of vern/gloss suggestions

- docs/user_guide/docs/goals.es.md
- docs/user_guide/docs/goals.md
- docs/user_guide/docs/goals.zh.md
- docs/user_guide/docs/project.es.md
The note text wasn't indented, resulting in an empty note followed by a paragraph with the intended note content.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3325)
> [User Guide] Fix displaced note

- deploy/scripts/setup_files/profiles/prod.yaml
- deploy/scripts/setup_files/profiles/staging.yaml
- src/types/runtimeConfig.ts
The previous site key was only for QA. New keys were generated for both QA and the live server.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3331)
> Update Turnstile site key

- deploy/scripts/app_release.py
- deploy/scripts/aws_env.py
- deploy/scripts/build.py
- deploy/scripts/check_certs.py
- deploy/scripts/combine_charts.py
- deploy/scripts/kube_env.py
- deploy/scripts/package_images.py
- deploy/scripts/sem_dom_import.py
- deploy/scripts/setup_cluster.py
- deploy/scripts/setup_combine.py
- deploy/scripts/setup_target.py
- maintenance/scripts/add_user_to_proj.py
- maintenance/scripts/combine_backup.py
- maintenance/scripts/combine_restore.py
- maintenance/scripts/db_update_audio_type.py
- maintenance/scripts/get_fonts.py
- maintenance/scripts/monitor.py
- maintenance/scripts/rm_project.py
- maintenance/scripts/update_cert.py
- scripts/clean_aws_repo.py
- scripts/cleanup_local_repo.py
- scripts/generate_openapi.py
- scripts/get_fonts_dev.py
- scripts/split_dictionary.py
- scripts/subtitle_tutorial_video.py
Change the "shebang" for Python scripts from:
```
#!/usr/bin/env python3
```
to
```
#!/usr/bin/env python
```
The original shebang was set so that Linux users can run the Python scripts by just providing the script name, e.g. `./deploy/scripts/app_release.py --get`.
Both of these shebang lines work because the `venv` module sets up `python3` and `python` to point to the version of Python in the virtual environment.  However, when the `venv` is created on Windows, only the `python` alias is created.  This means that the scripts fail when run from a `Git Bash`  session.
The new shebang works for both environments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3370)
> Fix shebang for Python scripts

- deploy/scripts/aws_env.py
Hit an error deploying The Combine because it is possible for the command that lists AWS profiles to have an extra empty line, which results in trying to fetch details for a profile with no name. (Have you every tried to go through the desert on a profile with no name?)
This pr avoids that snag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3387)
> Avoid empty lines in aws profiles list

- public/locales/en/translation.json
- src/components/ProjectSettings/ProjectLanguages.tsx
Resolves #2661  
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3408)
> Provide feedback after Vernacular name change

- src/components/Pronunciations/AudioRecorder.tsx
- src/components/Pronunciations/RecorderIcon.tsx
- src/components/Pronunciations/tests/RecorderIcon.test.tsx
Fixes #3411 and prevents trying to upload an empty audio file.
Stress-test with rapid repeated clicks on the same record button. Then pause a do a normal recording on the same button.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3414)
> Prevent double-click recorder bug

- deploy/ansible/playbook_k3s_airgapped_files.yml
- deploy/ansible/roles/container_engine/defaults/main.yml
- deploy/ansible/roles/container_engine/tasks/main.yml
- deploy/ansible/roles/container_images/defaults/main.yml
- deploy/ansible/roles/container_images/tasks/main.yml
- deploy/ansible/roles/helm_install/defaults/main.yml
- deploy/ansible/roles/helm_install/tasks/main.yml
- deploy/ansible/vars/k3s_versions.yml
Prequel to #3400
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3438)
> [ansible] Set up for more general architecture support

- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
- .github/workflows/maintenance.yml
- README.md
- deploy/helm/aws-login/templates/aws-ecr-login-cronjob.yaml
- deploy/helm/aws-login/templates/aws-ecr-login-oneshot.yaml
- deploy/helm/aws-login/values.yaml
- deploy/helm/thecombine/charts/maintenance/templates/cronjob-daily-backup.yaml
- deploy/helm/thecombine/charts/maintenance/templates/cronjob-update-fonts.yaml
- deploy/helm/thecombine/charts/maintenance/templates/get-fonts-hook.yaml
- deploy/helm/thecombine/charts/maintenance/values.yaml
- maintenance/Dockerfile
For maintenance use of `aws/kubectl`, switch from [Docker Hub (amd64 only)](https://hub.docker.com/r/sillsdev/aws-kubectl/tags) to [AWS ECR (both amd64 and arm64)](https://gallery.ecr.aws/thecombine/aws-kubectl).
Parallel pr: https://github.com/sillsdev/aws-kubectl/pull/5
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3449)
> [maintenance] Support arm64

- src/components/DataEntry/DataEntryTable/index.tsx
Fixes #3517 
Acceptance test:
- Create a project with `Backend.Tests/Assets/SingleEntryLiftWithSound.zip`
- Go to Data Entry and select any domain
- In the Vernacular field, type "testing" and press Tab
- When the "Select an entry" and "Select a sense" dialogs appear, select the exiting one
- Once the Gloss field is populated with "what is this", press Enter to submit the word
- In the new row that appears, add a note
- Go to project settings and export the project
- Open the .zip and the contained .lift file
- Verify that the entry's note has a language (not just an empty string)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3518)
> [DataEntry] Ensure analysis lang is on recent entry notes

- .github/workflows/backend.yml
- .github/workflows/codeql.yml
Our CodeQL results were failing to upload (e.g., https://github.com/sillsdev/TheCombine/actions/runs/12777064526/job/35617067435#step:7:486 and https://app.stepsecurity.io/github/sillsdev/TheCombine/actions/runs/12777064526?jobid=35617067435&tab=network-events). Added `uploads.github.com:443` to `.github/workflows/codeql.yml` to fix that (e.g., https://github.com/sillsdev/TheCombine/actions/runs/12790261713/job/35655616598?pr=3522#step:7:481).
Harden Runner is only now handling all the backend/CodeQL_build network events (and still doesn't report the network events of backend/test_build -- see https://app.stepsecurity.io/github/sillsdev/TheCombine/actions/runs/12777064538?jobid=35617067433&tab=network-events). Added the missing endpoint `builds.dotnet.microsoft.com:443` to …
> [GHA] Update backend and CodeQL endpoints

- .github/workflows/backend.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/deploy_release.yml
Supersedes #3524
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3527)
> Update setup-dotnet to v4.2.0 and clear old endpoints

- src/types/goals.ts
Hi sillsdev,
I have removed the user-related properties and imports from the Goal class and simplified the constructor and related code.
Please review the changes and provide any feedback.
Thank you!
Resolves #3525 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3526)
> Issue#3525: Goal class has unused field: user 

- Backend/Controllers/SpeakerController.cs
- Backend/Controllers/UserController.cs
- Backend/Controllers/UserRoleController.cs
- src/api/api/speaker-api.ts
- src/api/api/user-api.ts
- src/api/models/user.ts
- src/backend/index.ts
Resolves #3474
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3528)
> Move email, name from url to body to protect PII

- src/goals/Redux/GoalActions.ts
Follow-up to #3523, which would have allowed the backend to keep returning the same bad set of potential duplicates.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3530)
> [MergeDups] Blacklist bad merge sets

- Backend.Tests/Otel/LocationProviderTests.cs
- Backend/Otel/LocationProvider.cs
- Backend/Otel/OtelKernel.cs
Reverts/revises parts of #3533, #3537
Resolves #3534 (hopefully)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3538)
> [Otel] Remove debugging; Use different header

- src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts
Fixes #3546
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3548)
> [MergeDups] Fix bug preventing use of extra column

- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/index.tsx
Fixes #3521 
To test:
- import/open a project with protected senses (e.g. `Natqgu.zip`)
- go to Merge Duplicates
- find a set with at least one protected and one non-protected sense
- drag'n'drop a non-protected sense into a protected sense
- when the sidebar pops open, drag the secondary sense out of the sidebar and into any word
- drag'n'drop the non-protected sense back into a protected senses
- when the sidebar opens, drag the secondary sense into the trash and confirm deletion
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3561)
> [MergeDups] Allow actions from sidebar of protected sense

- .github/workflows/backend.yml
- .github/workflows/codeql.yml
* Remove CodeQL from the `backend` workflow, because:
* it was redundant with what's in the `codeql` workflow,
* it had a no-longer-necessary "Setup .NET" step that was a relic of CodeQL previously not supporting the newest .NET,
* it wasn't even uploading results (e.g., https://github.com/sillsdev/TheCombine/actions/runs/13061541171/job/36446160360#step:9:527);
* Add `actions` to the languages to analyze, since CodeQL now supports GHA analysis;
* Bump to the latest version, which includes said support.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3563)
> [GHA] Update CodeQL workflows

- .github/workflows/deploy_release.yml
* Remove `branches: [master]` which is meaningless in `release:`.
* Revert the part of #3527 that failed to notice that the region for uploading to public registries is always `us-east-1`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3551)
> [GHA] Clean up deploy_release workflow

- public/locales/en/translation.json
- src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx
We toast an error when user tries to save a completely empty sense (no definition, gloss, semantic domain, or part of speech), but the error message is empty. This pr adds an error message.
To test:
* Open a project with at least one entry
* Go to Review Entries
* Click the edit icon at the start of an entry row
* Click the edit icon next to a sense
* Delete all the content
* Click the green checkmark to save the sense
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3593)
> [ReviewEntries] Add error text when trying to save empty sense

- public/locales/en/translation.json
- src/components/SiteSettings/ProjectManagement/index.tsx
- src/components/SiteSettings/ProjectManagement/tests/index.test.tsx
Fixes #3552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3565)
> [SiteSettings] Redesign project management

- public/locales/en/translation.json
- src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/index.tsx
Resolves #2099
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3607)
> [MergeDups] Toast when actions fail

- Backend.Tests/Controllers/LiftControllerTests.cs
- Backend/Services/MergeService.cs
These two unnecessary semicolons are now causing the backend format check to fail: https://github.com/sillsdev/TheCombine/actions/runs/13526485054/job/37798239572?pr=3622
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3623)
> Remove extraneous semicolons

- .github/workflows/backend.yml
- .github/workflows/codeql.yml
- .github/workflows/commit_message_check.yml
- .github/workflows/database.yml
- .github/workflows/dependency-review.yml
- .github/workflows/deploy_qa.yml
- .github/workflows/frontend.yml
- .github/workflows/maintenance.yml
- .github/workflows/pages.yml
- .github/workflows/python.yml
Also, cancel in-progress sillsdev.github.io/TheCombine and qa-kube.thecombine.app deployment workflows when a new commit is pushed to `master`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3658)
> Cancel GHA workflows when another commit is pushed to a pr

- Backend.Tests/Controllers/WordControllerTests.cs
- Backend.Tests/Mocks/WordRepositoryMock.cs
- Backend/Controllers/LiftController.cs
- Backend/Controllers/WordController.cs
- Backend/Interfaces/IWordRepository.cs
- Backend/Repositories/WordRepository.cs
- src/api/api/word-api.ts
- src/backend/index.ts
- src/components/ProjectExport/ExportButton.tsx
- src/components/ProjectSettings/tests/index.test.tsx
Resolves #3751 
Reduces delay before the Export button in enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3756)
> For non-empty project check, just query database for 1 word

- src/components/DataEntry/DataEntryTable/NewEntry/StyledMenuItem.ts
- src/components/ProjectScreen/ChooseProject.tsx
Resolves #3792 
Before & After (with cursor hovering over second project):
(... except with a line added at the bottom too.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3807)
> [ChooseProject] Add horizontal lines between project names

- Backend.Tests/Controllers/SemanticDomainControllerTests.cs
- Backend/Controllers/SemanticDomainController.cs
- src/api/api/semantic-domain-api.ts
This function isn't currently used in the frontend.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3837)
> [SemanticDomainController] Fix GetAllSemanticDomainTreeNodes return type

- Backend.Tests/Controllers/AvatarControllerTests.cs
- Backend/Controllers/AvatarController.cs
- src/backend/index.ts
- src/components/UserSettings/ClickableAvatar.tsx
Also expand controller testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3839)
> [AvatarController] Restrict UploadAvatar to current user

- Backend.Tests/Controllers/AvatarControllerTests.cs
- Backend.Tests/Controllers/ProjectControllerTests.cs
- Backend.Tests/Controllers/UserEditControllerTests.cs
- Backend.Tests/Controllers/UserRoleControllerTests.cs
- Backend.Tests/Mocks/PermissionServiceMock.cs
- Backend.Tests/Services/PermissionServiceTests.cs
- Backend/Controllers/AvatarController.cs
- Backend/Controllers/ProjectController.cs
- Backend/Controllers/UserController.cs
- Backend/Interfaces/IPermissionService.cs
- Backend/Services/PermissionService.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3876)
> [PermissionService] Update authenticated user handling

- src/goals/Redux/GoalActions.ts
- src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditDialog.tsx
- src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/tests/EditDialog.test.tsx
- src/goals/ReviewEntries/ReviewEntriesTable/index.tsx
Fixes #3543 without even touching an audio/pronunciations file.
Both `EditCell` and `PronunciationsCell` (via the `confirm` prop) use `replaceWord` from their parent `ReviewEntriesTable`, so this pr pulls the goal-history-updating dispatch out of `EditCell` and executes it within `replaceWord` (where it really should have been in the first place).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3926)
> [ReviewEntries] Store edits from Pronunciations column

- .github/labeler.yml
- Backend/Dockerfile
- deploy/Dockerfile
- deploy/scripts/install-combine.sh
- deploy/scripts/package_images.py
Prep for #3400
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3927)
> Do minor labeler, deploy cleanup

- Backend.Tests/Controllers/InviteControllerTests.cs
- Backend.Tests/Controllers/PasswordResetControllerTests.cs
- Backend.Tests/Controllers/UserControllerTests.cs
- Backend.Tests/Mocks/PasswordResetRepositoryMock.cs
- Backend.Tests/Mocks/PasswordResetServiceMock.cs
- Backend.Tests/Services/PasswordResetServiceTests.cs
- Backend/Controllers/InviteController.cs
- Backend/Controllers/PasswordResetController.cs
- Backend/Interfaces/IPasswordResetService.cs
- Backend/Services/InviteService.cs
- Backend/Services/PasswordResetService.cs
- Backend/Startup.cs
- deploy/helm/thecombine/charts/backend/values.yaml
- src/api/api/invite-api.ts
- src/backend/index.ts
- src/components/InvalidLink/index.tsx
- src/components/Login/Login.tsx
- src/components/Login/ProjectInvite.tsx
- src/components/Login/Signup.tsx
- src/components/PasswordReset/ResetPage.tsx
- src/components/ProjectSettings/tests/index.test.tsx
- src/components/UserSettings/UserSettings.tsx
- src/components/UserSettings/tests/UserSettings.test.tsx
- src/utilities/userUtilities.ts
- src/utilities/utilities.ts
Sequel to #3920 
Prequel to #3877 
Changes:
- `InviteController`: method `ValidateToken` -> `ValidateInviteToken` (to avoid ambiguity in OpenAPI with other tokens)
- `PasswordResetService`:
- param `EmailOrUsername` -> `emailOrUsername`
- remove unnecessary method `ExpirePasswordReset`
- email title "Combine ..." -> "The Combine ..."
- `InvalidLink` component: add prop for optional body text
- `ProjectInvite` component: remove extraneous executions of `validateLink`
- `SignUp` component: prop `returnToEmailInvite` -> `onSignup` (for more general use)
- `UserSettings` component: set `email` state from normalization of new `emailPunycode` state (to only normalize in one place)
- `userUtilities`:
- created from two `utilities` functions and one `UserSettings` function
- `enqueueSnackbar` -> …
> Clean up login/token/user-related things
