Backend/Controllers/FrontierController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/WordController.cs

We will need to make sure this actually works for actual RELEASE mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/8)

Add Debug Only tags to some API functions

---

Backend/Controllers/UserController.cs
package.json
src/components/App/App.tsx
src/components/CreateProject/CreateProjectActions.tsx
src/components/CreateProject/CreateProjectComponent.tsx
src/components/CreateProject/CreateProjectReducer.tsx
src/components/CreateProject/index.tsx
src/components/CreateProject/tests/CreateProjectActions.test.tsx
src/components/CreateProject/tests/CreateProjectReducer.test.tsx
src/components/Login/LoginActions.tsx
src/components/Temp/TempReducer.tsx
src/resources/translations.json
src/rootReducer.tsx
src/types/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/9)

Create Project ui

---

Backend/Controllers/UserController.cs
Backend/Controllers/WordController.cs
docs/api/project/get.md
docs/api/project/settings/get.md
docs/api/project/words/get.md
docs/api/users/get_all.md

Having a body in a GET request is unsupported by axios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/10)

Remove filter argument from get_all_* API routes

---

package.json

* Move scripts above dependencies for better
maintenance
* Move development dependencies into devDependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/12)

Improve package.json layout

---

package.json
src/components/App/App.test.tsx
src/components/App/App.tsx
src/components/CreateProject/CreateProjectActions.tsx
src/components/Login/AuthHeaders.tsx
src/components/Login/LoginActions.tsx
src/components/Login/LoginComponent.tsx
src/components/Login/LoginReducer.tsx
src/components/Login/LogoutButton.tsx
src/components/Login/index.tsx
src/components/Login/tests/LoginActions.test.tsx
src/components/Login/tests/LoginReducer.test.tsx
src/components/Login/tests/__mocks__/axios.ts
src/components/PrivateRoute/index.tsx
src/index.tsx
src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/11)

Login route

---

src/components/App/App.tsx
src/components/Login/LoginActions.tsx
src/components/Login/LoginComponent.tsx
src/components/Login/LoginReducer.tsx
src/components/Login/index.tsx
src/resources/translations.json

There are no browser alerts in the login page now. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/14)

Login page alerts

---

src/goals/MergeDupGoal/DupFinder/dupFinder.ts
src/goals/MergeDupGoal/DupFinder/tests/dupFinder.test.ts
src/types/word.tsx

Word includes updates required by other branches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/17)

Added DupFinder Utility Class

---

Backend/Services/ProjectApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/22)

Fix lift upload

---

Backend/BackendFramework.csproj
Backend/Controllers/FrontierController.cs
Backend/Controllers/UploadContoller.cs
Backend/Controllers/WordController.cs
Backend/Interfaces/IWordRepository.cs
Backend/Interfaces/IWordService.cs
Backend/Services/LiftService.cs
Backend/Services/WordApiServices.cs
Backend/Services/WordRepository.cs
Backend/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/26)

Refactored Backend words api

---

package-lock.json
src/components/CreateProject/CreateProjectActions.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/30)

Allow project creation without lift file

---

src/goals/MergeDupGoal/MergeDupStep/reducer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/35)

Fix disappearing words

---

.gitignore
Backend/appsettings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/37)

Rename the datases

---

src/goals/MergeDupGoal/MergeDupStep/WordList/component.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/resources/translations.json

Add scroll for list of duplicates, 
Modify 'next' button
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/36)

Improve merge duplicate step ux

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/38)

Add backend testing to npm test

---

src/goals/MergeDupGoal/MergeDupStep/MergeRow/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordCard/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordCard/index.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/component.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/39)

Improve word card format

---

package-lock.json
package.json
src/components/App/DefaultState.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorAction.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorReducer.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorScroll.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/index.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorAction.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorReducer.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorScroll.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/__snapshots__/GoalSelectorScroll.test.tsx.snap
src/components/GoalTimeline/GoalSwitcher/GoalSwitcherComponent.tsx
src/components/GoalTimeline/GoalSwitcher/tests/GoalSwitcher.test.tsx
src/components/GoalTimeline/tests/GoalTimelineComponent.test.tsx
src/rootReducer.tsx
src/types/goals.tsx
src/types/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/34)

Add scrolling goal select UI

---

src/components/App/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordCard/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/component.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/goals/MergeDupGoal/MergeDupStep/reducer.tsx
src/resources/translations.json
src/types/word.tsx

- Change I'm done to Merge these words
- Fix crashing problem when moving cards with multiple glosses
- Make duplicate help not appear on the word you are dragging
- Add use of react keys to make lists more stable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/45)

Fix a number of visual problems in mergedupstep

---

src/backend/index.tsx
src/components/CreateProject/CreateProjectActions.tsx
src/components/Login/LoginActions.tsx
src/goals/CharInventoryCreation/CharacterInventoryActions.tsx
src/goals/CreateCharInv/CreateCharInv.tsx
src/goals/CreateStrWordInv/CreateStrWordInv.tsx
src/goals/HandleFlags/HandleFlags.tsx
src/goals/MergeDupGoal/DuplicateFinder/DuplicateFinder.ts
src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/goals/MergeDupGoal/MergeDupStep/reducer.tsx
src/goals/MergeDupGoal/MergeDups.tsx
src/goals/SpellCheckGloss/SpellCheckGloss.tsx
src/goals/ValidateChars/ValidateChars.tsx
src/goals/ValidateStrWords/ValidateStrWords.tsx
src/goals/ViewFinal/ViewFinal.tsx
src/types/user.tsx

- Add authentication to wrapper
- Update user model
- Use api wrapper instead of hand written routes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/50)

Use api wrapper

---

Backend/Controllers/FrontierController.cs
setupMongo.js
setupMongo.ts
src/backend/index.tsx
src/components/CreateProject/CreateProjectActions.tsx
src/components/CreateProject/CreateProjectReducer.tsx
src/components/Login/LoginActions.tsx
src/components/Login/index.tsx
src/components/Temp/TempActions.tsx
src/serviceWorker.ts
src/types/baseGoal.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/51)

Fix API Routing Problems

---

docs/meeting_notes/Merge_Duplicates_Trials/merge_duplicates_trials.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/49)

Add 6-18 Merge Duplicates Trial Notes

---

src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/goals/MergeDupGoal/MergeDupStep/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/54)

Combine 'next' and 'refresh' buttons

---

Backend.Tests/UserRoleControllerTests.cs
Backend.Tests/UserRoleServiceMock.cs
Backend/Models/UserRole.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/58)

Add UserRole API Testing

---

package-lock.json
src/components/App/component.tsx
src/components/GoalTimeline/GoalTimelineReducers.tsx
src/components/Login/LoginActions.tsx
src/components/Login/LoginComponent.tsx
src/components/Login/index.tsx
src/goals/CharInventoryCreation/index.tsx
src/goals/DraggableWord/reducer.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/actions.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/reducer.tsx
src/goals/MergeDupGoal/MergeDupStep/actions.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/goals/MergeDupGoal/MergeDupStep/reducer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/64)

Obey linter warnings

---

src/goals/MergeDupGoal/MergeDupStep/WordList/actions.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/reducer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/63)

Add sorting to word list

---

Backend.Tests/UploadControllerTests.cs
Backend/Models/Word.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/70)

Big Fix for upload files

---

src/goals/MergeDupGoal/MergeDupStep/MergeRow/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/component.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/69)

Add tooltips to merge dups step

---

docs/frontend/App/app.md
docs/frontend/README.md
docs/frontend/addingComponents.md
docs/frontend/fileStructure/backend.md
docs/frontend/fileStructure/components.md
docs/frontend/fileStructure/fileStructure.md
docs/frontend/fileStructure/goals.md
docs/frontend/fileStructure/index.tsx.md
docs/frontend/fileStructure/resources.md
docs/frontend/fileStructure/rootReducer.tsx.md
docs/frontend/fileStructure/serviceWorker.ts.md
docs/frontend/fileStructure/store.tsx.md
docs/frontend/fileStructure/types.md
src/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/68)

Front end docs

---

src/components/ContextMenu/ContextMenu.tsx
src/components/ContextMenu/tests/ContextMenu.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorAction.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorReducer.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorScroll.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/index.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorAction.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorReducer.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorScroll.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/__snapshots__/GoalSelectorScroll.test.tsx.snap
src/components/GoalTimeline/GoalTimelineComponent.tsx
src/resources/translations.json

In addition to centering ui/fixing its style:
* Adds a custom right-click drop-down menu for goal cards
* Repairs jerry-rigged unit tests for GoalSelectorScroll
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/60)

Upgrade goal selector scroll ui

---

.gitignore
Backend.Tests/UploadControllerTests.cs
Backend/Controllers/UploadContoller.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/75)

Backend Avatar Upload

---

src/components/CreateProject/CreateProjectComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/89)

Add check for file selection (Small fix for issue #76)

---

Backend.Tests/ProjectControllerTests.cs
Backend.Tests/UploadControllerTests.cs
Backend.Tests/UserControllerTests.cs
Backend.Tests/Util.cs
Backend.Tests/WordControllerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/97)

Fixed random number generator

---

src/components/GoalTimeline/DefaultState.tsx
src/goals/CharInventoryCreation/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/96)

Hook Character Inventory Creation UI to the rest of the website

---

src/backend/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/99)

Fix upload

---

package-lock.json
src/goals/MergeDupGoal/MergeDupStep/MergeRow/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordCard/component.tsx
src/goals/MergeDupGoal/MergeDupStep/WordList/component.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx

* Makes instructional cards always visible
* Gives the word list and merge word pane their own scrollbars
* Starts adding screen scaling to the UI, but will be incomplete until scaling text size is an option
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/90)

Idiotproof MergeDups UI

---

src/components/App/component.tsx
src/components/CreateProject/CreateProjectComponent.tsx
src/components/Login/LoginActions.tsx
src/components/Login/LoginComponent.tsx
src/components/Login/LoginPage/LoginComponent.tsx
src/components/Login/LoginPage/index.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/Login/RegisterPage/index.tsx
src/resources/translations.json

Added a separate page for register. Made design changes. 💯
---
Reviewers: I recommend checking out this branch to see the changes for yourself and test out user registration.
<br/>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/102)

Improve Login/Register UI

---

docs/meeting_notes/Merge_Duplicates_Trials/merge_duplicates_trials.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/107)

6-26 User Test Notes

---

src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorScroll.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorScroll.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/__snapshots__/GoalSelectorScroll.test.tsx.snap
src/goals/MergeDupGoal/MergeDupStep/MergeRow/component.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/component.tsx
src/goals/MergeDupGoal/MergeDupStep/component.tsx
src/index.tsx
src/types/theme.ts

* Not currently enabled, as more work will need done to make it look good
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/103)

Add theme prototype

---

Backend.Tests/LiftControllerTests.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/UserController.cs
Backend/Services/LiftService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/111)

Fix route for upload

---

src/goals/MergeDupGoal/DuplicateFinder/DuplicateFinder.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/113)

Fix Merge Goal Crashing when DB Empty

---

src/components/CreateProject/CreateProjectComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/115)

Add dependency for colors (Fix)

---

Backend.Tests/LiftControllerTests.cs
Backend.Tests/UserControllerTests.cs
Backend.Tests/UserEditControllerTests.cs
Backend.Tests/UserEditServiceMock.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserEditController.cs
Backend/Interfaces/IUserEditService.cs
Backend/Models/User.cs
Backend/Models/UserEdit.cs
Backend/Services/LiftService.cs
Backend/Services/UserEditApiServices.cs

*Signed-off-by: The very real SILMarkFuller <mark_fuller@sil.org>
*not actually Mark
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/114)

Reorganize User Roles

---

Backend/Controllers/UserEditController.cs
Backend/Services/LiftService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/117)

Hotfix UserEdits

---

Backend.Tests/Backend.Tests.csproj
Backend.Tests/coverage.json
README.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/119)

Add test coverage script and update README

---

package-lock.json
src/components/Login/LoginPage/LoginComponent.tsx
src/components/Login/LoginPage/tests/LoginComponent.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/118)

Add unit tests to LoginComponent

---

Backend/Services/LiftService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/127)

Implement citation form for import

---

src/goals/MergeDupGoal/DuplicateFinder/DuplicateFinder.ts

*The Sams made this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/129)

Bigfix: Crash when no possible duplicates found.

---

src/goals/CharInventoryCreation/components/SampleWords/SampleWordsComponent.tsx
src/goals/CharInventoryCreation/components/SampleWords/WordTileComponent.tsx

Fix highlighting space character 
Refreshing sample words when a word is ignored
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/132)

Fix character inventory

---

src/components/Login/LoginPage/LoginComponent.tsx
src/components/Login/LoginPage/tests/LoginComponent.test.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx

- updating the fields in the state only requires one function, rather than one for each field  
- the full bee movie script can't be used for a field 🐝 (input field length is limited to 100 chars)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/134)

Simplify updating state in login and register forms

---

src/backend/index.tsx
src/components/AppBar/AppBarComponent.tsx
src/components/ContextMenu/ContextMenu.tsx
src/components/EmptyGoal/EmptyGoalComponent.tsx
src/components/GoalTimeline/GoalSuggestions/GoalSuggestionsComponent.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/GoalSelectorScroll.tsx
src/components/GoalTimeline/GoalTimelineComponent.tsx
src/components/Login/LoginPage/index.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/Login/RegisterPage/index.tsx
src/goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen.tsx
src/goals/DefaultGoal/BaseGoalScreen/DisplayProg/displayProg.tsx
src/goals/DefaultGoal/BaseGoalWidget/BaseGoalWidget.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/MergeStackComponent.tsx
src/index.tsx

Just fixing files so that ~20 linter warnings are cleared
Note:
- if your React component doesn't need a constructor, don't give it one
- if you just want to perform an action for each element in an array, use `.forEach()`, not `.map()`
- use the stricter comparison operators `!==` and `===`, not `!=` and `==`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/137)

Follow linter warnings

---

package-lock.json
src/components/GoalRoute/component.tsx
src/components/GoalTimeline/DefaultState.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSwitcherComponent.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/GoalTimelineHorizontal.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/HorizontalDisplay.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/index.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/tests/GoalTimelineHorizontal.test.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/tests/HorizontalDisplay.test.tsx
src/resources/translations.json

* Horizontal UI with history on left, our suggestion in the middle, and alternate options to the right
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/133)

Create a new UI for selecting goals

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupsTree.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/MergeRowComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/MergeStackComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/138)

Change merge tree to be self contained

---

__mocks__/axios.js
src/components/Login/LoginActions.tsx
src/components/Login/tests/LoginActions.test.tsx
src/components/Login/tests/LoginReducer.test.tsx
src/goals/CharInventoryCreation/CharacterInventoryComponent.tsx
src/goals/CharInventoryCreation/components/CharacterSet/tests/CharacterSetComponent.test.tsx
src/goals/CharInventoryCreation/components/SampleWords/SampleWordsComponent.tsx
src/goals/CharInventoryCreation/components/SampleWords/WordTileComponent.tsx
src/goals/CharInventoryCreation/components/SampleWords/tests/SampleWordsComponent.test.tsx
src/goals/CharInventoryCreation/components/SampleWords/tests/WordTileComponent.test.tsx
src/goals/CharInventoryCreation/tests/CharInventoryActions.test.tsx
src/goals/CharInventoryCreation/tests/CharacterInventoryComponent.test.tsx
src/goals/CharInventoryCreation/tests/CharacterInventoryReducer.test.tsx
src/goals/CharInventoryCreation/tests/__snapshots__/CharacterInventoryComponent.test.tsx.snap

* Add tests for:
- Character set component
- Sample words component
- Word tile component
- Char inventory reducer + actions
* Update tests for:
- Login reducer + actions
- Character inventory component
* Modifications to other existing files to facilitate tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/128)

Add additional unit tests

---

src/components/CreateProject/CreateProjectComponent.tsx
src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/144)

Change project upload from .lift to .zip

---

src/backend/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/149)

Removed extraneous "

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/150)

Fix Mongo starting in wrong database

---

Backend/Services/UserApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/154)

Remove password from update user

---

Backend.Tests/AudioControllerTests.cs
Backend.Tests/UserEditControllerTests.cs
Backend.Tests/WordControllerTests.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/WordController.cs

Fix #152 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/155)

Check for valid project in every endpoint

---

Backend.Tests/UserEditControllerTests.cs
Backend.Tests/UserEditRepositoryMock.cs
Backend/Controllers/UserEditController.cs
Backend/Models/User.cs
package-lock.json
src/backend/index.tsx
src/components/GoalTimeline/GoalTimelineComponent.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/GoalTimelineHorizontal.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/index.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/tests/GoalTimelineHorizontal.test.tsx
src/components/GoalTimeline/GoalsActions.tsx
src/components/GoalTimeline/index.tsx
src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
src/components/Login/LoginActions.tsx
src/types/user.tsx

Change the way the frontend calls the backend when creating/loading a user edit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/156)

Create user edit fix

---

src/backend/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/158)

Store projectID in localstorage

---

src/backend/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/159)

Make errors passthrough to users in api wrapper

---

Backend/Controllers/AudioController.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/FrontierController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/WordController.cs
Backend/Program.cs
Backend/Properties/launchSettings.json
Backend/Services/UserApiServices.cs
Backend/Startup.cs
Backend/appsettings.json
__mocks__/axios.js
package-lock.json
src/backend/index.tsx

In order to test this add `ASPNETCORE_JWT_SECRET_KEY` to your environment variables as `Thisisasecretcode`. I don't know if farmer pickles will like this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/157)

Make secret key (for jwt tokens) an environment variable

---

src/backend/index.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/index.tsx
src/components/GoalTimeline/GoalsActions.tsx
src/components/GoalTimeline/GoalsReducer.tsx
src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
src/components/GoalTimeline/tests/GoalTimelineReducers.test.tsx
src/components/Project/UserProject.ts
src/goals/CharInventoryCreation/CharacterInventoryActions.tsx
src/goals/CharInventoryCreation/tests/CharInventoryActions.test.tsx
src/goals/CreateCharInv/CreateCharInv.tsx
src/goals/CreateStrWordInv/CreateStrWordInv.tsx
src/goals/HandleFlags/HandleFlags.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepActions.test.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MockMergeDupData.ts
src/goals/MergeDupGoal/MergeDups.tsx
src/goals/SpellCheckGloss/SpellCheckGloss.tsx
src/goals/ValidateChars/ValidateChars.tsx
src/goals/ValidateStrWords/ValidateStrWords.tsx
src/goals/ViewFinal/ViewFinal.tsx
src/types/baseGoal.tsx
src/types/goals.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/161)

Char inv goal hookup

---

package-lock.json
package.json
src/store.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/165)

Add redux devtools

---

Backend/Controllers/WordController.cs
Backend/Services/WordApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/167)

Add exception for when sense counts don't match

---

package-lock.json
src/components/GoalTimeline/GoalsReducer.tsx
src/goals/CreateCharInv/CreateCharInv.tsx
src/goals/DefaultGoal/BaseGoalScreen/BaseGoalScreen.tsx
src/goals/DefaultGoal/BaseGoalScreen/DisplayProg/displayProg.tsx
src/goals/DefaultGoal/BaseGoalScreen/DisplayProg/index.tsx
src/goals/DefaultGoal/BaseGoalScreen/DisplayProg/tests/displayProg.test.tsx
src/goals/DefaultGoal/BaseGoalScreen/tests/BaseGoalScreen.test.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
src/goals/MergeDupGoal/MergeDupStep/index.tsx
src/resources/translations.json

This branch also contains edits to the MergeDupStepReducer and GoalsReducer, which we may be able to remove if they prove problematic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/168)

Step progress indicator

---

Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Services/ProjectApiServices.cs
Backend/Services/UserApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/176)

Make update functions return 304 if no changes

---

package-lock.json
src/components/AddWords/AddWordsComponent.tsx
src/components/AddWords/tests/AddWords.test.tsx
src/components/AddWords/tests/__snapshots__/AddWords.test.tsx.snap
src/components/TreeView/TreeDepiction.tsx
src/components/TreeView/TreeViewComponent.tsx
src/components/TreeView/TreeViewHeader.tsx
src/components/TreeView/tests/MockSemanticTree.ts
src/components/TreeView/tests/TreeViewHeader.test.tsx
src/components/TreeView/tests/__snapshots__/TreeDepiction.test.tsx.snap
src/components/TreeView/tests/__snapshots__/TreeViewComponent.test.tsx.snap
src/components/TreeView/tests/__snapshots__/TreeViewHeader.test.tsx.snap
src/resources/tree/intersect.svg
src/resources/tree/leftEndcap.svg
src/resources/tree/parent.svg
src/resources/tree/pillar.svg
src/resources/tree/teeDown.svg
src/resources/tree/teeUpLeft.svg
src/resources/tree/teeUpRight.svg

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/177)

Upgrade tree view ui

---

src/goals/MergeDupGoal/MergeDupStep/MergeStack/MergeStackComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/183)

Make side pane automatically open when adding dup

---

dropDB.bat

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/185)

Add helper script for dropping DB

---

Backend.Tests/ProjectServiceMock.cs
Backend.Tests/UserEditControllerTests.cs
Backend.Tests/UserEditRepositoryMock.cs
Backend.Tests/UserRoleControllerTests.cs
Backend.Tests/UserRoleServiceMock.cs
Backend.Tests/UserServiceMock.cs
Backend/Contexts/UserRoleContext.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/UserRoleController.cs
Backend/Interfaces/IProjectService.cs
Backend/Interfaces/IUserEditService.cs
Backend/Interfaces/IUserRoleContext.cs
Backend/Interfaces/IUserRoleService.cs
Backend/Interfaces/IUserService.cs
Backend/Models/User.cs
Backend/Models/UserRole.cs
Backend/Services/ProjectApiServices.cs
Backend/Services/UserApiServices.cs
Backend/Services/UserEditRepository.cs
Backend/Services/UserRoleApiServices.cs
Backend/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/184)

Add UserRoles API

---

src/components/AppBar/AppBarComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/MergeStackComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/187)

Improve sidebar

---

Backend.Tests/LiftControllerTests.cs
Backend/Services/LiftService.cs
src/components/TreeView/TreeViewComponent.tsx
src/components/TreeView/index.tsx
src/components/TreeView/tests/TreeViewComponent.test.tsx
src/components/TreeView/tests/TreeViewReducer.test.tsx
src/resources/semantic-domains/en.json
src/resources/semantic-domains/es.json
src/resources/semantic-domains/fr.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/190)

Import semantic domains from file

---

Backend/Startup.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/191)

Minor code clean-up

---

package.json

Break points can be placed the same way as frontend code
```javascript
debugger
```
To connect a debugger go to [chrome://inspect](chrome://inspect) and hit inspect on the node instance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/192)

Test debug

---

Backend.Tests/AudioControllerTests.cs
Backend.Tests/UserEditControllerTests.cs
Backend.Tests/WordControllerTests.cs
Backend/Controllers/AudioController.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/FrontierController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/UserRoleController.cs
Backend/Controllers/WordController.cs
Backend/Helper/Secret.cs
Backend/Helper/Utilities.cs
Backend/Interfaces/IWordService.cs
Backend/Models/Project.cs
Backend/Models/User.cs
Backend/Models/UserEdit.cs
Backend/Models/UserRole.cs
Backend/Models/Word.cs
Backend/Services/LiftService.cs
Backend/Services/ProjectApiServices.cs
Backend/Services/UserApiServices.cs
Backend/Services/WordApiServices.cs
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/193)

Backend bigfixes and some doc comments

---

Backend/Services/UserApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/194)

Increase token expiry to 4 hours

---

Backend/Services/PermissionService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/203)

Remove circular dependency

---

Backend/Services/PermissionService.cs

Reverts sillsdev/TheCombine#203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/205)

Revert "Remove circular dependency"

---

seedAdmin.bat

requires environment variable `ASPDOTNET_ADMIN_PASSWORD`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/210)

Add script to add admin to database

---

src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx

The button now triggers the file input regardless of where it's clicked.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/214)

Fix File Upload Button (Project Creation)

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/218)

Fix MergeDupStep rendering with glossless senses

---

Backend.Tests/AudioControllerTests.cs
Backend.Tests/AvatarControllerTests.cs
Backend.Tests/LiftControllerTests.cs
Backend.Tests/ProjectControllerTests.cs
Backend.Tests/UserControllerTests.cs
Backend.Tests/UserEditControllerTests.cs
Backend.Tests/UserRoleControllerTests.cs
Backend.Tests/WordControllerTests.cs

Reverts sillsdev/TheCombine#215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/226)

Revert "Enable parallel tests"

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/228)

Fix displaying senses with one gloss in sidebar

---

src/components/GoalTimeline/DefaultState.tsx

* Code left in so that re-enabling them when they're implemented will be easy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/229)

Disable unused goals

---

package-lock.json
src/components/DataEntry/DataEntryComponent.tsx
src/components/DataEntry/DataEntryTable/DuplicateResolutionView/DuplicateResolutionView.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/239)

Only display glosses for the current language

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/244)

Merge semantic domains when two senses are duplicates

---

Backend/Controllers/FrontierController.cs
Backend/Controllers/LiftController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/248)

Correct paths in comments

---

src/components/GoalTimeline/GoalsActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/249)

Mergedups blacklist

---

Backend/Services/UserApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/254)

Remove user passwords and avatars from return values

---

Backend.Tests/UserServiceMock.cs
Backend/Controllers/AvatarController.cs
Backend/Interfaces/IUserService.cs
Backend/Services/UserApiServices.cs

PR #254 broke avatar download, this is a fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/262)

Fix avatar download

---

Backend/Services/UserApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/264)

Return null string instead of crashing if user is null

---

src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx

* Await the return of dispatch before asserting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/267)

Fix two broken tests of asynchronous methods

---

Backend.Tests/PermissionServiceMock.cs
Backend/Controllers/AudioController.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/FrontierController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/UserRoleController.cs
Backend/Controllers/WordController.cs
Backend/Interfaces/IPermissionService.cs
Backend/Services/PermissionService.cs
src/components/GoalTimeline/GoalsActions.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/270)

Return 403 forbidden when not authorized, return 401 when not authenticated

---

Backend/Controllers/AudioController.cs
Backend/Helper/Utilities.cs
Backend/Services/WordApiServices.cs
package-lock.json
src/backend/index.tsx
src/components/Pronunciations/AudioPlayer.tsx

The play buttons will toggle playing and stopping a recorded audio file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/273)

Play audio on pronunciations component

---

src/components/DataEntry/DataEntryTable/DuplicateResolutionView/tests/DuplicateResolutionView.test.tsx
src/components/ProjectScreen/CreateProject/CreateProjectActions.tsx
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx

* Don't reset the permissions on the current user
to a basic user if the admin clicks on themself
* Also: Fix test that shouldn't have built before
* Add better error handling for users that aren't
actually logged in during CreateProject
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/277)

Fix add user glitch

---

Backend/Startup.cs
src/components/DataEntry/DataEntryTable/DuplicateResolutionView/DuplicateResolutionView.tsx
src/components/DataEntry/DataEntryTable/ExistingEntry/ExistingEntry.tsx
src/components/DataEntry/DataEntryTable/ExistingEntry/tests/ExistingEntry.test.tsx
src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx
src/goals/MergeDupGoal/DuplicateFinder/DuplicateFinder.ts
src/goals/MergeDupGoal/DuplicateFinder/tests/DuplicateFinder.test.ts

* Return multiple duplicates from the frontier
* Display multiple rows if they are found
* Also enhance the add users to project with a
checkbox for users that are added and the avatar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/278)

Allow multiple duplicates in AutoComplete

---

src/components/AppBar/NavigationButtons.tsx
src/components/ProjectSettings/ProjectSettingsComponent.tsx
src/components/TreeView/TreeViewComponent.tsx
src/components/TreeView/TreeViewReducer.ts
src/components/TreeView/tests/TreeViewComponent.test.tsx
src/components/TreeView/tests/TreeViewReducer.test.tsx
src/index.tsx
src/resources/translations.json

* Add approved french translations from Crowdin
* Add french as a language choice
* Use language choice when displaying semantic domains
* Fix a couple of non-localized strings
* Remove the language picker and use browser language
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/281)

Add French translations

---

Backend/Services/WordApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/283)

Fix case problem that prevented Audio playback

---

package-lock.json
package.json
public/index.html
src/components/App/App.test.tsx
src/components/Login/LoginPage/LoginComponent.tsx
src/components/Login/LoginPage/tests/LoginComponent.test.tsx
src/components/ProjectSettings/ProjectSettingsComponent.tsx
src/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/284)

Working Recaptcha on Login screen

---

Backend/Startup.cs

Closes #290 
Closes #291
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/292)

Validate ASPNETCORE_JWT_SECRET_KEY environment variable

---

.gitignore
Backend.Tests/LiftControllerTests.cs
Backend.Tests/PermissionServiceMock.cs
Backend.Tests/ProjectControllerTests.cs
Backend.Tests/UserControllerTests.cs
Backend.Tests/UserRoleControllerTests.cs
Backend.Tests/UserServiceMock.cs
Backend/Controllers/AudioController.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/FrontierController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/UserRoleController.cs
Backend/Controllers/WordController.cs
Backend/Interfaces/IPermissionService.cs
Backend/Models/User.cs
Backend/Models/UserRole.cs
Backend/Services/LiftApiServices.cs
Backend/Services/PermissionService.cs
Backend/Services/UserApiServices.cs
Backend/Startup.cs
README.md
seedAdmin.bat
setAdminUser.bat

Backend portion for #300
Closes #297 
Closes #306 
- Enable `User` DELETE endpoints
- Enable `Project` DELETE all endpoint
- Create `setAdminUser.bat` script to set users as database admins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/303)

Site Admin Endpoints

---

.gitattributes
README.md
package.json
src/components/UserSettings/UserSettings.tsx
src/index.tsx

Create `npm run prettier-check` to enforce that TypeScript code is properly formatted.
This is now enabled on TeamCity CI.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/321)

Create a prettier-check npm script

---

README.md
package-lock.json
package.json
src/backend/localStorage.tsx
src/components/ContextMenu/tests/ContextMenu.test.tsx
src/components/GoalTimeline/GoalSwitcher/GoalSelectorScroll/tests/GoalSelectorScroll.test.tsx
src/components/GoalTimeline/GoalTimelineHorizontal/tests/GoalTimelineHorizontal.test.tsx
src/components/Login/LoginPage/tests/LoginComponent.test.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/TreeView/tests/TreeViewHeader.test.tsx
src/goals/CharInventoryCreation/tests/CharacterInventoryReducer.test.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepActions.test.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MockMergeDupData.ts
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/CellColumns.test.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/tests/ReviewEntriesComponent.test.tsx

Also:
-  Upgrade to semver compatible dependencies via `npm upgrade`. Going any further causes test breakages (#320)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/319)

Add eslint script

---

.editorconfig
Backend.Tests/AudioControllerTests.cs
Backend.Tests/AvatarControllerTests.cs
Backend.Tests/LiftControllerTests.cs
Backend.Tests/ProjectControllerTests.cs
Backend.Tests/UserControllerTests.cs
Backend.Tests/UserEditControllerTests.cs
Backend.Tests/UserRoleControllerTests.cs
Backend.Tests/WordControllerTests.cs
Backend/Controllers/UserEditController.cs
Backend/Models/Project.cs
Backend/Services/LiftApiServices.cs
Backend/Startup.cs
README.md
package.json

From my research, `dotnet-format` is the official formatter supported by Microsoft for C# code: https://github.com/dotnet/format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/322)

Add dotnet-format to auto-format C# project files

---

Backend.Tests/AudioControllerTests.cs
Backend.Tests/AvatarControllerTests.cs
Backend.Tests/Backend.Tests.csproj
Backend.Tests/LiftControllerTests.cs
Backend/BackendFramework.csproj
Backend/Startup.cs
Backend/appsettings.json
README.md

Closes #323
- Bump to C# 8.0 ([expected default for .NET Core 2.1 and 3.1](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/324)

Port backend to .NET Core 3.1

---

src/components/ProjectSettings/ProjectImport/ProjectImport.tsx
src/resources/translations.json

Resolves #272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/332)

Added localization for the Choose File button.

---

README.md

Closes #346
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/347)

Add instructions to enable VS Code format on save

---

Backend.Tests/AudioControllerTests.cs
Backend.Tests/LiftControllerTests.cs
Backend/Controllers/AudioController.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/LiftController.cs
Backend/Helper/FileUtilities.cs
Backend/Services/LiftApiServices.cs
Backend/Services/ProjectApiServices.cs

Closes #295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/341)

Convert Helper.Utilities into a static class

---

Backend/Controllers/ProjectController.cs
Backend/Models/Project.cs

The backend was not sending the field name the frontend was expecting for updating the user in localstorage
closes #316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/386)

Correct field name of user update in backend

---

Backend/Helper/FileUtilities.cs
Backend/Services/LiftApiServices.cs
Backend/Services/WordApiServices.cs

Resolves #294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/404)

Consolidated pathToHome generation.

---

Backend.Tests/ProjectServiceMock.cs
Backend.Tests/UserRoleServiceMock.cs
Backend.Tests/UserServiceMock.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserController.cs
Backend/Controllers/UserRoleController.cs
Backend/Helper/ResultOfUpdate.cs
Backend/Interfaces/IProjectService.cs
Backend/Interfaces/IUserRoleService.cs
Backend/Interfaces/IUserService.cs
Backend/Models/UserRole.cs
Backend/Services/UserApiServices.cs
Backend/Services/UserRoleApiServices.cs

Closes #304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/408)

Move ResultOfUpdate into a common module

---

src/components/Login/AuthHeaders.tsx
src/components/Login/tests/AuthHeaders.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/426)

Add argument to AuthHeaders and make unit tests.

---

src/components/Pronunciations/AudioRecorder.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/428)

Change audio recorder color while recording - UX suggestion

---

Backend.Tests/Backend.Tests.csproj

Closes #429
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/430)

Remove outdated .NET Core 2.2 test dependencies from the backend

---

Backend.Tests/Backend.Tests.csproj

Closes #432
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/433)

Reference the proper web SDK in Backend tests for .NET Core 3.0+

---

.gitignore
README.md
docker-compose.yml
nginx/generate_config.sh
src/types/runtimeConfig.tsx

Closes #431
Addresses the last part of this comment: https://github.com/sillsdev/TheCombine/issues/427#issuecomment-644373042
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/446)

Use identical baseURL in production

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/tests/ReviewEntriesComponent.test.tsx

* modify DataEntryTable to call addWord when
data is present in the NewEntry
* improve DataEntryTable tests to allow verification
* Closes #335
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/444)

Save word data in Data Entry if Complete is clicked

---

src/components/DataEntry/DataEntryTable/tests/DataEntryTable.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/452)

Fix mistakes in unit test comments

---

src/components/SiteSettings/ProjectsExport/ProjectsExport.tsx
src/components/SiteSettings/SiteSettingsComponent.tsx

Fix two compile warnings introduced in pr #310 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/453)

Fix compile warnings.

---

Backend.Tests/ProjectServiceMock.cs
Backend.Tests/UserRoleControllerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/475)

Increase UserRoleController unit test coverage

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/517)

Update README prefixes ASPNETCORE_ -> COMBINE_

---

Backend/Controllers/ProjectController.cs
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx
src/components/ProjectSettings/ProjectUsers/UserList.tsx

Resolves #528
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/538)

Fix bug in adding user to a project

---

src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/Login/RegisterPage/tests/RegisterComponent.test.tsx
src/resources/translations.json
src/utilities.tsx

Resolves #525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/527)

Require usernames to be at least 3 characters long.

---

Backend/Controllers/UserController.cs
src/backend/index.tsx
src/components/SiteSettings/SiteSettingsComponent.tsx
src/components/SiteSettings/UserManagment/ConfirmDeletion.tsx
src/components/SiteSettings/UserManagment/UserList.tsx
src/components/SiteSettings/UserManagment/UserManagment.tsx
src/resources/translations.json

Allows Site Admin to view and delete users. It provides a Modal to confirm its deletion. In a later pull request, we should probably provide a page for the Admin to edit details of all the users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/539)

Site Settings User List

---

src/backend/localStorage.tsx
src/components/AppBar/UserMenu.tsx
src/components/Login/LoginActions.tsx
src/components/UserSettings/AvatarUpload.tsx
src/components/UserSettings/UserSettings.tsx

Uses Local Storage to store Avatar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/553)

Avatar Errors

---

.vscode/launch.json
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/561)

Add configuration to debug jest in vscode

---

src/components/DataEntry/DataEntryTable/GlossWithSuggestions/GlossWithSuggestions.tsx
src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/580)

Improve visual of gloss in DataEntry > ExistingEntry

---

src/components/BaseSettings/BaseSettingsComponent.tsx
src/components/ProjectSettings/ProjectSettingsComponent.tsx
src/components/ProjectSettings/ProjectUsers/ActiveUsers.tsx
src/components/ProjectSettings/ProjectUsers/index.tsx
src/resources/translations.json

Resolves #572
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/584)

[ProjectSettings] Add ActiveUser list; Enable show/hide sections

---

src/components/UserSettings/UserSettings.tsx

Closes #589
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/590)

Fix user's phone number showing up as their name in the project settings

---

Backend/Dockerfile
docker-compose.yml

Closes #514
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/591)

Run backend process as non-root user in Docker container

---

src/components/DataEntry/ExistingDataTable/ExistingDataTable.tsx
src/components/DataEntry/ExistingDataTable/ImmutableExistingData/ImmutableExistingData.tsx
src/types/word.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/593)

Check for empty glosses

---

src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx

When selected a random sense of a random word, skip words without any senses
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/613)

[MergeDupStepReducer.test] Fix sporadically failing tests

---

src/components/DataEntry/DataEntryTable/VernWithSuggestions/VernWithSuggestions.tsx

Resolves #530 
Resolves #536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/616)

[VernWithSuggestions] Limit how much different suggestions can be from what is typed

---

src/components/Login/LoginPage/LoginComponent.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell/DeleteCell.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteWordDialog.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
src/resources/translations.json

Don't allow saving words with all senses deleted.
Popup confirmation dialog for deleting an entry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/617)

[ReviewEntries] Alerts when deleting words

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/DataEntryTable/VernWithSuggestions/SenseDialog/SenseDialog.tsx
src/components/DataEntry/DataEntryTable/VernWithSuggestions/VernDialog/VernDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/619)

Hide deleted senses in data entry

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/DataEntryTable/VernWithSuggestions/SenseDialog/SenseDialog.tsx
src/components/DataEntry/DataEntryTable/VernWithSuggestions/VernDialog/VernDialog.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTypes.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/624)

[ReviewEntries] Remove deleted senses from a word when saving to backend

---

src/components/PasswordReset/RequestPage/component.tsx

Resolves one part of #537
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/625)

[PasswordReset] Only check if email exists on submit

---

package-lock.json
package.json

Unintentionally placed in dependencies instead of devDependencies in #626
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/640)

Move @types/nspell from deps to devDeps

---

Backend.Tests/LiftControllerTests.cs
Backend/Services/LiftApiServices.cs

* Exclude non-active senses during the export
* Minor code clean-up
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/643)

Do not export deleted senses

---

Backend.Tests/AudioControllerTests.cs

Resolves #654
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/655)

Stop AudioControllerTests setup from deleting .CombineFiles

---

package-lock.json

I believe this update was accidentally missed in #649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/661)

Sync up @types/recordrtc package-lock.json with npm install

---

Backend/Services/WordApiServices.cs

Resolves #670
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/673)

Initialize sense indices in correct place

---

Backend/Contexts/EmailContext.cs
Backend/Controllers/AudioController.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/WordController.cs
Backend/Helper/FileUtilities.cs
Backend/Interfaces/IWordService.cs
Backend/Models/Project.cs
Backend/Models/User.cs
Backend/Models/UserEdit.cs
Backend/Models/UserRole.cs
Backend/Models/Word.cs
Backend/Services/LiftApiServices.cs
Backend/Services/ProjectApiServices.cs
Backend/Services/UserApiServices.cs
Backend/Services/WordApiServices.cs
Backend/Services/WordRepository.cs
Backend/Startup.cs

- Use `await` properly in a few places it was missing
- Use string interpolation
- Elide `this` usage
- Remove redundant parenthesis
- Use `var` type inference
- Use `switch` to simplify `if`/`else` chain
- Fix inconsistent naming
- Make several methods `static` to simplify scope
- Simplify several `return` expressions
- Remove unused imports
- Mark several items `private`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/671)

Refactor several backend modules

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/680)

[DataEntryTable] Don't update frontier if a previous update is still in progress

---

src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx
src/components/TreeView/TreeViewHeader.tsx
src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx
src/goals/CharInventoryCreation/components/CharacterList/CharacterListComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/MergeRowComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeStack/MergeStackComponent.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesComponent.tsx

* Remove unused states
* Avoid potentially inconsistent state updates
* Switch from `<Translate...` to `this.props.translate(...` to avoid duplicate ids 
* Sort imports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/674)

Fix frontend LGTM warnings

---

src/components/ProjectSettings/ProjectSettingsComponent.tsx

Resolves #663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/678)

Remove depricated componentWillMount from ProjectSettings

---

README.md

Add LGTM badges to README to encourage high code quality
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/686)

Add LGTM badges to README

---

Backend.Tests/LiftControllerTests.cs
Backend/Controllers/LiftController.cs
Backend/Interfaces/ILiftService.cs
Backend/Services/LiftApiServices.cs
Backend/Services/WordApiServices.cs
Backend/Services/WordRepository.cs
Backend/Startup.cs

* Add and use ILiftService interface
* Also set date created/modified when
words are added/edited
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/679)

Make LiftService a true transient service

---

src/components/DataEntry/spellChecker.ts

Resolves the first part of #487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/718)

Handle multi-word glosses

---

README.md
package-lock.json
package.json

Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/726)

Add localization, license, contributors badges

---

src/components/Temp/TempComponent.tsx

- Remove unused component state
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/729)

Fix frontend LGTM issue

---

src/components/ProjectSettings/ProjectName/ProjectName.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/731)

Don't reference this.props within this.SetState

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/734)

Release version 0.3.0

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/735)

Bump to 0.3.1-alpha.0

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
README.md
src/components/ProjectSettings/ProjectName/ProjectName.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/733)

Enable GitHub Actions CI

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
README.md
package.json

Closes #737
You can view the combined coverage report here for this PR: https://codecov.io/gh/sillsdev/TheCombine/pull/739/tree
> Note: The README badges will not show coverage % until this has been merged into master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/739)

Add Codecov integration

---

src/components/BaseSettings/BaseSettingsComponent.tsx
src/components/ContextMenu/ContextMenu.tsx
src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/PasswordReset/RequestPage/component.tsx
src/components/PasswordReset/ResetPage/component.tsx
src/components/ProjectScreen/ChooseProject/ChooseProjectComponent.tsx
src/components/ProjectSettings/ProjectName/ProjectName.tsx
src/components/ProjectSettings/ProjectSwitch/ProjectSwitch.tsx
src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx
src/components/ProjectSettings/ProjectUsers/UserList.tsx
src/components/SiteSettings/ProjectManagement/ProjectManagement.tsx
src/components/SiteSettings/UserManagment/UserManagment.tsx
src/components/TreeView/TreeDepiction.tsx
src/components/TreeView/TreeViewHeader.tsx
src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx
src/goals/CharInventoryCreation/components/CharacterEntry/CharacterEntryComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx

Per https://lgtm.com/rules/1819283066/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/740)

In setState, use (prevState, props) where appropriate

---

.github/workflows/python.yml

[Python 3.9 released Oct 5, 2020](https://www.python.org/dev/peps/pep-0596/#schedule).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/753)

Support Python 3.9

---

Backend.Tests/Controllers/ProjectControllerTests.cs
Backend.Tests/Models/ProjectTests.cs
Backend/Models/Project.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/750)

Improve backend test coverage of Project

---

.github/workflows/backend.yml
Backend/Controllers/ProjectController.cs

Ensure that backend code passes `dotnet-format` in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/758)

Run dotnet-format in CI

---

Backend/Services/LiftApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/761)

On lift import, preserve entry guids

---

package-lock.json
package.json

Update version number to release patch to live server.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/762)

Bump version to 0.3.1 to release fix to LIFT import

---

package-lock.json
package.json

Set TheCombine version to 0.3.2-alpha.0 for future commits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/763)

Set Version to 0.3.2-alpha.0

---

Backend.Tests/Controllers/LiftControllerTests.cs

Unit test for #761.
Fails in `master` before that merge and passes after.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/764)

Test LIFT round trip Guid

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/771)

Add note that sudo is required for docker commands on Linux

---

Backend.Tests/Controllers/LiftControllerTests.cs
Backend/Models/Word.cs
Backend/Services/LiftApiServices.cs

The `Sense` follow-up to #761 and #764 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/774)

Preserve sense guids

---

Backend/Services/LiftApiServices.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/773)

Move MergeInNote out of area for unused functions

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/775)

Bump version to 0.4.0 to release note field

---

package-lock.json
package.json

Increment software version for next development cycle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/776)

Bump version to 0.4.1-alpha.0

---

package-lock.json
package.json

Update version string for Release 0.5.0 which adds
- Notes field in data entry
- Performance improvements - non-blocking audio processing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/792)

Release 0.5.0

---

package-lock.json
package.json

Set version to 0.5.1-alpha.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/793)

Set version string for development of next release.

---

src/components/ProjectSettings/ProjectExport/ExportProjectButton.tsx

Resolves #798
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/799)

Add download attribute to export <a> tag

---

Backend/Controllers/LiftController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/801)

Force garbage collection at end of ExportLiftFile()

---

src/backend/index.tsx
src/components/ProjectSettings/ProjectExport/ExportProjectButton.tsx
src/tests/utilities.test.ts
src/utilities.tsx

Resolves #596
Resolves #646 (but with name generated in frontend, rather than the one generated in the backend)
Format: projectName_YYYY-MM-DD_hh-mm-ss.zip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/800)

Project export filename projectName_date_time

---

src/components/Login/LoginActions.tsx
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx
src/components/SiteSettings/UserManagment/UserManagment.tsx

Resolves #697
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/797)

[Login, UserManagement] Avoid avatar 404 error

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/816)

Add Markdown link to Docker deployment docs

---

package-lock.json
package.json

Set version to 0.6.0 to include the following PRs:
- Refactor temporary files generated by backend (#810)
- Add liftImported field to existing projects (#815)
- ExportProject actions/reducer/state (#812)
- Add Markdown link to Docker deployment docs (#816)
- Centralize the AppBar; Remove extraneous component wrappers (#807)
- Remove GC.Collect() call that did not have any noticeable improvement for memory usage (#813)
- Add explicit default formatters by language (#808)
- Set cache expiration so that if the server's frontend implementation is updated (#809)
- NewEntry note (#802)
- Consolidate navigation paths; Cleanup GoalTimeline folder structure (#805)
- [Login, UserManagement] Avoid avatar 404 error (#797)
- Modify TreeView search's event handler to preempt material-table's (#804)
- …

Update version number to 0.6.0

---

README.md
dev-requirements.txt

- Update Python dev dependencies
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/821)

Update Python dev dependencies

---

nginx/templates/thecombine.conf.template

Fix typo from #809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/824)

Fix typo in NGINX configuration

---

package-lock.json
package.json

Late update to version for development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/827)

Bump version to 0.6.0-alpha.0

---

src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx

Fixes #835
SenseDialog did not correctly update the gloss when a selection was made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/837)

Completely update gloss in NewEntry's state.

---

package-lock.json
package.json
src/components/App/App.test.tsx
src/components/GoalRoute/tests/component.test.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/841)

Update App, GoalRoute testing

---

src/backend/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/842)

Remove unused and redundant DeleteWord function.

---

Backend.Tests/Controllers/AvatarControllerTests.cs
Backend.Tests/Controllers/LiftControllerTests.cs
Backend.Tests/Mocks/PasswordResetContextMock.cs
Backend.Tests/Mocks/PasswordResetServiceMock.cs
Backend.Tests/Mocks/PermissionServiceMock.cs
Backend.Tests/Mocks/ProjectServiceMock.cs
Backend.Tests/Mocks/UserEditRepositoryMock.cs
Backend.Tests/Mocks/UserServiceMock.cs
Backend.Tests/Mocks/WordRepositoryMock.cs
Backend/Contexts/PasswordResetContext.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Helper/FileStorage.cs
Backend/Helper/Sanitization.cs
Backend/Services/UserApiServices.cs
Backend/Services/WordApiServices.cs

Closes #656
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/851)

Delete files generated during backend unit tests

---

Backend.Tests/Controllers/LiftControllerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/854)

Convert Lift roundtrip testing from [Test] with `foreach` to [TestCase...].

---

src/goals/ReviewEntries/ReviewEntriesComponent/tests/ReviewEntriesComponent.test.tsx

`npm run test-frontend -- tests/ReviewEntriesComponent` passes its tests but gives a console warning:
``` console.error node_modules/react-dom/cjs/react-dom.development.js:88
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
in ReviewEntriesComponent (created by Context.Consumer)
in LocalizedComponent (at ReviewEntriesComponent.test.tsx:81)
in Provider (at ReviewEntriesComponent.test.tsx:80)
```
Upgrading from `react-dom` to `react-test-renderer` eliminated that warning, but triggered a new one (possibly the original problem): the mock for `material-table` was not creating satisfactory `children` for its …

Update ReviewEntriesComponent testing

---

package-lock.json
package.json

Belated update of version number to 0.6.1-alpha.0 for development work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/867)

Update version to 0.6.1-alpha.0

---

README.md

Related to #871
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/873)

Update README to cover macOS setup instructions

---

src/components/UserSettings/AvatarUpload.tsx
src/components/UserSettings/UserSettings.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/877)

[UserSettings] Fix 'save' text.

---

Backend.Tests/Backend.Tests.csproj
Backend.Tests/Controllers/AudioControllerTests.cs
Backend.Tests/Controllers/AvatarControllerTests.cs
Backend.Tests/Controllers/LiftControllerTests.cs
Backend.Tests/Controllers/ProjectControllerTests.cs
Backend.Tests/Controllers/UserControllerTests.cs
Backend.Tests/Controllers/UserEditControllerTests.cs
Backend.Tests/Controllers/UserRoleControllerTests.cs
Backend.Tests/Controllers/WordControllerTests.cs
Backend.Tests/Mocks/EmailServiceMock.cs
Backend.Tests/Mocks/PasswordResetContextMock.cs
Backend.Tests/Mocks/ProjectServiceMock.cs
Backend.Tests/Mocks/UserServiceMock.cs
Backend.Tests/Services/PasswordResetServiceTests.cs
Backend/Controllers/FrontierController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/UserRoleController.cs
Backend/Controllers/WordController.cs
Backend/Interfaces/ILiftService.cs
Backend/Interfaces/IProjectService.cs
Backend/Services/LiftApiServices.cs
Backend/Services/ProjectApiServices.cs

Closes #850
Follow on planned in #882 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/881)

Use nullable compiler option for backend test project

---

src/components/AppBar/UserMenu.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/887)

[UserMenu] Close when selection is made.

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx

Resolves #898
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/899)

[DataEntryTable] In getProjectSettings, add check for undefined/null.

---

Backend.Tests/Mocks/UserServiceMock.cs
Backend/Controllers/UserController.cs
Backend/Helper/ResultOfUpdate.cs
Backend/Interfaces/IUserService.cs
Backend/Services/UserApiServices.cs
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/UserSettings/UserSettings.tsx

Backend | UserServices: Check for empty or duplicate email or username in Create and Update.
Frontend | UserSettings: When email is taken, use red box instead of alert.
Resolves #894
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/900)

Add email/username checking to Create/Update in UserServices

---

src/goals/MergeDupGoal/DuplicateFinder/DuplicateFinder.ts
src/goals/MergeDupGoal/DuplicateFinder/tests/DuplicateFinder.test.ts

Resolves #601
Resolves #603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/901)

Sort possible duplicates alphabetically, not by score.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/905)

Update version to 0.6.2-alpha.0

---

package-lock.json
package.json

Set version to 0.6.2 to release to production.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/910)

Set version for release 0.6.2

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/911)

Create version 0.6.3-alpha.0 for development work

---

src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesReducer.tsx

Resolve #917
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/918)

Add StoreActions.RESET to ReviewEntriesReducer.

---

src/components/GoalTimeline/GoalsActions.tsx
src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
src/types/goalUtilities.tsx
src/types/goals.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/919)

Seperate goal utilities.

---

src/components/Project/ProjectActions.tsx
src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx
src/components/ProjectSettings/ProjectLanguages/index.tsx
src/components/ProjectSettings/ProjectLanguages/tests/ProjectLangauges.test.tsx
src/components/ProjectSettings/ProjectName/ProjectName.tsx
src/components/ProjectSettings/ProjectName/index.tsx
src/components/ProjectSettings/ProjectSettingsComponent.tsx
src/components/ProjectSettings/index.tsx
src/goals/CharInventoryCreation/CharacterInventoryActions.tsx

Extract a project-specific function from CharacterInventoryActions.tsx (that updates a project in both state and database) and use in various places (some that only updated one but not both).
As a side effect, resolves #920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/921)

Make saveChangesToProject a more general project function.

---

src/components/GoalTimeline/GoalsActions.tsx
src/components/GoalTimeline/tests/GoalTimelineActions.test.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/index.tsx

Move goal-general functions to GoalActions, merge-specific functions to MergeDupStepActions.
A follow-up pr is needed to work the bugs out of these goal-general functions and make sure they are generally useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/922)

Goal-MergeDups function exchange

---

dev-requirements.txt

Upgrade all Python dependencies.
Updates of note:
- `mypy 0.800` used for type checking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/928)

Upgrade Python dependencies

---

src/components/AppBar/AppBarComponent.tsx
src/components/ProjectExport/DownloadButton.tsx

Fixes #938. Makes the download button white in the AppBar.
Helps with #937. Makes the download button blue next to the blue export button.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/939)

Download button color

---

src/components/ProjectExport/DownloadButton.tsx
src/index.tsx

Fixes #942 
Fixes #949
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/950)

Allow country-specific language codes from browser.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/971)

Update version to 0.6.3

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/973)

Update version to 0.6.4-alpha.0.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/980)

Update version to 0.6.4.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/982)

Set development version 0.6.5-alpha.0

---

lgtm.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/983)

Exclude spelling dictionaries from lgtm analysis

---

Dockerfile
README.md

Closes #998
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1000)

Upgrade to Node 14 LTS

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx

Resolves #1002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1003)

Replace manual formatting with Grid

---

src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTable.tsx

Fixes #1017
Use same format as CreateCharacterInventory title.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1018)

[ReviewEntries] Format title.

---

deploy/host_vars/thecombine.app.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1024)

Correct reCAPTCHA site key for thecombine.app

---

deploy/roles/combine_maintenance/files/add_user_to_proj.py
deploy/roles/combine_maintenance/files/maint_utils.py
deploy/roles/combine_maintenance/files/make_user_admin.py
deploy/roles/combine_maintenance/files/rm_project.py
tox.ini

Closes #1039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1040)

Enable Python type checking in deploy/roles

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1042)

Set version to 0.6.5

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1043)

Bump version to 0.6.6-alpha.0.

---

package-lock.json
package.json

Follow-up to #1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1044)

Bump version to 0.6.6

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1046)

Bump version to 0.6.7-alpha.0

---

deploy/roles/docker_install/tasks/main.yml
deploy/vars/packages.yml

Also, bump the following versions:
- docker-compose: 1.28.4
- aws-cli: 2.1.28
Closes #562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1048)

Allow upgrades to docker-compose

---

src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesReducer.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/index.tsx

Follow-up to #1033
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1052)

Cut out leftover language stuff.

---

Backend.Tests/Mocks/WordRepositoryMock.cs
Backend/Controllers/LiftController.cs
Backend/Interfaces/ILiftService.cs
Backend/Interfaces/IWordRepository.cs
Backend/Services/LiftApiServices.cs
Backend/Services/WordRepository.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1054)

Use InsertManyAsync() on import to reduce connections to mongo.

---

package-lock.json
package.json

To release fix to importing large files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1059)

Bump version to 0.6.7.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1058)

Fix typo and formatting in README

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1060)

Bump version to 0.6.8-alpha.0.

---

Backend/Services/LiftApiServices.cs

Add documentation for #1064
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1066)

Document that FinishEntry cannot be marked async

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1067)

Bump version to 0.6.8.

---

Backend.Tests/Backend.Tests.csproj
Backend/BackendFramework.csproj
Backend/Dockerfile

Closes #471 
Closes #927
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1057)

Upgrade upstream SIL dependencies to 8.0.0

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1068)

Bump to dev version 0.6.9-alpha.0.

---

Backend.Tests/Controllers/LiftControllerTests.cs
Backend/Controllers/LiftController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1069)

Remove try-catch that's masking errors.

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupsTree.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1073)

Merge reducer cleanup.

---

src/backend/index.tsx
src/components/GoalTimeline/GoalsActions.tsx
src/components/ProjectSettings/ProjectUsers/UserList.tsx
src/components/TreeView/TreeViewHeader.tsx
src/goals/CharInventoryCreation/CharacterInventoryActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepReducer.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupsTree.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/MergeRowComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/MergeStack.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeRow/index.tsx
src/goals/MergeDupGoal/MergeDupStep/index.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepActions.test.tsx
src/goals/MergeDupGoal/MergeDupStep/tests/MergeDupStepReducer.test.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
src/types/word.tsx

Mostly superficial changes, with some minor refactoring of:
- `MergeDupStepActions` > `mergeWord()`
- `MergeDupStepComponent` > `renderSideBar()`
- `MergeDupStepReducer` > `getRandomRef()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1075)

Cleanup 'id' variable names; let -> const where appropriate.

---

README.md

Add details for how to view the logs of a single service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1080)

Add instructions to view log of single service

---

deploy/bin/clean_repo.py

Test should not fail if keep_pattern is not defined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1083)

Fix test of keep_pattern

---

src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesActions.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/tests/ReviewEntriesActions.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1089)

[ReviewEntries] Don't require semantic domains.

---

src/components/UserSettings/UserSettings.tsx
src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DragSense.tsx
src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DropWord.tsx
src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx
src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/SidebarDragSense.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepActions.tsx
src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx
src/types/goalUtilities.tsx

This is a temporary holdover for the duplicate finder algorithm to be refactored and moved to the backend.
Progress toward #594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1102)

[MergeDups] Duplicate candidates: more similar first, more at a time

---

package-lock.json
package.json

For after release 0.6.9.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1103)

Bump version to 0.6.10-alpha.

---

src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
src/components/ProjectSettings/ProjectImport/ProjectImport.tsx
src/components/UserSettings/UserSettings.tsx
src/goals/CharInventoryCreation/components/CharacterDetail/CharacterInfo.tsx
src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx
src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/DropWord.tsx
src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1106)

Add missing translates.

---

src/browserHistory.ts
src/components/AppBar/UserMenu.tsx
src/components/Login/LoginPage/LoginComponent.tsx

Fixes #1104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1109)

Fix link to User Guide

---

src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx

Fixes #863
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1110)

Fix console warning by inverting typography and grid nesting.

---

deploy/roles/combine_maintenance/files/add_user_to_proj.py
deploy/roles/combine_maintenance/files/aws_backup.py
deploy/roles/combine_maintenance/files/combine_app.py
deploy/roles/combine_maintenance/files/combine_restore.py

Python code improvements from John's comments from PR #1091.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1113)

Python code improvements

---

Backend/Controllers/InviteController.cs
Backend/Controllers/UserController.cs
Backend/Models/User.cs

Closes #1123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1124)

Fix email invite and password reset features

---

Backend/Controllers/InviteController.cs
Backend/Services/InviteService.cs
src/backend/index.tsx
src/browserHistory.ts
src/components/ProjectInvite/ProjectInviteComponent.tsx
src/types/invite.ts

Closes #1118
- Fix frontend routing for invite links
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1122)

Fix email invite logic

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1128)

Bump version to 0.6.10

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1129)

Version 0.6.11-alpha.0.

---

package-lock.json
package.json
src/backend/index.tsx

Closes #1121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1133)

Integrate http-status-codes package

---

README.md

Fix link target
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1143)

Fix link to production docs from README

---

package-lock.json
package.json

Bump version to 0.7.1-alpha.0 for development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1153)

Bump to version 0.7.1-alpha.0

---

dev-requirements.in
dev-requirements.txt

Revert regression in #1157 related to upstream Jinja2 major release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1159)

Revert Jinja2 to < 3.x

---

README.md

Fix some broken links in the README
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1163)

Fix Chocolatey README links

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1166)

Release 0.7.1

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1167)

Version 0.7.2-alpha.0.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1168)

Fix Markdown table of contents link in README

---

README.md

Encourage new contributors/developers to target Ubuntu 20.04. This makes sure the Python version is new enough for what we currently support without extra steps needed to install a new version of Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1169)

Recommend Ubuntu 20.04 for Linux development

---

README.md

Added note on which portions of the readme can be skipped for new development members
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1184)

Small README note

---

src/components/Login/Redux/LoginActions.tsx

Fixes #1186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1187)

Have successful register auto-login.

---

src/components/DataEntry/DataEntryTable/NewEntry/VernDialog.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/CellColumns.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/DeleteCell.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/GlossCell.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/CellColumns.test.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/CellComponents/tests/GlossCell.test.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTable.tsx

Resolves #1188
Fixes #1192 (by disabling dragging)
Fixes #1195 
Before:
After:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1191)

Implement Senses column in ReviewEntriesTable.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1207)

Add git tutorial link to Learn More.

---

Backend.Tests/Backend.Tests.csproj
Backend/BackendFramework.csproj
docs/user_guide/docs/licenses/backend_licenses.txt

Closes  #1203
Follow on to #1198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1215)

Update backend dependencies

---

src/goals/CharInventoryCreation/Redux/CharacterInventoryReduxTypes.ts

Resolves #1240 
Fixes regression from #1117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1241)

Revert CharacterInventoryType.RESET string.

---

.vscode/launch.json

Like #391, but for debugging after the switch to .NET 5.0 (#1198).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1245)

Update launch.json .NET folder 3.1 -> 5.0.

---

Backend.Tests/Helper/DuplicateFinderTests.cs
README.md
docs/user_guide/docs/dataEntry.md
docs/user_guide/docs/project.md
src/components/TreeView/TreeDepiction.tsx

Follow-up to #1242 and #1244
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1246)

Add unit test; Use em-dash; Replace one-liner ifs.

---

package-lock.json
package.json

Prepare version for Release 0.7.2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1266)

Bump version to 0.7.2

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1268)

Bump version to 0.7.3-alpha.0.

---

Backend/Controllers/UserController.cs
src/api/api/user-api.ts
src/backend/index.ts
src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx
src/components/ProjectSettings/ProjectUsers/ProjectUsers.tsx

Closes #1224
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1275)

Automatically add registered users to project if invited by email

---

src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1279)

Update slogan on landing page.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1280)

Bump to version 0.7.3.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1281)

Bump version to 0.7.4-alpha.0

---

src/components/AppBar/UserMenu.tsx
src/components/Project/ProjectActions.ts
src/components/ProjectScreen/ProjectScreenComponent.tsx
src/components/ProjectScreen/tests/ProjectScreenComponent.test.tsx

Fixes #1287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1288)

Fix dispatch, localStorage elements of clearing current project.

---

Backend.Tests/Models/EmailInviteTests.cs
Backend/Models/EmailInvite.cs
src/api/api/user-role-api.ts
src/api/models/email-invite.ts

Also update OpenApi for this change and for #1253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1284)

Remove unnecessary EmailInvite.Id.

---

src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx

Fix bug introduced in #1275.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1290)

Fix email invite.

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1293)

Bump to version 0.7.4

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1294)

Bump version to 0.7.5-alpha.0

---

.github/workflows/backend.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1292)

Add failure logs to the artifacts if CodeQL fails

---

src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx
src/components/ProjectSettings/ProjectImport/ProjectImport.tsx
src/resources/translations.json

Resolves #1267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1302)

Update upload format instructions.

---

src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1318)

Add 'The' before 'Combine'.

---

docs/user_guide/docs/licenses/frontend_licenses.txt

Run `npm run license-report-frontend` to update our frontend license report.
Follow on to #1291 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1315)

Update frontend license report

---

deploy/roles/combine_maintenance/defaults/main.yml
deploy/roles/combine_maintenance/templates/combine-backup-job.j2
deploy/roles/combine_maintenance/templates/combine-clean-aws.j2
deploy/roles/k8s_config/templates/cronjob-daily-backup.yaml.j2
deploy/roles/k8s_config/templates/env-maintenance-configmap.yaml.j2
maintenance/scripts/combine-clean-aws.sh

Fixes 2 issues with the backup process:
- Removes the clean up of files in the backend - it is no longer needed, Closes #1325 
- Fixes the cleanup of old backups in AWS S3 - the filter to select the backups to be cleaned up was not selective enough. Closes #1348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1349)

Fix backup issues

---

src/components/Pronunciations/AudioPlayer.tsx
src/components/Pronunciations/RecorderIcon.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1351)

Move tooltip above record and play icons

---

src/components/AppBar/UserMenu.tsx

Added margin styling to the avatar component to create space between the username text and the avatar.
Closes #1234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1354)

Added padding between username text and avatar

---

src/components/Buttons/EditTextDialog.tsx
src/components/DataEntry/DataEntryTable/EntryCellComponents/EntryNote.tsx

Closes #1295
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1353)

Autofocus the note text field when add note is clicked in new entry

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1362)

Bump version to 0.7.6-alpha.0

---

Backend.Tests/Controllers/AudioControllerTests.cs
Backend.Tests/Controllers/UserControllerTests.cs
Backend.Tests/Mocks/MergeBlacklistRepositoryMock.cs
Backend.Tests/Mocks/PermissionServiceMock.cs
Backend.Tests/Mocks/ProjectRepositoryMock.cs
Backend.Tests/Mocks/UserRepositoryMock.cs
Backend.Tests/Mocks/UserRoleRepositoryMock.cs
Backend.Tests/Models/MergeWordsTests.cs
Backend.Tests/Models/ProjectTests.cs
Backend.Tests/Models/UserEditTests.cs
Backend.Tests/Util.cs
Backend/Controllers/UserController.cs
Backend/Interfaces/IMergeService.cs
Backend/Models/EmailInvite.cs
Backend/Models/MergeWords.cs
Backend/Models/Project.cs
Backend/Models/Word.cs
Backend/Repositories/WordRepository.cs
Backend/Services/LiftService.cs
Backend/Services/WordService.cs

Refactor backend and clean up the following items:
- Remove unused imports
- Remove redundant parenthesis
- Remove unused methods
- Relax target-type new usage (introduced in #1232) to avoid cases were return value type inference was used, which is not always obvious
- Use target-type new where appropriate (on variable declarations where type is already written on the left)
- Reduce nesting / cognitive load by using early return on some methods
- Make some values `readonly` or `const` where appropriate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1372)

Refactor Backend

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/ProjectInvite/ProjectInviteComponent.tsx
src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx
src/components/Pronunciations/PronunciationsComponent.tsx

Consistently use the same style to import the `backend` API helper methods.
```ts
import * as backend from "backend";
```
Rather than:
```ts
import * as Backend from "backend";
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1373)

Use consistent import style for backend module

---

.github/workflows/frontend.yml

Closes #1371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1378)

Unpin NodeJS in GitHub Actions

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1380)

Bump to version 0.7.6

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1381)

Bump to version 0.7.7-alpha.0

---

deploy/hosts.yml

Disable the Captcha for the qa server to enable automated DBV.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1384)

Disable captcha for qa server

---

Backend.Tests/Controllers/LiftControllerTests.cs
Backend.Tests/Models/MergeWordsTests.cs
Backend/Controllers/AvatarController.cs
Backend/Controllers/LiftController.cs
Backend/Helper/FileStorage.cs
Backend/Repositories/UserRepository.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1383)

Minor backend cleanup

---

src/backend/index.ts
src/components/GoalTimeline/Redux/GoalActions.ts
src/components/Login/LoginPage/LoginComponent.tsx
src/components/Login/RegisterPage/RegisterComponent.tsx
src/components/PasswordReset/tests/ResetPage.test.tsx
src/components/Pronunciations/tests/Pronunciations.test.tsx
src/goals/CharInventoryCreation/Redux/CharacterInventoryActions.ts
src/goals/CharInventoryCreation/components/CharacterDetail/CharacterInfo.tsx
src/goals/CreateCharInv/CharInvComponent/CharInvCompleted.tsx

Fix spelling typos within the frontend source folder
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1386)

Fix frontend spelling typos

---

src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/DataEntryTable/EntryCellComponents/GlossWithSuggestions.tsx
src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
src/components/DataEntry/DataEntryTable/NewEntry/tests/NewEntry.test.tsx
src/components/DataEntry/DataEntryTable/RecentEntry/RecentEntry.tsx
src/components/DataEntry/DataEntryTable/RecentEntry/tests/RecentEntry.test.tsx

Resolves #1332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1454)

Use project languages for DataEntry input labels

---

Backend.Tests/Controllers/LiftControllerTests.cs
Backend.Tests/Controllers/WordControllerTests.cs
Backend.Tests/Helper/FileStorageTests.cs
Backend.Tests/Models/MergeWordsTests.cs

Increase backend test coverage
- `MergeUndoId` model
- `FileStorage` ID sanitization
- `LiftService`  export with invalid Project ID
- `WordController` permissions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1462)

Increase backend unit test coverage

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1475)

Release version 0.7.9

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1476)

Bump version to 0.7.10-alpha.0

---

docs/user_guide/docs/dataEntry.md

Document #1464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1477)

Document automatic insertion of . between domain digits

---

src/backend/index.ts
src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx
src/components/ProjectSettings/ProjectSettingsComponent.tsx
src/components/ProjectSettings/ProjectUsers/AddProjectUsers.tsx
src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx
src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx
src/components/Pronunciations/AudioRecorder.tsx
src/components/Pronunciations/Recorder.ts
src/components/Pronunciations/tests/__snapshots__/Pronunciations.test.tsx.snap
src/components/SiteSettings/UserManagement/ConfirmDeletion.tsx
src/components/SiteSettings/UserManagement/UserManagement.tsx
src/components/Toast/SwalToast.ts
src/components/Toast/UpperRightToastContainer.tsx
src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceActions.ts
src/resources/translations.json

Closes #1387 
- Update calls to `toast()` to explicit `toast.success()` and `toast.error()` to automatically provide a more clearer icon/color to user
- To see the difference, see: https://fkhadra.github.io/react-toastify/introduction/
- Add missing Toast to failed microphone access and several other components
- Add SWAL alerts to errors in TypeScript files outside of the React JSX tree
- Consolidate repeated `ToastContainer` definitions into a shared component
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1484)

Improve unexpected error handling in frontend

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1486)

Release version 0.7.10

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1487)

Bump version to 0.7.11-alpha.0

---

.github/actions/combine-build/action.yml
.github/actions/combine-deploy-update/action.yml
.github/workflows/deploy_live.yml
.github/workflows/deploy_qa.yml

Create GitHub actions to build and deploy _The Combine_ to QA and Live servers.  The QA Server is updated with each update of the `master` branch; the Live server is updated with each update of the `live` branch.
Closes #1092
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1490)

Create GitHub Actions to deploy The Combine

---

src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx

Fixes #1337
Fixes #1493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1499)

CreateProject file-selector: Move above lang pickers; Add clear button

---

src/components/DataEntry/DataEntryComponent.tsx

Use immutable `const` bindings in `DataEntryComponent` to make code easier to understand.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1503)

Use immutable bindings in DataEntryComponent

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1507)

Create release version 0.7.11

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1508)

Bump version to 0.7.12-alpha.0

---

package-lock.json
package.json

Bump version to prepare for release 0.7.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1510)

Bump version to 0.7.12

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1511)

Bump version to 0.7.13-alpha.0

---

src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx

Fixes #1515
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1525)

Fix new-entry note bug

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1533)

Release 0.7.13

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1535)

Bump version to 0.7.14-alpha.0

---

src/components/ProjectSettings/ProjectSettingsComponent.tsx
src/resources/translations.json

Closes #1543
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1544)

Rename Project Settings "Interface Language" header

---

Backend.Tests/Models/ProjectTests.cs
Backend/Models/Project.cs
Backend/Repositories/ProjectRepository.cs
src/api/models/project.ts
src/components/DataEntry/DataEntryTable/RecentEntry/tests/RecentEntry.test.tsx
src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx
src/components/Pronunciations/tests/Pronunciations.test.tsx
src/components/TreeView/TreeViewComponent.tsx
src/components/TreeView/index.ts
src/components/TreeView/tests/TreeViewComponent.test.tsx
src/goals/CharInventoryCreation/tests/CharacterInventoryComponent.test.tsx
src/index.tsx
src/resources/translations.json
src/types/project.ts

Resolves #1542
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1545)

Add SemDomWritingSystem to project settings

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1550)

Bump version to 0.7.15-alpha.0

---

scripts/importSemanticDomains.ts
src/resources/semantic-domains/en.json

* Generate the .json from the latest FieldWorks data
* Add comment to the top of the script file to explain
what input data is expected
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1549)

Update the English semantic domains

---

.editorconfig
src/components/DataEntry/DataEntryTable/EntryCellComponents/VernWithSuggestions.tsx
src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx

Closes #1538
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1552)

[NewEntry] Shift focus on ENTER if selected suggestion matches types vernacular 

---

.editorconfig
package-lock.json
package.json
src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTable.tsx

Related to #1421
This is a stop-gap to avoid an issue of the frontend locking up for 1-2 minutes until #1421 is better resolved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1554)

Reduce maximum row size in Review Entries

---

src/components/DataEntry/DataEntryComponent.tsx
src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx
src/components/GoalTimeline/GoalTimelineComponent.tsx
src/components/Login/LoginPage/LoginComponent.tsx
src/components/ProjectInvite/ProjectInviteComponent.tsx
src/components/ProjectScreen/CreateProject/CreateProjectComponent.tsx
src/components/ProjectSettings/ProjectImport/ProjectImport.tsx
src/components/ProjectSettings/ProjectLanguages/ProjectLanguages.tsx
src/components/ProjectSettings/ProjectUsers/EmailInvite.tsx
src/components/SiteSettings/UserManagement/UserList.tsx
src/goals/CharInventoryCreation/components/CharacterDetail/FindAndReplace/FindAndReplaceComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1562)

Cleanup this.setState usage

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1559)

Bump version to 0.7.15

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1567)

Bump version to 0.7.16-alpha.0

---

src/components/DataEntry/DataEntryComponent.tsx
src/components/DataEntry/ExistingDataTable/ExistingDataTable.tsx
src/components/DataEntry/ExistingDataTable/ImmutableExistingData.tsx
src/components/DataEntry/tests/DataEntryComponent.test.tsx
src/types/word.ts

Resolves #1563
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1564)

Refactor DomainWord to avoid duplicate keys

---

docs/user_guide/docs/project.md

Closes #1557 
Also
- Fix broken link to Lexique Pro
- Wrap some long indented lines that `prettier` skips
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1570)

Document semantic domain language project setting

---

docs/user_guide/docs/licenses/backend_licenses.txt
docs/user_guide/docs/licenses/frontend_licenses.txt
package-lock.json

Ran `npm update` then `npm run license-report-frontend`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1574)

npm update; update frontend license report

---

.github/actions/combine-deploy-update/action.yml
.github/workflows/deploy_qa.yml

Fix issue where an input was tested as a boolean instead of a string.  See GitHub Actions issue [Boolean inputs are not actually booleans #1483](https://github.com/actions/runner/issues/1483)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1578)

Fix "Deploy Update to QA Server" action

---

src/components/AppBar/UserMenu.tsx

Fixes #1577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1588)

[UserMenu] Fix anchor settings conflict

---

src/components/Buttons/DeleteEditTextDialog.tsx
src/components/Buttons/FlagButton.tsx
src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/resources/translations.json

Resolves #1582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1589)

[FlagButton] Add text dialog with edit/delete/cancel options

---

Backend/Services/WordService.cs

Resolves: #1585 
Only mark it as a duplicate if a word with the same vernacular *also* has a blank gloss *and* has the same semantic domain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1591)

[DataEntry > NewEntry] Don't tag as duplicate if gloss is blank

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1596)

Bump version for Release 0.7.16

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1597)

Bump version to 0.7.17-alpha.0

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1605)

Bump version for Release 0.7.17

---

Backend.Tests/Services/WordServiceTests.cs
Backend.Tests/Util.cs

Resolves #1592
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1593)

Add tests for WordIsUnique()

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1606)

Bump version to 0.7.18-alpha.0

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1613)

Bump version for Release 0.7.18

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1625)

Set version for Release 0.7.19

---

src/goals/ReviewEntries/ReviewEntriesComponent/ReviewEntriesTable.tsx

Fixes #1629
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1630)

Fix column filter

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1632)

Bump version for release 0.7.20

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1633)

Bump version to 0.7.21-alpha.0

---

src/types/writingSystem.ts

Fixes #1641
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1642)

Fix code for French in list of supported ui langs

---

deploy/helm/thecombine/Chart.yaml
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1647)

Bump version to 0.7.22-alpha.0

---

deploy/helm/thecombine/Chart.yaml
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1659)

Bump version to 0.7.23-alpha.0

---

docs/user_guide/docs/dataEntry.md
docs/user_guide/docs/goals.md
docs/user_guide/docs/project.md
src/resources/translations.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1660)

Update README per feedback from Kevin

---

.github/workflows/backend.yml
Backend/BackendFramework.csproj
Backend/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1663)

Revert dotnet to 6.0.x

---

Backend/Services/LiftService.cs
deploy/ansible/ansible.cfg
docs/user_guide/docs/admin.md
docs/user_guide/docs/dataEntry.md
docs/user_guide/docs/goals.md
docs/user_guide/docs/index.md
docs/user_guide/docs/project.md
src/components/TreeView/tests/MockSemanticDomain.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1673)

Fix documentation based on Kevin's feedback

---

docs/user_guide/mkdocs.yml

One thing missed in #1673
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1674)

Hyphenate adjectival noun phrases

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1675)

Bump version for Release 0.7.24

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1676)

Bump version to 0.7.25-alpha.0

---

docs/user_guide/docs/licenses/frontend_licenses.txt
package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1698)

npm update

---

src/goals/MergeDupGoal/MergeDupStep/MergeDupStepComponent.tsx

Resolves #1705
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1707)

[MergeStep] Convert Save&Continue Button to LoadingButton

---

deploy/scripts/build.py
deploy/scripts/enum_types.py
deploy/scripts/setup_cluster.py
deploy/scripts/streamfile.py
deploy/scripts/utils.py

Change the build script to build the frontend, backend, and maintenance components for _The Combine_ as parallel jobs.  By default, the build output is not shown, only the progress.
This mechanism decreases the build time for a clean build by approximately 25%.  If the image is also pushed to AWS ECR, the build time is reduced by approximately 35%.
Closes #1594.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1709)

Build "The Combine" Docker images in parallel

---

src/components/TreeView/TreeSearch.tsx
src/components/TreeView/tests/TreeSearch.test.tsx

Fixes #794 (again)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1710)

Move stopPropagation back to onKeyDown

---

src/goals/ReviewEntries/ReviewEntriesComponent/CellColumns.tsx
src/goals/ReviewEntries/ReviewEntriesComponent/tests/CellColumns.test.tsx

Resolves #1714
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1715)

Review entries domain filter

---

.github/workflows/deploy_release.yml
docs/deploy/kubernetes_design/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1728)

Add 'database' to list of components to build

---

Backend/Services/LiftService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1740)

Export entry id: vern -> vern_guid

---

README.md
database/init/update-semantic-domains.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/thecombine/1746)

Change update mode for Semantic Domain database items

---

.github/workflows/scorecards.yml

Update the _Scorecards supply-chain security_ GitHub Action as follows:
- Add required endpoints missed in audit of previous runs
- Run action on PR update to enable testing before PR merge
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1817)

Update OSSF Scorecards action

---

.github/workflows/backend.yml
.github/workflows/codeql.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/1982)

Update codeql tests to resolve endpoint access failures

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/scorecards.yml
Backend/BackendFramework.csproj
deploy/requirements.txt
dev-requirements.txt
maintenance/requirements.txt
package-lock.json
package.json

Update dependencies identified by `dependabot` for the week of 03 Apr 2023.
Note that instead of updating the `@mui/lab` dependency, it was removed.  `@mui/lab` is no longer referenced by the frontend code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2001)

Dependabot updates for week of 3 Apr 2023

---

src/components/DataEntry/DataEntryComponent.tsx
src/components/DataEntry/DataEntryTable/DataEntryTable.tsx
src/components/DataEntry/ExistingDataTable/ExistingDataTable.tsx

Fixes #2072 
Fixes #2073
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2074)

Fix minor existing data drawer bugs

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/scorecards.yml
Backend/BackendFramework.csproj
Backend/Dockerfile
deploy/requirements.txt
dev-requirements.txt
docs/user_guide/docs/licenses/backend_licenses.txt
docs/user_guide/docs/licenses/frontend_licenses.txt
maintenance/requirements.txt
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2107)

Dependabot updates for week of 01 May 2023

---

Backend.Tests/Controllers/LiftControllerTests.cs
Backend/Controllers/LiftController.cs
Backend/Helper/CombineHub.cs
package-lock.json
src/components/AnnouncementBanner/AnnouncementBanner.tsx
src/components/App/SignalRHub.tsx
src/components/ProjectExport/DownloadButton.tsx
src/components/ProjectExport/Redux/ExportProjectActions.ts

The added error handling is because, without it, a failed export gets the frontend stuck on "export in progress" so the user cannot try to export again, even on a different project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2115)

Refactor banner and export/download

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/combine_deploy_image.yml
.github/workflows/database.yml
.github/workflows/deploy_qa.yml
.github/workflows/deploy_release.yml
.github/workflows/frontend.yml
.github/workflows/maintenance.yml
.github/workflows/pages.yml
.github/workflows/python.yml
.github/workflows/scorecards.yml
Backend/Dockerfile
Dockerfile
database/Dockerfile
docs/user_guide/docs/licenses/frontend_licenses.txt
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2132)

Dependabot updates for week of 08 May 2023

---

src/components/AppBar/AppBarComponent.tsx
src/components/AppBar/Logo.tsx
src/goals/MergeDupGoal/MergeDupStep/DragDropComponents/MergeDragDrop.tsx

Also, adjust AppBar to mitigate overflows
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2142)

[MergeDupStep] Improve trash positioning

---

public/locales/en/translation.json
src/goals/CharInventoryCreation/components/CharacterList/CharacterCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2147)

Cleanup UI strings

---

Backend/Controllers/LiftController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2197)

Improve failure logging on lift export

---

public/locales/en/translation.json
src/components/App/AppLoggedIn.tsx
src/components/UserSettings/ClickableAvatar.tsx
src/components/UserSettings/UserSettings.tsx
src/components/UserSettings/tests/AvatarUpload.test.tsx
src/components/UserSettings/tests/UserSettings.test.tsx
src/i18n.ts

Resolves #706
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2199)

[UserSettings] Add ui-lang selector

---

src/components/DataEntry/DataEntryTable/NewEntry/NewEntry.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2225)

Bugfix: Remove erroneous !

---

.prettierignore
.vscode/settings.json
Backend/Startup.cs
README.md
docs/deploy/README.md
docs/deploy/kubernetes_design/README.md
scripts/genBackendCoverageReport.ts
scripts/setRelease.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2252)

Fix spelling

---

.vscode/extensions.json
.vscode/settings.json
README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2254)

Add the missing final s

---

src/components/AppBar/NavigationButtons.tsx
src/components/AppBar/ProjectButtons.tsx
src/utilities/useWindowSize.tsx

Resolves #2250
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2273)

[AppBar] Adjust nav button width based on window width

---

Backend.Tests/Util.cs
Backend/Models/Word.cs
src/api/models/word.ts

Resolves #2279
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2280)

[Backend > Models > Word] Remove PartOfSpeech

---

src/components/DataEntry/ExistingDataTable/ExistingDataTable.tsx

Fixes #609
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2284)

[ExistingDataTable] Keep height less than window's

---

src/components/App/component.tsx
src/components/ProjectSettings/ProjectLanguages.tsx
src/components/ProjectSettings/ProjectUsers/AddProjectUsers.tsx
src/components/Pronunciations/AudioRecorder.tsx
src/components/Pronunciations/tests/__snapshots__/Pronunciations.test.tsx.snap
src/components/SiteSettings/UserManagement/UserManagement.tsx
src/components/Toast/UpperRightToastContainer.tsx

Some toast popped up from the bottom. Other toast appeared in the designated location (upper-right corner), but twice. This rectifies both.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2283)

Consolidate the toast

---

src/components/ProjectSettings/ProjectName.tsx
src/components/ProjectSettings/ProjectSwitch.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2307)

[ProjectSettings] Fix ProjectName not updating on project switch

---

Backend/Models/Project.cs
Backend/Services/LiftService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2335)

Make writing system handling more robust

---

docs/user_guide/docs/account.md
docs/user_guide/docs/goals.md
docs/user_guide/docs/project.md
src/components/Login/LoginPage/LoginComponent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2350)

[User Guide] Incorporate feedback

---

src/components/DataEntry/DataEntryTable/EntryCellComponents/tests/GlossWithSuggestions.test.tsx
src/components/DataEntry/DataEntryTable/EntryCellComponents/tests/VernWithSuggestions.test.tsx
src/setupTests.js

Resolves #2048 and prevents new console errors and warnings from slipping into our tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2351)

[frontend] Fail any test with console error/warn

---

Backend.Tests/Mocks/PermissionServiceMock.cs
Backend/Controllers/InviteController.cs
Backend/Controllers/UserRoleController.cs
Backend/Interfaces/IPermissionService.cs
Backend/Services/PermissionService.cs
public/locales/en/translation.json
src/api/models/role.ts
src/api/models/writing-system.ts
src/backend/index.ts
src/components/Project/ProjectActions.ts
src/components/ProjectSettings/ProjectUsers/ActiveProjectUsers.tsx
src/components/ProjectSettings/ProjectUsers/AddProjectUsers.tsx
src/components/ProjectSettings/ProjectUsers/CancelConfirmDialogCollection.tsx
src/components/ProjectSettings/index.tsx
src/components/SiteSettings/ProjectManagement/ProjectManagement.tsx
src/components/SiteSettings/ProjectManagement/ProjectUsersButtonWithConfirmation.tsx

Half of #708
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2370)

[SiteSettings] Let site admins manage users on all projects

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/combine_deploy_image.yml
.github/workflows/pages.yml
.github/workflows/python.yml
.github/workflows/scorecards.yml
Backend/BackendFramework.csproj
Backend/Dockerfile
database/Dockerfile
deploy/requirements.txt
dev-requirements.txt
maintenance/requirements.txt
package-lock.json
package.json
src/components/DataEntry/DataEntryTable/index.tsx
src/components/Pronunciations/RecorderIcon.tsx
src/components/Pronunciations/tests/Pronunciations.test.tsx
src/components/Pronunciations/tests/__snapshots__/Pronunciations.test.tsx.snap
tox.ini

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2397)

Dependabot updates for week of 17 July 2023

---

src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/DragSense.tsx

Fixes #2411
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2412)

[DragSense] Add array equality check to selector

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2431)

Simplify .gitignore rules

---

public/locales/ar/translation.json
public/locales/es/translation.json
public/locales/fr/translation.json
public/locales/pt/translation.json

Downloaded the current translations from CrowdIn and processed with https://github.com/sillsdev/react-localize-crowdin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2432)

Update: ar, es, fr, pt

---

src/components/ProjectSettings/ProjectSchedule/DateSelector.tsx
src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts
src/utilities/utilities.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2463)

Avoid implicit any[] arrays

---

src/components/UserSettings/tests/UserSettings.test.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2508)

Modify tests

---

deploy/helm/aws-login/values.yaml
deploy/helm/thecombine/charts/frontend/templates/deployment-frontend.yaml
deploy/helm/thecombine/charts/maintenance/templates/cronjob-daily-backup.yaml
deploy/helm/thecombine/charts/maintenance/templates/deployment-maintenance.yaml
deploy/helm/thecombine/charts/maintenance/templates/env-maintenance-configmap.yaml
deploy/helm/thecombine/charts/maintenance/templates/font-storage-persistent-volume-claim.yaml
deploy/helm/thecombine/charts/maintenance/values.yaml
deploy/helm/thecombine/values.yaml
maintenance/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2509)

Font support jmg

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/combine_deploy_image.yml
.github/workflows/database.yml
.github/workflows/deploy_qa.yml
.github/workflows/deploy_release.yml
.github/workflows/frontend.yml
.github/workflows/maintenance.yml
.github/workflows/pages.yml
.github/workflows/python.yml
.github/workflows/scorecards.yml
Backend/BackendFramework.csproj
Dockerfile
deploy/requirements.txt
dev-requirements.txt
docs/user_guide/default/licenses/backend_licenses.txt
docs/user_guide/default/licenses/frontend_licenses.txt
maintenance/requirements.txt
package-lock.json
package.json
src/api/api/project-api.ts
src/api/api/user-api.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2527)

Dependabot updates for week of 28 August 2023

---

src/components/ProjectScreen/CreateProject/index.tsx

Closes #2532
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2533)

Fix label for Analysis Language field

---

src/components/DataEntry/DataEntryTable/RecentEntry.tsx

Fixes #2570
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2571)

[RecentEntry] Don't allow empty vernacular

---

src/components/ProjectScreen/ChooseProject.tsx
src/components/ProjectScreen/tests/ChooseProject.test.tsx

Resolves #2460
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2617)

Sort ChooseProject list alphabetically

---

src/goals/CharacterInventory/CharInv/CharacterDetail/FindAndReplace/index.tsx

Resolves #2581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2639)

Use TextFieldWithFont for find-and-replace

---

src/utilities/fontCssUtilities.ts
src/utilities/tests/fontCssUtilities.test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2641)

Add tests for fontCssUtilities

---

deploy/scripts/setup_files/profiles/nuc.yaml
deploy/scripts/setup_files/profiles/nuc_qa.yaml

Follow-up to #2549
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2648)

Add UI language zh (Chinese) to nuc profile localLangList

---

Backend/Services/EmailService.cs

Progress on #2647
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2671)

[EmailService] Exclude from test coverage

---

src/components/DataEntry/DataEntryTable/tests/index.test.tsx

Frontend unit testing for #2659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2662)

[DataEntry] Add sem-dom testing

---

.vscode/settings.json
docs/user_guide/docs/en/admin.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2714)

[User Guide] Fix typo

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/scorecards.yml
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2719)

Dependabot updates for 16 October 2023

---

Backend.Tests/Mocks/PermissionServiceMock.cs
Backend.Tests/Services/PermissionServiceTests.cs
Backend/Controllers/AudioController.cs
Backend/Controllers/InviteController.cs
Backend/Controllers/LiftController.cs
Backend/Controllers/MergeController.cs
Backend/Controllers/ProjectController.cs
Backend/Controllers/StatisticsController.cs
Backend/Controllers/UserEditController.cs
Backend/Controllers/UserRoleController.cs
Backend/Controllers/WordController.cs
Backend/Interfaces/IPermissionService.cs
Backend/Services/PermissionService.cs

Fixes #2675
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2712)

[PermissionService] Replace brittle project id check

---

scripts/setRelease.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2741)

Fix comment description of setRelease.js

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/database.yml
.github/workflows/deploy_qa.yml
.github/workflows/deploy_release.yml
.github/workflows/frontend.yml
.github/workflows/maintenance.yml
.github/workflows/pages.yml
.github/workflows/python.yml
.github/workflows/scorecards.yml
Backend/BackendFramework.csproj
Backend/Dockerfile
deploy/requirements.txt
dev-requirements.txt
docs/user_guide/assets/licenses/backend_licenses.txt
docs/user_guide/assets/licenses/frontend_licenses.txt
maintenance/requirements.txt
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2773)

Dependabot Updates for November 2023

---

src/goals/ReviewEntries/ReviewEntriesTable/CellColumns.tsx
src/goals/ReviewEntries/ReviewEntriesTable/CellComponents/DeleteCell.tsx
src/goals/ReviewEntries/ReviewEntriesTable/CellComponents/tests/DeleteCell.test.tsx
src/goals/ReviewEntries/ReviewEntriesTypes.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2823)

Expand DeleteCell testing

---

src/components/Login/Login.tsx

Fixes #2830
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2831)

[Login] Fix button layout

---

src/components/ProjectSettings/tests/index.test.tsx
src/components/ProjectUsers/tests/SpeakerConsentListItemIcon.test.tsx
src/components/SiteSettings/tests/index.test.tsx

Resolves #2891
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2892)

Remove `act` from around `@testing-library` user events

---

src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts
src/store.ts
src/types/hooks.ts
src/utilities/testUtilities.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2894)

Fix `import` order by moving 'type'

---

src/goals/MergeDuplicates/Redux/MergeDupsReducer.ts
src/goals/MergeDuplicates/Redux/tests/MergeDupsDataMock.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/2898)

[MergeDups] Clean up auto-merging of definitions

---

.github/workflows/commit_message_check.yml

with multiple
issues in the initial commit comment to see if it is working or not when we call the fieldworks job
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3019)

Add a commit message checker.

---

README.md
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3116)

Update 1.0.0 to 2.0.0

---

.github/workflows/backend.yml
Backend/BackendFramework.csproj
Backend/Dockerfile
README.md

Resolves some instances of #927 (e.g., imnasnainaec's macOS 14), but not all (e.g., andracc's macOS 12).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3171)

Update icu.net; Fix ubuntu 22.04

---

.github/workflows/backend.yml
.github/workflows/codeql.yml
.github/workflows/combine_deploy_image.yml
.github/workflows/commit_message_check.yml
.github/workflows/database.yml
.github/workflows/deploy_qa.yml
.github/workflows/deploy_release.yml
.github/workflows/frontend.yml
.github/workflows/maintenance.yml
.github/workflows/pages.yml
.github/workflows/python.yml
.github/workflows/scorecards.yml
Backend/BackendFramework.csproj
Backend/Dockerfile
database/Dockerfile
deploy/requirements.txt
dev-requirements.txt
docs/user_guide/assets/licenses/backend_licenses.txt
docs/user_guide/assets/licenses/frontend_licenses.txt
maintenance/requirements.txt
package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3222)

Dependabot updates for July 2024

---

README.md

Follow-up to #3172 
[Before](https://github.com/sillsdev/TheCombine?tab=readme-ov-file#the-combine):
[After](https://github.com/sillsdev/TheCombine/tree/readme-id?tab=readme-ov-file#the-combine):
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3219)

[README] Add Id (Indonesian) to sem-dom badge

---

src/components/DataEntry/DataEntryTable/EntryCellComponents/tests/GlossWithSuggestions.test.tsx
src/components/DataEntry/DataEntryTable/EntryCellComponents/tests/VernWithSuggestions.test.tsx

A little piece of #3180 and resolving a hang-up for #3041
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3304)

Move EntryCellComponents tests to @testing-library

---

package-lock.json
package.json
src/components/Pronunciations/Recorder.ts
src/components/WordCard/DomainChipsGrid.tsx
src/utilities/fontContext.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3303)

Update prettier and parentheses

---

Backend/Services/PermissionService.cs

Fixes #3256
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3314)

Increase login expire from 4 to 12 hours

---

LICENSE
docs/user_guide/mkdocs.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3367)

Update SIL International to SIL Global

---

README.md
deploy/scripts/install-combine.sh
deploy/scripts/kube_env.py
deploy/scripts/package_images.py
deploy/scripts/setup_cluster.py
deploy/scripts/setup_combine.py
deploy/scripts/uninstall-combine
deploy/scripts/utils.py
installer/README.md
installer/make-combine-installer.sh

Fixes a duplicate `--debug` arg issue from #3391
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3402)

[installer] Use --dependency-update; Fix debugging; Remove junk dirs

---

.github/workflows/backend.yml
.github/workflows/frontend.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3447)

[GHA] Update codecov endpoints

---

deploy/scripts/app_release.py

Fixes #3439
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3446)

[build] Allow on detached HEAD

---

src/components/DataEntry/DataEntryTable/index.tsx
src/goals/Redux/GoalActions.ts

Resolves #3471
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3523)

[MergeDups] Add failsafe for duplicate guids and other bad merge sets

---

Backend.Tests/Otel/LocationProviderTests.cs
Backend/Otel/LocationProvider.cs

Resolves #3534 (hopefully)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3533)

Tweak IP checking

---

Backend/Otel/LocationProvider.cs
Backend/Otel/OtelKernel.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3537)

[DEBUG] Dump all request headers to logs

---

docs/user_guide/assets/licenses/frontend_licenses.txt
package-lock.json
package.json
src/types/Redux/analytics.ts
src/types/Redux/analyticsReduxTypes.ts

Follow-up to #3467
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3535)

Remove unused vanilla-cookieconsent

---

Backend.Tests/Helper/DuplicateFinderTests.cs
Backend/Helper/DuplicateFinder.cs

Resolves #3468
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3550)

[MergeDups] For similar-vern words, compare glosses & definitions

---

src/components/Pronunciations/AudioRecorder.tsx
src/components/Pronunciations/PronunciationsFrontend.tsx
src/components/Pronunciations/Recorder.ts

Fixes #3555
To test, try various combinations of adding and removing recording in Data Entry (on both New and Recent entries) and in Review Entries (both in the pronunciation column of the main table and in a row's Edit Dialog).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3556)

[AudioRecorder] Fix bug preventing multiple recordings

---

src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/DropWord.tsx

Resolves #3559
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3560)

[MergeDups>DropWord] Always show protected word warning

---

src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3595)

[ReviewEntries] Eliminate unhandled edit error

---

LICENSE
docs/user_guide/mkdocs.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3597)

Update copyright to 2025

---

src/goals/MergeDuplicates/MergeDupsStep/MergeDragDrop/index.tsx

Groundwork for #3445
This is strictly a refactor and shouldn't have any changes in behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3562)

[MergeDragDrop] Refactor to use payloads, mergeTreeRefs

---

src/components/Login/Login.tsx
src/components/Login/Signup.tsx
src/components/Login/tests/Login.test.tsx
src/components/Login/tests/Signup.test.tsx

Part of #3180
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3616)

[Login, Signup] Move tests to @testing-library

---

src/components/DataEntry/DataEntryTable/NewEntry/StyledMenuItem.ts
src/components/DataEntry/DataEntryTable/NewEntry/VernDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3625)

[NewEntry>VernDialog] If only one entry, auto-expand senses

---

src/components/DataEntry/DataEntryHeader.tsx

Fixes #3541
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3674)

[DataEntry] Set domain description, questions to be bidi

---

src/goals/ReviewEntries/ReviewEntriesTable/Cells/DomainsCell.tsx

Follow-up to #3619/#3625 
Before & After
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3676)

[DataEntry] In 'Select an entry', fix sem-dom contrast

---

deploy/helm/thecombine/charts/maintenance/templates/cronjob-update-fonts.yaml
maintenance/scripts/mui_language_picker_fonts.txt

Get correct script execution from https://github.com/sillsdev/TheCombine/blob/v2.3.1/deploy/helm/thecombine/charts/maintenance/templates/get-fonts-hook.yaml#L40-L41
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3678)

[prod] Fix update-fonts CronJob

---

README.md
docs/deploy/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3706)

Update setup/deploy READMEs

---

README.md
deploy/scripts/install-combine.sh
installer/README.md
installer/make-combine-installer.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3710)

Update install & deploy READMEs & logging

---

Backend.Tests/Backend.Tests.csproj
Backend/BackendFramework.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3711)

[Backend] Dependency updates for May 2025

---

Backend/Helper/Language.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3712)

[import] Avoid empty lang-tags

---

docs/user_guide/docs/goals.es.md
docs/user_guide/docs/goals.md
docs/user_guide/docs/goals.zh.md
src/goals/ReviewEntries/ReviewEntriesTable/filterFn.ts
src/goals/ReviewEntries/ReviewEntriesTable/tests/filterFn.test.ts

Resolves #3714
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3715)

[ReviewEntries] Use whitespace filter for non-empty text

---

Backend/Services/LiftService.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3727)

[import] Trim whitespace off text

---

Backend/Helper/DuplicateFinder.cs
Backend/Services/MergeService.cs

Helps with #3720
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3731)

[MergeDups] Decrease max similarity score to speed up dup finder

---

Backend/Controllers/LiftController.cs
Backend/Helper/GrammaticalCategory.cs
docs/deploy/README.md
docs/user_guide/assets/licenses/backend_licenses.txt
src/components/DataEntry/DataEntryTable/NewEntry/index.tsx
src/components/Project/ProjectReduxTypes.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3732)

Update backend license report; Fix typos

---

src/goals/MergeDuplicates/Redux/reducerUtilities.ts
src/goals/MergeDuplicates/Redux/tests/reducerUtilities.test.ts

Resolves #3742
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3743)

[MergeDups] Make gloss and definition merging more uniform

---

Backend/Helper/Sanitization.cs

Resolves #3799
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3804)

Allow apostrophe in file names

---

src/goals/ReviewEntries/ReviewEntriesTable/Cells/EditCell/EditSenseDialog.tsx

Fixes #3791
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3805)

[ReviewEntries] Prevent empty dialog after Enter-selecting domain

---

package-lock.json
package.json
src/components/Statistics/LineChartComponent.tsx
src/utilities/tests/utilities.test.ts
src/utilities/utilities.ts

Fixes #3809
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3810)

[Statistics] Fix line-graph color loading error

---

Backend.Tests/Mocks/UserRepositoryMock.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3840)

[UserRepositoryMock] Fix Update error when no user found

---

Backend.Tests/Controllers/BannerControllerTests.cs
Backend/Controllers/BannerController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3842)

[BannerController] Add missing ProducesResponseType for Status403Forbidden

---

Backend.Tests/Controllers/InviteControllerTests.cs
Backend/Controllers/InviteController.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3843)

[InviteController] Add ProducesResponseType attributes, one test

---

src/components/Login/tests/Login.test.tsx
src/components/Login/tests/Signup.test.tsx
src/components/ProjectUsers/tests/SpeakerConsentListItemIcon.test.tsx

This is a vestige of `react-test-renderer`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3856)

Remove act from around testing-library async clicks

---

maintenance/scripts/rm_project.py

Resolves #3859
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3861)

[maintenance/scripts] In rm_project.py, update collections

---

.github/dependabot.yml
.github/workflows/frontend.yml
Dockerfile
README.md
package-lock.json
package.json

Resolves #3900
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3903)

Upgrade Node from 20 to 22 LTS

---

.github/labeler.yml
.github/workflows/labeler.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3923)

Add GHA workflow with pr labeler

---

src/components/Buttons/DeleteButtonWithDialog.tsx
src/components/Buttons/FlagButton.tsx
src/components/Dialogs/DeleteEditTextDialog.tsx
src/components/Dialogs/EditTextDialog.tsx
src/components/Dialogs/SubmitTextDialog.tsx
src/components/ProjectUsers/EmailInvite.tsx
src/components/ProjectUsers/tests/EmailInvite.test.tsx
src/components/ProjectUsers/tests/ProjectSpeakersList.test.tsx
src/components/ProjectUsers/tests/SortOptions.test.tsx

Part of #3180
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3935)

Migrate ProjectUsers components to testing-library

---

src/components/GoalTimeline/GoalHistoryButton.tsx
src/components/WordCard/DomainChip.tsx
src/components/WordCard/SummarySenseCard.tsx
src/components/WordCard/index.tsx
src/utilities/utilities.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/TheCombine/3933)

Implement getLocalizedDateTimeString; Add onlyId to DomainChip
